/**
 * Maintenance Domain - Domain Events
 * Typed domain events for event-driven architecture
 */

export type MaintenanceEventType =
  | 'MaintenanceScheduleCreated'
  | 'MaintenanceScheduleUpdated'
  | 'MaintenanceScheduleDeleted'
  | 'MaintenanceScheduleCompleted'
  | 'MaintenanceScheduleOverdue'
  | 'MaintenanceAutoScheduled'
  | 'MaintenanceTemplateCreated'
  | 'MaintenanceTemplateUpdated'
  | 'MaintenanceTemplateDeleted';

export interface DomainEventBase {
  eventId: string;
  eventType: MaintenanceEventType;
  aggregateId: string;
  aggregateType: 'MaintenanceSchedule' | 'MaintenanceTemplate';
  occurredAt: Date;
  userId?: string;
  orgId: string;
  version: number;
}

export interface MaintenanceScheduleCreatedEvent extends DomainEventBase {
  eventType: 'MaintenanceScheduleCreated';
  aggregateType: 'MaintenanceSchedule';
  payload: {
    equipmentId: string;
    scheduledDate: Date;
    maintenanceType: string;
    priority: string;
    autoGenerated?: boolean;
    pdmScore?: number;
  };
}

export interface MaintenanceScheduleUpdatedEvent extends DomainEventBase {
  eventType: 'MaintenanceScheduleUpdated';
  aggregateType: 'MaintenanceSchedule';
  payload: {
    previousState: Record<string, unknown>;
    newState: Record<string, unknown>;
    changedFields: string[];
  };
}

export interface MaintenanceScheduleDeletedEvent extends DomainEventBase {
  eventType: 'MaintenanceScheduleDeleted';
  aggregateType: 'MaintenanceSchedule';
  payload: {
    equipmentId: string;
    scheduledDate: Date;
    reason?: string;
  };
}

export interface MaintenanceScheduleCompletedEvent extends DomainEventBase {
  eventType: 'MaintenanceScheduleCompleted';
  aggregateType: 'MaintenanceSchedule';
  payload: {
    equipmentId: string;
    completedAt: Date;
    completedBy: string;
    actualDuration?: number;
    notes?: string;
  };
}

export interface MaintenanceScheduleOverdueEvent extends DomainEventBase {
  eventType: 'MaintenanceScheduleOverdue';
  aggregateType: 'MaintenanceSchedule';
  payload: {
    equipmentId: string;
    scheduledDate: Date;
    daysOverdue: number;
  };
}

export interface MaintenanceAutoScheduledEvent extends DomainEventBase {
  eventType: 'MaintenanceAutoScheduled';
  aggregateType: 'MaintenanceSchedule';
  payload: {
    equipmentId: string;
    scheduledDate: Date;
    pdmScore: number;
    triggerSource: 'pdm_prediction' | 'rul_threshold' | 'anomaly_detection';
    modelId?: string;
    modelVersion?: string;
  };
}

export interface MaintenanceTemplateCreatedEvent extends DomainEventBase {
  eventType: 'MaintenanceTemplateCreated';
  aggregateType: 'MaintenanceTemplate';
  payload: {
    name: string;
    equipmentType?: string;
    maintenanceType: string;
  };
}

export interface MaintenanceTemplateUpdatedEvent extends DomainEventBase {
  eventType: 'MaintenanceTemplateUpdated';
  aggregateType: 'MaintenanceTemplate';
  payload: {
    previousState: Record<string, unknown>;
    newState: Record<string, unknown>;
    changedFields: string[];
  };
}

export interface MaintenanceTemplateDeletedEvent extends DomainEventBase {
  eventType: 'MaintenanceTemplateDeleted';
  aggregateType: 'MaintenanceTemplate';
  payload: {
    name: string;
    equipmentType?: string;
  };
}

export type MaintenanceDomainEvent =
  | MaintenanceScheduleCreatedEvent
  | MaintenanceScheduleUpdatedEvent
  | MaintenanceScheduleDeletedEvent
  | MaintenanceScheduleCompletedEvent
  | MaintenanceScheduleOverdueEvent
  | MaintenanceAutoScheduledEvent
  | MaintenanceTemplateCreatedEvent
  | MaintenanceTemplateUpdatedEvent
  | MaintenanceTemplateDeletedEvent;

export function createEventId(): string {
  return `evt_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
}
