import type { IEventPublisher, IRealtimeSyncPort, IAuditPort } from '../domain/ports';
import type { MaintenanceDomainEvent } from '../domain/events';
import { domainEventBus, createDomainEvent } from '../../../lib/domain-event-bus/index.js';
import { createLogger } from '../../../lib/structured-logger';

const logger = createLogger("MaintenanceEventPublisher");

function emitTypedEvent(event: MaintenanceDomainEvent): void {
  switch (event.eventType) {
    case 'MaintenanceScheduleCreated':
      domainEventBus.emit("maintenance.scheduled", createDomainEvent("maintenance.scheduled", event.orgId, {
        equipmentId: event.payload.equipmentId,
        scheduledDate: event.payload.scheduledDate,
        maintenanceType: event.payload.maintenanceType,
        priority: event.payload.priority,
        autoGenerated: event.payload.autoGenerated,
        pdmScore: event.payload.pdmScore,
      }, { aggregateId: event.aggregateId, aggregateType: "MaintenanceSchedule" }));
      break;
    case 'MaintenanceScheduleUpdated':
      domainEventBus.emit("maintenance.updated", createDomainEvent("maintenance.updated", event.orgId, {
        previousState: event.payload.previousState,
        newState: event.payload.newState,
        changedFields: event.payload.changedFields,
      }, { aggregateId: event.aggregateId, aggregateType: "MaintenanceSchedule" }));
      break;
    case 'MaintenanceScheduleDeleted':
      domainEventBus.emit("maintenance.deleted", createDomainEvent("maintenance.deleted", event.orgId, {
        equipmentId: event.payload.equipmentId,
        scheduledDate: event.payload.scheduledDate,
        reason: event.payload.reason,
      }, { aggregateId: event.aggregateId, aggregateType: "MaintenanceSchedule" }));
      break;
    case 'MaintenanceScheduleCompleted':
      domainEventBus.emit("maintenance.completed", createDomainEvent("maintenance.completed", event.orgId, {
        equipmentId: event.payload.equipmentId,
        completedAt: event.payload.completedAt,
        completedBy: event.payload.completedBy,
        actualDuration: event.payload.actualDuration,
        notes: event.payload.notes,
      }, { aggregateId: event.aggregateId, aggregateType: "MaintenanceSchedule" }));
      break;
    case 'MaintenanceScheduleOverdue':
      domainEventBus.emit("maintenance.overdue", createDomainEvent("maintenance.overdue", event.orgId, {
        equipmentId: event.payload.equipmentId,
        scheduledDate: event.payload.scheduledDate,
        daysOverdue: event.payload.daysOverdue,
      }, { aggregateId: event.aggregateId, aggregateType: "MaintenanceSchedule" }));
      break;
    case 'MaintenanceAutoScheduled':
      domainEventBus.emit("maintenance.auto_scheduled", createDomainEvent("maintenance.auto_scheduled", event.orgId, {
        equipmentId: event.payload.equipmentId,
        scheduledDate: event.payload.scheduledDate,
        pdmScore: event.payload.pdmScore,
        triggerSource: event.payload.triggerSource,
        modelId: event.payload.modelId,
        modelVersion: event.payload.modelVersion,
      }, { aggregateId: event.aggregateId, aggregateType: "MaintenanceSchedule" }));
      break;
    case 'MaintenanceTemplateCreated':
      domainEventBus.emit("maintenance.template_created", createDomainEvent("maintenance.template_created", event.orgId, {
        name: event.payload.name,
        equipmentType: event.payload.equipmentType,
        maintenanceType: event.payload.maintenanceType,
      }, { aggregateId: event.aggregateId, aggregateType: "MaintenanceTemplate" }));
      break;
    case 'MaintenanceTemplateUpdated':
      domainEventBus.emit("maintenance.template_updated", createDomainEvent("maintenance.template_updated", event.orgId, {
        previousState: event.payload.previousState,
        newState: event.payload.newState,
        changedFields: event.payload.changedFields,
      }, { aggregateId: event.aggregateId, aggregateType: "MaintenanceTemplate" }));
      break;
    case 'MaintenanceTemplateDeleted':
      domainEventBus.emit("maintenance.template_deleted", createDomainEvent("maintenance.template_deleted", event.orgId, {
        name: event.payload.name,
        equipmentType: event.payload.equipmentType,
      }, { aggregateId: event.aggregateId, aggregateType: "MaintenanceTemplate" }));
      break;
  }
}

export class EventPublisherAdapter implements IEventPublisher {
  async publish(event: MaintenanceDomainEvent): Promise<void> {
    try {
      emitTypedEvent(event);
      logger.info("Published maintenance domain event", { eventType: event.eventType });
    } catch (error) {
      logger.error("Failed to publish maintenance domain event", { eventType: event.eventType, error });
      throw error;
    }
  }

  async publishBatch(events: MaintenanceDomainEvent[]): Promise<void> {
    for (const event of events) {
      await this.publish(event);
    }
  }
}

export class RealtimeSyncAdapter implements IRealtimeSyncPort {
  async publishChange(params: {
    entityType: string;
    operation: 'create' | 'update' | 'delete';
    entityId: string;
    payload: unknown;
  }): Promise<void> {
    logger.info("Realtime sync delegated to domain event bus bridge", { entityType: params.entityType, operation: params.operation });
  }
}

export class AuditAdapter implements IAuditPort {
  async record(params: {
    entityType: string;
    entityId: string;
    operation: string;
    payload: unknown;
    userId?: string;
  }): Promise<void> {
    logger.info("Audit record delegated to domain event bus journal", { entityType: params.entityType, operation: params.operation });
  }
}

export const eventPublisher = new EventPublisherAdapter();
export const realtimeSync = new RealtimeSyncAdapter();
export const auditAdapter = new AuditAdapter();
