/**
 * Alerts - Database Storage
 */

import { randomUUID } from "node:crypto";
import { eq, and, sql, gte } from "drizzle-orm";
import { db } from "../../db-config";
import { alertConfigurations, alertNotifications, alertSuppressions, alertComments, type AlertConfiguration, type InsertAlertConfig, type AlertNotification, type InsertAlertNotification, type AlertSuppression, type InsertAlertSuppression, type AlertComment, type InsertAlertComment } from "@shared/schema-runtime";

export class DatabaseAlertStorage {
  private validateOrgId(orgId: string | undefined, method: string): void { if (!orgId) {console.warn(`[${method}] Missing orgId - potential security issue`);} }

  async getAlertConfigurations(equipmentId?: string, orgId?: string): Promise<AlertConfiguration[]> { const conditions: any[] = []; if (orgId) {conditions.push(eq(alertConfigurations.orgId, orgId));} if (equipmentId) {conditions.push(eq(alertConfigurations.equipmentId, equipmentId));} if (conditions.length > 0) {return db.select().from(alertConfigurations).where(and(...conditions));} return db.select().from(alertConfigurations); }
  async getAlertConfiguration(id: string, orgId?: string): Promise<AlertConfiguration | undefined> { const conditions = orgId ? and(eq(alertConfigurations.id, id), eq(alertConfigurations.orgId, orgId)) : eq(alertConfigurations.id, id); const [result] = await db.select().from(alertConfigurations).where(conditions); return result; }
  async createAlertConfiguration(config: InsertAlertConfig): Promise<AlertConfiguration> { const [n] = await db.insert(alertConfigurations).values({ id: randomUUID(), ...config, createdAt: new Date(), updatedAt: new Date() }).returning(); return n; }
  async updateAlertConfiguration(id: string, updates: Partial<InsertAlertConfig>, orgId?: string): Promise<AlertConfiguration> { this.validateOrgId(orgId, "updateAlertConfiguration"); const conditions = orgId ? and(eq(alertConfigurations.id, id), eq(alertConfigurations.orgId, orgId)) : eq(alertConfigurations.id, id); const [updated] = await db.update(alertConfigurations).set({ ...updates, updatedAt: new Date() }).where(conditions).returning(); if (!updated) {throw new Error(`Alert configuration ${id} not found`);} return updated; }
  async deleteAlertConfiguration(id: string, orgId?: string): Promise<void> { this.validateOrgId(orgId, "deleteAlertConfiguration"); const conditions = orgId ? and(eq(alertConfigurations.id, id), eq(alertConfigurations.orgId, orgId)) : eq(alertConfigurations.id, id); await db.delete(alertConfigurations).where(conditions); }

  async getAlertNotifications(acknowledged?: boolean, orgId?: string): Promise<AlertNotification[]> { const conditions: any[] = []; if (orgId) {conditions.push(eq(alertNotifications.orgId, orgId));} if (acknowledged !== undefined) {conditions.push(eq(alertNotifications.acknowledged, acknowledged));} if (conditions.length > 0) {return db.select().from(alertNotifications).where(and(...conditions)).orderBy(sql`${alertNotifications.createdAt} DESC`);} return db.select().from(alertNotifications).orderBy(sql`${alertNotifications.createdAt} DESC`); }
  async getAlertNotificationsPaginated(acknowledged: boolean | undefined, orgId: string | undefined, limit: number, offset: number): Promise<{ items: AlertNotification[]; total: number }> { const conditions: any[] = []; if (acknowledged !== undefined) {conditions.push(eq(alertNotifications.acknowledged, acknowledged));} if (orgId) {conditions.push(eq(alertNotifications.orgId, orgId));} const countQuery = db.select({ count: sql<number>`count(*)` }).from(alertNotifications); const countResult = conditions.length > 0 ? await countQuery.where(and(...conditions)) : await countQuery; const total = Number(countResult[0]?.count || 0); const query = db.select().from(alertNotifications).orderBy(sql`${alertNotifications.createdAt} DESC`).limit(limit).offset(offset); const items = conditions.length > 0 ? await query.where(and(...conditions)) : await query; return { items, total }; }
  async hasRecentAlert(equipmentId: string, sensorType: string, alertType: string, minutesBack: number = 10): Promise<boolean> { const cutoffTime = new Date(Date.now() - minutesBack * 60 * 1000); const result = await db.select({ count: sql<number>`COUNT(*)` }).from(alertNotifications).where(and(eq(alertNotifications.equipmentId, equipmentId), eq(alertNotifications.sensorType, sensorType), eq(alertNotifications.alertType, alertType), eq(alertNotifications.acknowledged, false), gte(alertNotifications.createdAt, cutoffTime))); return (result[0]?.count || 0) > 0; }
  async getAlertNotification(id: string, orgId?: string): Promise<AlertNotification | undefined> { const conditions = orgId ? and(eq(alertNotifications.id, id), eq(alertNotifications.orgId, orgId)) : eq(alertNotifications.id, id); const [result] = await db.select().from(alertNotifications).where(conditions); return result; }
  async createAlertNotification(notification: InsertAlertNotification): Promise<AlertNotification> { const [n] = await db.insert(alertNotifications).values({ id: randomUUID(), ...notification, acknowledged: notification.acknowledged || false, createdAt: new Date(), updatedAt: new Date() }).returning(); return n; }
  async acknowledgeAlert(id: string, acknowledgedBy: string, orgId?: string): Promise<AlertNotification> { this.validateOrgId(orgId, "acknowledgeAlert"); const conditions = orgId ? and(eq(alertNotifications.id, id), eq(alertNotifications.orgId, orgId)) : eq(alertNotifications.id, id); const [updated] = await db.update(alertNotifications).set({ acknowledged: true, acknowledgedBy, acknowledgedAt: new Date(), updatedAt: new Date() }).where(conditions).returning(); if (!updated) {throw new Error(`Alert notification ${id} not found`);} return updated; }

  async addAlertComment(commentData: InsertAlertComment): Promise<AlertComment> { const [n] = await db.insert(alertComments).values({ id: randomUUID(), ...commentData, createdAt: new Date() }).returning(); return n; }
  async getAlertComments(alertId: string): Promise<AlertComment[]> { return db.select().from(alertComments).where(eq(alertComments.alertId, alertId)).orderBy(sql`${alertComments.createdAt} DESC`); }

  async createAlertSuppression(suppressionData: InsertAlertSuppression): Promise<AlertSuppression> { const [n] = await db.insert(alertSuppressions).values({ id: randomUUID(), ...suppressionData, createdAt: new Date() }).returning(); return n; }
  async getActiveSuppressions(orgId?: string): Promise<AlertSuppression[]> { const now = new Date(); if (orgId) {return db.select().from(alertSuppressions).where(and(eq(alertSuppressions.orgId, orgId), gte(alertSuppressions.suppressUntil, now)));} return db.select().from(alertSuppressions).where(gte(alertSuppressions.suppressUntil, now)); }
  async removeAlertSuppression(id: string, orgId?: string): Promise<void> { this.validateOrgId(orgId, "removeAlertSuppression"); const conditions = orgId ? and(eq(alertSuppressions.id, id), eq(alertSuppressions.orgId, orgId)) : eq(alertSuppressions.id, id); await db.delete(alertSuppressions).where(conditions); }
  async isAlertSuppressed(equipmentId: string, sensorType: string, alertType: string, orgId: string): Promise<boolean> { const suppressions = await this.getActiveSuppressions(orgId); return suppressions.some((s) => s.equipmentId === equipmentId && s.sensorType === sensorType && s.alertType === alertType); }
}
