import { lazy } from "react";

const SystemHub = lazy(() => import("@/pages/system-hub"));
const ConfigurationHub = lazy(() => import("@/pages/configuration-hub"));
const SensorsHub = lazy(() => import("@/pages/sensors-hub"));
const NotificationsHub = lazy(() => import("@/pages/notifications-hub"));
const StormGeoSettings = lazy(() => import("@/pages/stormgeo-settings"));
const SensorTemplatesPage = lazy(() => import("@/pages/sensor-templates"));
const OrganizationManagement = lazy(() => import("@/pages/organization-management"));
const SystemAdministration = lazy(() => import("@/pages/system-administration"));
const Diagnostics = lazy(() => import("@/pages/DiagnosticsDashboard"));
const ManualTelemetryUpload = lazy(() => import("@/pages/manual-telemetry-upload"));
const CopilotAdmin = lazy(() => import("@/pages/copilot-admin"));
const AgentActivity = lazy(() => import("@/pages/agent-activity"));
const Settings = lazy(() => import("@/pages/settings"));
const NotificationSettings = lazy(() => import("@/pages/notification-settings"));
const EmailTemplates = lazy(() => import("@/pages/email-templates"));
const EmailAlertsSettings = lazy(() => import("@/pages/email-alerts-settings"));
const PermissionsSettings = lazy(() => import("@/pages/permissions-settings"));
const StorageSettings = lazy(() => import("@/pages/storage-settings"));
const TransportSettings = lazy(() => import("@/pages/transport-settings"));
const AdminTenants = lazy(() => import("@/pages/admin/tenants"));
const Admin3DModels = lazy(() => import("@/pages/admin/3d-models"));
const AdminEquipmentDependencies = lazy(() => import("@/pages/admin/equipment-dependencies"));
const AdminTelemetryWarehouse = lazy(() => import("@/pages/admin/telemetry-warehouse"));

export const systemRoutes = [
  { path: "/system", component: SystemHub },
  { path: "/configuration", component: ConfigurationHub },
  { path: "/sensors", component: SensorsHub },
  { path: "/notifications", component: NotificationsHub },
  { path: "/stormgeo-settings", component: StormGeoSettings },
  { path: "/sensor-templates", component: SensorTemplatesPage },
  { path: "/organization-management", component: OrganizationManagement },
  { path: "/system-administration", component: SystemAdministration },
  { path: "/diagnostics", component: Diagnostics },
  { path: "/telemetry-upload", component: ManualTelemetryUpload },
  { path: "/copilot-admin", component: CopilotAdmin },
  { path: "/agent/activity", component: AgentActivity },
  { path: "/settings", component: Settings },
  { path: "/notification-settings", component: NotificationSettings },
  { path: "/email-templates", component: EmailTemplates },
  { path: "/email-alerts-settings", component: EmailAlertsSettings },
  { path: "/permissions-settings", component: PermissionsSettings },
  { path: "/storage-settings", component: StorageSettings },
  { path: "/transport-settings", component: TransportSettings },
  { path: "/admin/tenants", component: AdminTenants },
  { path: "/admin/3d-models", component: Admin3DModels },
  { path: "/admin/equipment-dependencies", component: AdminEquipmentDependencies },
  { path: "/admin/telemetry-warehouse", component: AdminTelemetryWarehouse },
];
