const HEADER_ALIASES: Record<string, string> = {
  "comp no": "Component No",
  "comp. no": "Component No",
  "component no": "Component No",
  "component no.": "Component No",
  "component number": "Component Number",
  "comp name": "Component Name",
  "comp. name": "Component Name",
  "component name": "Component Name",
  "job no": "Job No",
  "job no.": "Job No",
  "job number": "Job Number",
  "job name": "Job Name",
  "work order no": "Job No",
  "part no": "Part No",
  "part no.": "Part No",
  "part number": "Part Number",
  "item no": "Part No",
  "item code": "Part No",
  "part name": "Part Name",
  "item name": "Part Name",
  "item description": "Part Name",
  "r.o.b": "ROB",
  "r.o.b.": "ROB",
  rob: "ROB",
  "qty on board": "ROB",
  "remaining on board": "Remaining On Board",
  maker: "Maker",
  "maker name": "Maker",
  manufacturer: "Manufacturer",
  mfr: "Manufacturer",
  model: "Model",
  "model no": "Model No",
  "serial no": "Serial No",
  "serial number": "Serial Number",
  system: "System",
  "system name": "System Name",
  criticality: "Criticality",
  "running hours": "Running Hours",
  "running hrs": "Running Hours",
  "run hrs": "Running Hours",
  "current hours": "Current Hours",
  "total running hours": "Total Running Hours",
  status: "Status",
  active: "Active",
  location: "Location",
  description: "Description",
  "install date": "Install Date",
  "installation date": "Installation Date",
  "job type": "Job Type",
  "maintenance type": "Maintenance Type",
  "job status": "Job Status",
  priority: "Priority",
  "planned date": "Planned Date",
  "due date": "Due Date",
  "next due date": "Next Due Date",
  "done date": "Done Date",
  "completed date": "Completed Date",
  "completion date": "Completed Date",
  "created date": "Created Date",
  "estimated hours": "Estimated Hours",
  "actual hours": "Actual Hours",
  "man hours": "Man Hours",
  "done at hours": "Done At Hours",
  remarks: "Remarks",
  comments: "Comments",
  findings: "Findings",
  category: "Category",
  group: "Group",
  uom: "UOM",
  unit: "Unit",
  "min stock": "Min Stock",
  "minimum stock": "Minimum Stock",
  "max stock": "Max Stock",
  "unit price": "Unit Price",
  cost: "Cost",
  "lead time": "Lead Time",
  "lead time (days)": "Lead Time (Days)",
  bin: "Bin",
  "bin location": "Bin Location",
  "store location": "Store Location",
  supplier: "Supplier",
  "supplier code": "Supplier Code",
  "imdg class": "IMDG Class",
  "un number": "UN Number",
  hazmat: "Hazmat",
  vessel: "Vessel",
  "vessel name": "Vessel Name",
  "vessel code": "Vessel Code",
  "employee no": "Employee No",
  "seafarer id": "Seafarer ID",
  name: "Name",
  rank: "Rank",
  "certificate name": "Certificate Name",
  "certificate type": "Certificate Type",
  "certificate no": "Certificate No",
  "issuing authority": "Issuing Authority",
  "issue date": "Issue Date",
  "expiry date": "Expiry Date",
  date: "Date",
  "work hours": "Work Hours",
  "rest hours": "Rest Hours",
  violation: "Violation",
  "violation type": "Violation Type",
  responsible: "Responsible",
  "assigned to": "Assigned To",
  "power (kw)": "Power (kW)",
  "rated rpm": "Rated RPM",
  capacity: "Capacity",
  "weight (kg)": "Weight (kg)",
  "class no": "Class No",
  "drawing no": "Drawing No",
  "sub category": "Sub Category",
  "maker part no": "Maker Part No",
  "qty on hand": "Qty On Hand",
  "deck/location": "Deck/Location",
  "equipment type": "Equipment Type",
  "component type": "Component Type",
  "class criticality": "Class Criticality",
  "last maintenance date": "Last Maintenance Date",
  "last done date": "Last Done Date",
  "long description": "Long Description",
  "interval (days)": "Interval (Days)",
  "interval (hours)": "Interval (Hours)",
  frequency: "Frequency",
};

export function normalizeShipmateHeaders(headers: string[]): string[] {
  return headers.map((h) => {
    const lower = h.toLowerCase().trim();
    return HEADER_ALIASES[lower] || h.trim();
  });
}
