import { defineConfig } from "drizzle-kit";

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL, ensure the database is provisioned");
}

export default defineConfig({
  out: "./migrations",
  schema: [
    "./shared/schema.ts",
    "./shared/schema/core.ts",
    "./shared/schema/sync.ts",
    "./shared/schema/vessels.ts",
    "./shared/schema/equipment.ts",
    "./shared/schema/work-orders.ts",
    "./shared/schema/alerts.ts",
    "./shared/schema/maintenance.ts",
    "./shared/schema/telemetry.ts",
    "./shared/schema/sensors.ts",
    "./shared/schema/inventory.ts",
    "./shared/schema/crew.ts",
    "./shared/schema/compliance.ts",
    "./shared/schema/ml-analytics-core.ts",
    "./shared/schema/ml-analytics-advanced.ts",
    "./shared/schema/iot-edge.ts",
    "./shared/schema/knowledge-base.ts",
    "./shared/schema/rag.ts",
    "./shared/schema/insights.ts",
    "./shared/schema/optimizer.ts",
    "./shared/schema/permissions.ts",
    "./shared/schema/logbooks.ts",
    "./shared/schema/admin.ts",
    "./shared/schema/costs.ts",
    "./shared/schema/dtc.ts",
    "./shared/schema/scheduling-settings.ts",
    "./shared/schema/purchasing.ts",
    "./shared/schema/stormgeo.ts",
    "./shared/schema/pdm-feature-store.ts",
    "./shared/schema/vessel-diagram-registry.ts",
    "./shared/schema/agent.ts",
    "./shared/schema/digital-twin.ts",
    "./shared/schema/safety-alarms.ts",
    "./shared/schema/role-dashboards.ts",
    "./shared/schema/ml-training-pipeline.ts",
    "./shared/schema/scheduled-reports.ts",
    "./shared/schema/equipment-dependencies.ts",
    "./shared/schema/crew-tasks.ts",
    "./shared/schema/certificates.ts",
    "./shared/schema/sso.ts",
    "./shared/schema/safety-bulletins.ts",
    "./shared/schema/import-manifest.ts",
    "./shared/schema/external-data-cache.ts",
    "./shared/schema/diagnostic-runs.ts",
    "./shared/schema/ops-deployment.ts",
    "./shared/schema/feedback.ts",
  ],
  dialect: "postgresql",
  dbCredentials: {
    url: process.env.DATABASE_URL,
  },
});
