import type { ActionCode, ActionDefinition } from "./types";

export const ACTIONS: Record<ActionCode, ActionDefinition> = {
  view: {
    code: "view",
    name: "View",
    description: "View and read data",
    riskLevel: "low",
    sortOrder: 1,
  },
  create: {
    code: "create",
    name: "Create",
    description: "Create new records",
    riskLevel: "medium",
    sortOrder: 2,
  },
  edit: {
    code: "edit",
    name: "Edit",
    description: "Modify existing records",
    riskLevel: "medium",
    sortOrder: 3,
  },
  delete: {
    code: "delete",
    name: "Delete",
    description: "Remove records permanently",
    riskLevel: "high",
    sortOrder: 4,
  },
  export: {
    code: "export",
    name: "Export",
    description: "Export data to files",
    riskLevel: "medium",
    sortOrder: 5,
  },
  approve: {
    code: "approve",
    name: "Approve",
    description: "Approve submissions or requests",
    riskLevel: "high",
    sortOrder: 6,
  },
  assign: {
    code: "assign",
    name: "Assign",
    description: "Assign tasks or resources to crew",
    riskLevel: "medium",
    sortOrder: 7,
  },
  complete: {
    code: "complete",
    name: "Complete",
    description: "Mark items as completed",
    riskLevel: "medium",
    sortOrder: 8,
  },
  manage_parts: {
    code: "manage_parts",
    name: "Manage Parts",
    description: "Add or remove parts from work orders",
    riskLevel: "high",
    sortOrder: 9,
  },
  manage_config: {
    code: "manage_config",
    name: "Manage Configuration",
    description: "Change system or sensor configurations",
    riskLevel: "critical",
    sortOrder: 10,
  },
  manage: {
    code: "manage",
    name: "Manage",
    description: "Manage operational definitions and configuration",
    riskLevel: "critical",
    sortOrder: 11,
  },
  trigger: {
    code: "trigger",
    name: "Trigger",
    description: "Trigger operational alerts or alarms",
    riskLevel: "high",
    sortOrder: 12,
  },
  clear: {
    code: "clear",
    name: "Clear",
    description: "Clear active operational alerts or alarms",
    riskLevel: "high",
    sortOrder: 13,
  },
  acknowledge: {
    code: "acknowledge",
    name: "Acknowledge",
    description: "Acknowledge alerts, alarms, or required reviews",
    riskLevel: "medium",
    sortOrder: 14,
  },
  sign_off: {
    code: "sign_off",
    name: "Sign Off",
    description: "Officially sign off on logbook entries or compliance documents",
    riskLevel: "high",
    sortOrder: 15,
  },
  override: {
    code: "override",
    name: "Override",
    description: "Override system recommendations or safety checks",
    riskLevel: "critical",
    sortOrder: 16,
  },
  configure: {
    code: "configure",
    name: "Configure",
    description: "Configure feature settings and registry behavior",
    riskLevel: "high",
    sortOrder: 17,
  },
  "upload-diagram": {
    code: "upload-diagram",
    name: "Upload Diagram",
    description: "Upload or replace vessel diagram media",
    riskLevel: "high",
    sortOrder: 18,
  },
  "publish-map": {
    code: "publish-map",
    name: "Publish Map",
    description: "Publish a validated vessel section map",
    riskLevel: "critical",
    sortOrder: 19,
  },
  "rollback-diagram": {
    code: "rollback-diagram",
    name: "Rollback Diagram",
    description: "Roll back active diagram versions",
    riskLevel: "critical",
    sortOrder: 20,
  },
  "edit-section-map": {
    code: "edit-section-map",
    name: "Edit Section Map",
    description: "Edit section map geometry and labels",
    riskLevel: "high",
    sortOrder: 21,
  },
  "replace-section-thumbnail": {
    code: "replace-section-thumbnail",
    name: "Replace Section Thumbnail",
    description: "Replace section thumbnail media",
    riskLevel: "medium",
    sortOrder: 22,
  },
  "replace-equipment-thumbnail": {
    code: "replace-equipment-thumbnail",
    name: "Replace Equipment Thumbnail",
    description: "Replace equipment thumbnail media",
    riskLevel: "medium",
    sortOrder: 23,
  },
  "assign-equipment": {
    code: "assign-equipment",
    name: "Assign Equipment",
    description: "Assign equipment to vessel sections",
    riskLevel: "medium",
    sortOrder: 24,
  },
  "create-work-order": {
    code: "create-work-order",
    name: "Create Work Order",
    description: "Create work orders from Vessel Intelligence",
    riskLevel: "medium",
    sortOrder: 25,
  },
  "create-expert-case": {
    code: "create-expert-case",
    name: "Create Expert Case",
    description: "Create expert cases from Vessel Intelligence",
    riskLevel: "medium",
    sortOrder: 26,
  },
};
