import type { ResourceCategory, ResourceDefinition } from "./types";

export const RESOURCES: ResourceDefinition[] = [
  // Operations
  {
    code: "dashboard",
    name: "Dashboard",
    description: "Main dashboard with fleet overview",
    category: "operations",
    icon: "LayoutDashboard",
    actions: ["view"],
    sortOrder: 1,
  },
  {
    code: "vessels",
    name: "Vessels",
    description: "Fleet vessel management",
    category: "operations",
    icon: "Ship",
    actions: ["view", "create", "edit", "delete", "export"],
    sortOrder: 2,
  },
  {
    code: "equipment",
    name: "Equipment",
    description: "Equipment registry and details",
    category: "operations",
    icon: "Wrench",
    actions: ["view", "create", "edit", "delete", "manage_config"],
    sortOrder: 3,
  },
  {
    code: "sensors",
    name: "Sensors",
    description: "Sensor configuration and monitoring",
    category: "operations",
    icon: "Activity",
    actions: ["view", "create", "edit", "delete", "manage_config"],
    sortOrder: 4,
  },
  {
    code: "hub:vessel-intelligence",
    name: "Vessel Intelligence Hub",
    description: "Access to the Vessel Intelligence navigation hub",
    category: "operations",
    icon: "Ship",
    actions: ["view"],
    sortOrder: 5,
  },
  {
    code: "vessel-intelligence",
    name: "Vessel Intelligence",
    description: "Versioned vessel diagram registry, section maps, and thumbnail administration",
    category: "operations",
    icon: "Layers",
    actions: [
      "view",
      "configure",
      "upload-diagram",
      "publish-map",
      "rollback-diagram",
      "edit-section-map",
      "replace-section-thumbnail",
      "replace-equipment-thumbnail",
      "assign-equipment",
      "create-work-order",
      "create-expert-case",
      "acknowledge",
      "export",
    ],
    sortOrder: 6,
  },

  // Maintenance
  {
    code: "work_orders",
    name: "Work Orders",
    description: "Maintenance work orders",
    category: "maintenance",
    icon: "ClipboardList",
    actions: ["view", "create", "edit", "delete", "assign", "complete", "manage_parts"],
    sortOrder: 10,
  },
  {
    code: "maintenance_schedules",
    name: "Maintenance Schedules",
    description: "Planned maintenance scheduling",
    category: "maintenance",
    icon: "Calendar",
    actions: ["view", "create", "edit", "delete", "approve"],
    sortOrder: 11,
  },
  {
    code: "maintenance_templates",
    name: "Maintenance Templates",
    description: "Reusable maintenance templates",
    category: "maintenance",
    icon: "FileCode",
    actions: ["view", "create", "edit", "delete"],
    sortOrder: 12,
  },
  {
    code: "alerts",
    name: "Alerts",
    description: "Equipment alerts and notifications",
    category: "maintenance",
    icon: "Bell",
    actions: ["view", "edit", "delete", "manage_config"],
    sortOrder: 13,
  },

  // Crew
  {
    code: "crew_members",
    name: "Crew Members",
    description: "Crew roster and profiles",
    category: "crew",
    icon: "Users",
    actions: ["view", "create", "edit", "delete", "export"],
    sortOrder: 20,
  },
  {
    code: "crew_schedules",
    name: "Crew Schedules",
    description: "Work schedules and assignments",
    category: "crew",
    icon: "CalendarDays",
    actions: ["view", "create", "edit", "delete", "assign"],
    sortOrder: 21,
  },
  {
    code: "rest_hours",
    name: "Rest Hours",
    description: "STCW rest hour tracking",
    category: "crew",
    icon: "Clock",
    actions: ["view", "create", "edit", "delete", "approve", "sign_off"],
    sortOrder: 22,
  },
  {
    code: "certifications",
    name: "Certifications",
    description: "Crew certifications and training",
    category: "crew",
    icon: "Award",
    actions: ["view", "create", "edit", "delete"],
    sortOrder: 23,
  },
  {
    code: "safety_alarms",
    name: "Safety Alarms",
    description: "Operational safety alarm viewing and response",
    category: "crew",
    icon: "ShieldAlert",
    actions: ["view", "trigger", "clear", "acknowledge", "export"],
    sortOrder: 24,
  },
  {
    code: "safety_alarm_types",
    name: "Safety Alarm Types",
    description: "Configure available safety alarm definitions",
    category: "crew",
    icon: "Bell",
    actions: ["view", "manage"],
    sortOrder: 25,
  },
  {
    code: "leave_requests",
    name: "Leave Requests",
    description: "Crew leave management",
    category: "crew",
    icon: "Plane",
    actions: ["view", "create", "edit", "delete", "approve"],
    sortOrder: 26,
  },

  // Inventory
  {
    code: "inventory",
    name: "Inventory",
    description: "Parts and supplies inventory",
    category: "inventory",
    icon: "Package",
    actions: ["view", "create", "edit", "delete", "export"],
    sortOrder: 30,
  },
  {
    code: "inventory_movements",
    name: "Inventory Movements",
    description: "Stock movements and adjustments",
    category: "inventory",
    icon: "ArrowLeftRight",
    actions: ["view", "create", "edit", "delete"],
    sortOrder: 31,
  },
  {
    code: "purchase_requests",
    name: "Purchase Requests",
    description: "Procurement and purchasing",
    category: "inventory",
    icon: "ShoppingCart",
    actions: ["view", "create", "edit", "delete", "approve"],
    sortOrder: 32,
  },
  {
    code: "suppliers",
    name: "Suppliers",
    description: "Supplier management",
    category: "inventory",
    icon: "Building2",
    actions: ["view", "create", "edit", "delete"],
    sortOrder: 33,
  },
  {
    code: "service_orders",
    name: "Service Orders",
    description: "External service provider orders",
    category: "inventory",
    icon: "FileText",
    actions: ["view", "create", "edit", "delete", "approve"],
    sortOrder: 34,
  },
  {
    code: "service_requests",
    name: "Service Requests",
    description: "Service request workflow for procurement review",
    category: "inventory",
    icon: "ClipboardList",
    actions: ["view", "create", "edit", "delete", "approve"],
    sortOrder: 35,
  },

  // Compliance
  {
    code: "deck_logbook",
    name: "Deck Logbook",
    description: "Bridge deck operations log",
    category: "compliance",
    icon: "BookOpen",
    actions: ["view", "create", "edit", "delete", "sign_off", "export"],
    sortOrder: 40,
  },
  {
    code: "engine_logbook",
    name: "Engine Logbook",
    description: "Engine room operations log",
    category: "compliance",
    icon: "Cog",
    actions: ["view", "create", "edit", "delete", "sign_off", "export"],
    sortOrder: 41,
  },
  {
    code: "compliance_findings",
    name: "Compliance Findings",
    description: "Audit findings and NCRs",
    category: "compliance",
    icon: "ShieldAlert",
    actions: ["view", "create", "edit", "delete", "approve"],
    sortOrder: 42,
  },
  {
    code: "compliance_reports",
    name: "Compliance Reports",
    description: "ISM and regulatory reports",
    category: "compliance",
    icon: "FileCheck",
    actions: ["view", "create", "export"],
    sortOrder: 43,
  },

  // Analytics
  {
    code: "analytics_dashboard",
    name: "Analytics Dashboard",
    description: "Performance analytics and insights",
    category: "analytics",
    icon: "BarChart3",
    actions: ["view", "export"],
    sortOrder: 50,
  },
  {
    code: "predictive_maintenance",
    name: "Predictive Maintenance",
    description: "ML-based failure predictions",
    category: "analytics",
    icon: "BrainCircuit",
    actions: ["view", "manage_config", "override"],
    sortOrder: 51,
  },
  {
    code: "condition_monitoring",
    name: "Condition Monitoring",
    description: "Oil analysis and wear tracking",
    category: "analytics",
    icon: "Droplets",
    actions: ["view", "create", "edit", "delete"],
    sortOrder: 52,
  },
  {
    code: "ai_reports",
    name: "AI Reports",
    description: "AI-generated insights and reports",
    category: "analytics",
    icon: "Sparkles",
    actions: ["view", "create", "export"],
    sortOrder: 53,
  },
  {
    code: "cost_savings",
    name: "Cost Savings",
    description: "ROI and cost savings tracking",
    category: "analytics",
    icon: "PiggyBank",
    actions: ["view", "export"],
    sortOrder: 54,
  },

  // Settings
  {
    code: "organization_settings",
    name: "Organization Settings",
    description: "Organization configuration",
    category: "settings",
    icon: "Building",
    actions: ["view", "edit"],
    sortOrder: 60,
  },
  {
    code: "user_management",
    name: "User Management",
    description: "User accounts and roles",
    category: "settings",
    icon: "UserCog",
    actions: ["view", "create", "edit", "delete"],
    sortOrder: 61,
  },
  {
    code: "permission_management",
    name: "Permission Management",
    description: "Role and permission configuration",
    category: "settings",
    icon: "Shield",
    actions: ["view", "create", "edit", "delete"],
    sortOrder: 62,
  },
  {
    code: "system_settings",
    name: "System Settings",
    description: "System-wide configuration",
    category: "settings",
    icon: "Settings",
    actions: ["view", "edit", "manage_config"],
    sortOrder: 63,
  },
  {
    code: "integrations",
    name: "Integrations",
    description: "Third-party integrations",
    category: "settings",
    icon: "Plug",
    actions: ["view", "create", "edit", "delete", "manage_config"],
    sortOrder: 64,
  },
  {
    code: "audit_log",
    name: "Audit Log",
    description: "System audit trail",
    category: "settings",
    icon: "FileSearch",
    actions: ["view", "export"],
    sortOrder: 65,
  },
];

export const RESOURCE_CATEGORIES: { code: ResourceCategory; name: string; icon: string }[] = [
  { code: "operations", name: "Operations", icon: "Ship" },
  { code: "maintenance", name: "Maintenance", icon: "Wrench" },
  { code: "crew", name: "Crew", icon: "Users" },
  { code: "inventory", name: "Inventory", icon: "Package" },
  { code: "compliance", name: "Compliance", icon: "Shield" },
  { code: "analytics", name: "Analytics", icon: "BarChart3" },
  { code: "settings", name: "Settings", icon: "Settings" },
];
