import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { AlertTriangle, CheckCircle2, Clock, AlertCircle, Info, Wrench, FileText, ArrowUpCircle } from "lucide-react";
import { useActionableInsightsData } from "@/features/insights";
import { formatDate } from "@/lib/formatters";

const SeverityBadgeVariants: Record<string, "destructive" | "default" | "secondary" | "outline"> = { critical: "destructive", high: "default", medium: "secondary", low: "outline" };
const SeverityBadgeColors: Record<string, string> = { critical: "bg-red-500 dark:bg-red-600", high: "bg-orange-500 dark:bg-orange-600", medium: "bg-yellow-500 dark:bg-yellow-600", low: "bg-blue-500 dark:bg-blue-600" };
const TypeIcons: Record<string, typeof AlertTriangle> = { FAILURE_PREDICTED: AlertTriangle, MAINTENANCE_DUE: Wrench, CONDITION_DETERIORATING: ArrowUpCircle, SENSOR_ANOMALY: AlertCircle, OPTIMIZATION_OPPORTUNITY: Info, COMPLIANCE_RISK: FileText };

const SeverityBadge = ({ severity }: { severity: string }) => (<Badge variant={SeverityBadgeVariants[severity]} className={SeverityBadgeColors[severity]}>{severity.toUpperCase()}</Badge>);
const TypeIcon = ({ type }: { type: string }) => { const Icon = TypeIcons[type] || Info; return <Icon className="h-5 w-5" />; };

export default function ActionableInsightsPage() {
  const { stats, insights, insightsLoading, selectedSeverity, setSelectedSeverity, showResolved, toggleShowResolved, selectedInsight, detailsOpen, setDetailsOpen, resolveDialogOpen, setResolveDialogOpen, resolutionNotes, setResolutionNotes, handleAcknowledge, handleResolve, handleSelectInsight, acknowledgeMutation, resolveMutation } = useActionableInsightsData();

  return (
    <div className="min-h-screen" data-testid="actionable-insights-page">
      <div className="container mx-auto p-6 space-y-6 bg-background dark:bg-gray-950">

      {stats && (<div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-7 gap-4">{[{ label: "Total", value: stats.total, testId: "stat-total" }, { label: "Critical", value: stats.critical, color: "text-red-500 dark:text-red-400", testId: "stat-critical" }, { label: "High", value: stats.high, color: "text-orange-500 dark:text-orange-400", testId: "stat-high" }, { label: "Medium", value: stats.medium, color: "text-yellow-500 dark:text-yellow-400", testId: "stat-medium" }, { label: "Low", value: stats.low, color: "text-blue-500 dark:text-blue-400", testId: "stat-low" }, { label: "Unresolved", value: stats.unresolved, testId: "stat-unresolved" }, { label: "Resolved", value: stats.resolved, color: "text-green-500 dark:text-green-400", testId: "stat-resolved" }].map((s) => (<Card key={s.testId} className="bg-card dark:bg-gray-900" data-testid={s.testId}><CardHeader className="pb-2"><CardTitle className={`text-sm font-medium ${s.color || "text-muted-foreground dark:text-gray-400"}`}>{s.label}</CardTitle></CardHeader><CardContent><div className={`text-2xl font-bold ${s.color || "text-foreground dark:text-white"}`}>{s.value}</div></CardContent></Card>))}</div>)}

      <Card className="bg-card dark:bg-gray-900"><CardHeader><div className="flex items-center justify-between"><CardTitle className="text-foreground dark:text-white">Insights</CardTitle><Button variant={showResolved ? "default" : "outline"} size="sm" onClick={toggleShowResolved} className="dark:bg-gray-800 dark:text-white dark:hover:bg-gray-700" data-testid="button-toggle-resolved">{showResolved ? "Hide Resolved" : "Show Resolved"}</Button></div></CardHeader><CardContent>
        <Tabs value={selectedSeverity || "all"} onValueChange={(v) => setSelectedSeverity(v === "all" ? null : v)}><TabsList className="dark:bg-gray-800">{["all", "critical", "high", "medium", "low"].map((tab) => <TabsTrigger key={tab} value={tab} data-testid={`filter-${tab}`}>{tab.charAt(0).toUpperCase() + tab.slice(1)}</TabsTrigger>)}</TabsList></Tabs>
        <div className="mt-4 space-y-3">
          {insightsLoading && <div className="text-center py-8 text-muted-foreground dark:text-gray-400" data-testid="loading-state">Loading insights...</div>}
          {!insightsLoading && insights.length === 0 && <div className="text-center py-8 text-muted-foreground dark:text-gray-400" data-testid="empty-state">No insights found</div>}
          {insights.map((insight) => (<Card key={insight.id} className="cursor-pointer hover:bg-accent dark:bg-gray-800 dark:hover:bg-gray-700 transition-colors" onClick={() => handleSelectInsight(insight)} data-testid={`insight-card-${insight.id}`}><CardContent className="p-4"><div className="flex items-start justify-between gap-4"><div className="flex items-start gap-3 flex-1"><div className="mt-1"><TypeIcon type={insight.type} /></div><div className="flex-1 space-y-1"><div className="flex items-center gap-2 flex-wrap"><h3 className="font-semibold text-foreground dark:text-white" data-testid={`insight-title-${insight.id}`}>{insight.title}</h3><SeverityBadge severity={insight.severity} />{insight.acknowledged && <Badge variant="outline" className="dark:border-gray-600 dark:text-gray-300"><CheckCircle2 className="h-3 w-3 mr-1" />Acknowledged</Badge>}{insight.resolved && <Badge variant="outline" className="bg-green-50 dark:bg-green-900/20 text-green-700 dark:text-green-300 border-green-300 dark:border-green-700"><CheckCircle2 className="h-3 w-3 mr-1" />Resolved</Badge>}</div><p className="text-sm text-muted-foreground dark:text-gray-400">{insight.message}</p>{insight.equipment && <p className="text-xs text-muted-foreground dark:text-gray-500">Equipment: {insight.equipment.name} ({insight.equipment.type})</p>}<p className="text-xs text-muted-foreground dark:text-gray-500"><Clock className="h-3 w-3 inline mr-1" />{formatDate(insight.createdAt)}</p></div></div></div></CardContent></Card>))}
        </div>
      </CardContent></Card>

      <Dialog open={detailsOpen} onOpenChange={setDetailsOpen}><DialogContent className="max-w-3xl bg-background dark:bg-gray-900 text-foreground dark:text-white"><DialogHeader><DialogTitle className="flex items-center gap-2">{selectedInsight && <TypeIcon type={selectedInsight.type} />}{selectedInsight?.title}</DialogTitle><DialogDescription className="dark:text-gray-400">{selectedInsight?.message}</DialogDescription></DialogHeader>{selectedInsight && <div className="space-y-4 max-h-[60vh] overflow-y-auto"><div><Label className="dark:text-gray-300">Severity</Label><div className="mt-1"><SeverityBadge severity={selectedInsight.severity} /></div></div>{selectedInsight.equipment && <div><Label className="dark:text-gray-300">Equipment</Label><p className="text-sm mt-1 dark:text-gray-400">{selectedInsight.equipment.name} ({selectedInsight.equipment.type})</p></div>}{selectedInsight.recommendedAction && <div><Label className="dark:text-gray-300">Recommended Action</Label><p className="text-sm mt-1 dark:text-gray-400">{selectedInsight.recommendedAction}</p></div>}{selectedInsight.supportingSignals && <div><Label className="dark:text-gray-300">Supporting Signals</Label><pre className="text-xs mt-1 bg-muted dark:bg-gray-800 p-3 rounded overflow-x-auto dark:text-gray-300">{JSON.stringify(selectedInsight.supportingSignals, null, 2)}</pre></div>}{selectedInsight.relatedProcedures && selectedInsight.relatedProcedures.length > 0 && <div><Label className="dark:text-gray-300">Related Procedures</Label><ul className="list-disc list-inside text-sm mt-1 space-y-1 dark:text-gray-400">{selectedInsight.relatedProcedures.map((proc) => <li key={proc}>{proc}</li>)}</ul></div>}{selectedInsight.resolutionNotes && <div><Label className="dark:text-gray-300">Resolution Notes</Label><p className="text-sm mt-1 dark:text-gray-400">{selectedInsight.resolutionNotes}</p></div>}</div>}<DialogFooter>{selectedInsight && !selectedInsight.acknowledged && <Button variant="outline" onClick={() => handleAcknowledge(selectedInsight.id)} disabled={acknowledgeMutation.isPending} className="dark:bg-gray-800 dark:text-white dark:hover:bg-gray-700" data-testid="button-acknowledge">Acknowledge</Button>}{selectedInsight && !selectedInsight.resolved && <Button onClick={() => setResolveDialogOpen(true)} className="dark:bg-blue-600 dark:hover:bg-blue-700" data-testid="button-resolve">Mark as Resolved</Button>}</DialogFooter></DialogContent></Dialog>

      <Dialog open={resolveDialogOpen} onOpenChange={setResolveDialogOpen}><DialogContent className="bg-background dark:bg-gray-900 text-foreground dark:text-white"><DialogHeader><DialogTitle>Resolve Insight</DialogTitle><DialogDescription className="dark:text-gray-400">Add notes about how this insight was resolved.</DialogDescription></DialogHeader><div className="space-y-4"><div><Label htmlFor="resolution-notes" className="dark:text-gray-300">Resolution Notes</Label><Textarea id="resolution-notes" value={resolutionNotes} onChange={(e) => setResolutionNotes(e.target.value)} placeholder="Describe the actions taken to resolve this insight..." className="mt-1 dark:bg-gray-800 dark:text-white dark:border-gray-700" rows={4} data-testid="input-resolution-notes" /></div></div><DialogFooter><Button variant="outline" onClick={() => setResolveDialogOpen(false)} className="dark:bg-gray-800 dark:text-white dark:hover:bg-gray-700">Cancel</Button><Button onClick={handleResolve} disabled={resolveMutation.isPending} className="dark:bg-blue-600 dark:hover:bg-blue-700" data-testid="button-submit-resolve">{resolveMutation.isPending ? "Resolving..." : "Resolve"}</Button></DialogFooter></DialogContent></Dialog>
      </div>
    </div>
  );
}
