import { format } from "date-fns";
import { Zap } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import type { MaintenanceSchedulesPageModel } from "./maintenance-schedules-types";

interface MaintenanceScheduleDialogsProps {
  m: MaintenanceSchedulesPageModel;
}

export function MaintenanceScheduleDialogs({ m }: MaintenanceScheduleDialogsProps) {
  return (
    <>
      <Dialog open={m.viewModalOpen} onOpenChange={m.setViewModalOpen}>
        <DialogContent className="max-w-2xl" data-testid="schedule-detail-modal">
          <DialogHeader>
            <DialogTitle>Maintenance Schedule Details</DialogTitle>
            <DialogDescription>
              {m.selectedSchedule && m.getEquipmentName(m.selectedSchedule.equipmentId)}
            </DialogDescription>
          </DialogHeader>
          {m.selectedSchedule && (
            <div className="space-y-6">
              <div className="grid grid-cols-2 gap-6">
                <div>
                  <Label className="text-sm font-medium text-muted-foreground">Equipment</Label>
                  <p className="text-base font-medium mt-1">
                    {m.getEquipmentName(m.selectedSchedule.equipmentId)}
                  </p>
                </div>
                <div>
                  <Label className="text-sm font-medium text-muted-foreground">Type</Label>
                  <p className="text-base capitalize mt-1">{m.selectedSchedule.maintenanceType}</p>
                </div>
                <div>
                  <Label className="text-sm font-medium text-muted-foreground">
                    Scheduled Date
                  </Label>
                  <p className="text-base font-medium mt-1">
                    {format(new Date(m.selectedSchedule.scheduledDate), "MMM d, yyyy h:mm a")}
                  </p>
                </div>
                <div>
                  <Label className="text-sm font-medium text-muted-foreground">Status</Label>
                  <div className="mt-1">
                    <Badge className={m.getStatusBadge(m.selectedSchedule.status).className}>
                      {m.getStatusBadge(m.selectedSchedule.status).label}
                    </Badge>
                  </div>
                </div>
                <div>
                  <Label className="text-sm font-medium text-muted-foreground">Priority</Label>
                  <div className="mt-1">
                    <Badge className={m.getPriorityBadge(m.selectedSchedule.priority).className}>
                      {m.getPriorityBadge(m.selectedSchedule.priority).label}
                    </Badge>
                  </div>
                </div>
                {m.selectedSchedule.assignedTo && (
                  <div>
                    <Label className="text-sm font-medium text-muted-foreground">Assigned To</Label>
                    <p className="text-base mt-1">{m.selectedSchedule.assignedTo}</p>
                  </div>
                )}
              </div>
              {m.selectedSchedule.description && (
                <div>
                  <Label className="text-sm font-medium text-muted-foreground">Description</Label>
                  <p className="text-base mt-2 p-3 bg-muted/50 rounded-lg">
                    {m.selectedSchedule.description}
                  </p>
                </div>
              )}
              {m.selectedSchedule.autoGenerated && (
                <div className="flex items-center gap-2 p-3 bg-blue-500/10 rounded-lg border border-blue-500/30">
                  <Zap className="h-4 w-4 text-blue-600 dark:text-blue-400" />
                  <span className="text-sm text-blue-700 dark:text-blue-300">
                    Automatically scheduled based on predictive analytics
                  </span>
                </div>
              )}
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => m.setViewModalOpen(false)}>
              Close
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={m.createModalOpen} onOpenChange={m.setCreateModalOpen}>
        <DialogContent className="max-w-2xl" data-testid="create-schedule-modal">
          <DialogHeader>
            <DialogTitle>Schedule New Maintenance</DialogTitle>
            <DialogDescription>Create a new maintenance schedule for equipment</DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <Label htmlFor="create-equipment">Equipment *</Label>
              <Select
                value={m.createForm.equipmentId || ""}
                onValueChange={(value) =>
                  m.setCreateForm((prev) => ({ ...prev, equipmentId: value }))
                }
              >
                <SelectTrigger data-testid="select-create-equipment">
                  <SelectValue placeholder="Select equipment" />
                </SelectTrigger>
                <SelectContent>
                  {m.equipment?.map((eq) => (
                    <SelectItem key={eq.id} value={eq.id}>
                      {eq.name || eq.id}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label htmlFor="create-date">Scheduled Date & Time *</Label>
                <Input
                  id="create-date"
                  type="datetime-local"
                  value={
                    m.createForm.scheduledDate
                      ? typeof m.createForm.scheduledDate === "string"
                        ? m.createForm.scheduledDate
                        : new Date(m.createForm.scheduledDate).toISOString().slice(0, 16)
                      : ""
                  }
                  onChange={(e) =>
                    m.setCreateForm((prev) => ({ ...prev, scheduledDate: e.target.value }))
                  }
                  data-testid="input-create-schedule-date"
                />
              </div>
              <div>
                <Label htmlFor="create-type">Maintenance Type *</Label>
                <Select
                  value={m.createForm.maintenanceType || "preventive"}
                  onValueChange={(value) =>
                    m.setCreateForm((prev) => ({ ...prev, maintenanceType: value }))
                  }
                >
                  <SelectTrigger data-testid="select-create-type">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="preventive">Preventive</SelectItem>
                    <SelectItem value="corrective">Corrective</SelectItem>
                    <SelectItem value="predictive">Predictive</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label htmlFor="create-priority">Priority *</Label>
                <Select
                  value={m.createForm.priority?.toString() || "2"}
                  onValueChange={(value) =>
                    m.setCreateForm((prev) => ({ ...prev, priority: Number.parseInt(value) }))
                  }
                >
                  <SelectTrigger data-testid="select-create-priority">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="1">High Priority</SelectItem>
                    <SelectItem value="2">Medium Priority</SelectItem>
                    <SelectItem value="3">Low Priority</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label htmlFor="create-assigned">Assigned To</Label>
                <Input
                  id="create-assigned"
                  placeholder="Technician name..."
                  value={m.createForm.assignedTo || ""}
                  onChange={(e) =>
                    m.setCreateForm((prev) => ({ ...prev, assignedTo: e.target.value }))
                  }
                  data-testid="input-create-assigned"
                />
              </div>
            </div>
            <div>
              <Label htmlFor="create-description">Description</Label>
              <Textarea
                id="create-description"
                placeholder="Details about this maintenance..."
                value={m.createForm.description || ""}
                onChange={(e) =>
                  m.setCreateForm((prev) => ({ ...prev, description: e.target.value }))
                }
                rows={3}
                data-testid="textarea-create-description"
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => m.setCreateModalOpen(false)}>
              Cancel
            </Button>
            <Button
              onClick={m.handleCreateSubmit}
              disabled={m.createMutation.isPending}
              data-testid="button-submit-create-schedule"
            >
              {m.createMutation.isPending ? "Creating..." : "Create Schedule"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={m.editModalOpen} onOpenChange={m.setEditModalOpen}>
        <DialogContent className="max-w-2xl" data-testid="edit-schedule-modal">
          <DialogHeader>
            <DialogTitle>Edit Maintenance Schedule</DialogTitle>
            <DialogDescription>
              Update schedule for{" "}
              {m.selectedSchedule && m.getEquipmentName(m.selectedSchedule.equipmentId)}
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <Label htmlFor="edit-equipment">Equipment *</Label>
              <Select
                value={m.editForm.equipmentId || ""}
                onValueChange={(value) =>
                  m.setEditForm((prev) => ({ ...prev, equipmentId: value }))
                }
              >
                <SelectTrigger data-testid="select-edit-equipment">
                  <SelectValue placeholder="Select equipment" />
                </SelectTrigger>
                <SelectContent>
                  {m.equipment?.map((eq) => (
                    <SelectItem key={eq.id} value={eq.id}>
                      {eq.name || eq.id}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label htmlFor="edit-date">Scheduled Date & Time *</Label>
                <Input
                  id="edit-date"
                  type="datetime-local"
                  value={
                    m.editForm.scheduledDate
                      ? typeof m.editForm.scheduledDate === "string"
                        ? m.editForm.scheduledDate
                        : new Date(m.editForm.scheduledDate).toISOString().slice(0, 16)
                      : ""
                  }
                  onChange={(e) =>
                    m.setEditForm((prev) => ({ ...prev, scheduledDate: new Date(e.target.value) }))
                  }
                  data-testid="input-edit-schedule-date"
                />
              </div>
              <div>
                <Label htmlFor="edit-type">Maintenance Type *</Label>
                <Select
                  value={m.editForm.maintenanceType || "preventive"}
                  onValueChange={(value) =>
                    m.setEditForm((prev) => ({ ...prev, maintenanceType: value }))
                  }
                >
                  <SelectTrigger data-testid="select-edit-type">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="preventive">Preventive</SelectItem>
                    <SelectItem value="corrective">Corrective</SelectItem>
                    <SelectItem value="predictive">Predictive</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label htmlFor="edit-priority">Priority *</Label>
                <Select
                  value={m.editForm.priority?.toString() || "2"}
                  onValueChange={(value) =>
                    m.setEditForm((prev) => ({ ...prev, priority: Number.parseInt(value) }))
                  }
                >
                  <SelectTrigger data-testid="select-edit-priority">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="1">High Priority</SelectItem>
                    <SelectItem value="2">Medium Priority</SelectItem>
                    <SelectItem value="3">Low Priority</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label htmlFor="edit-status">Status *</Label>
                <Select
                  value={m.editForm.status || "scheduled"}
                  onValueChange={(value) => m.setEditForm((prev) => ({ ...prev, status: value }))}
                >
                  <SelectTrigger data-testid="select-edit-status">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="scheduled">Scheduled</SelectItem>
                    <SelectItem value="in_progress">In Progress</SelectItem>
                    <SelectItem value="completed">Completed</SelectItem>
                    <SelectItem value="cancelled">Cancelled</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div>
              <Label htmlFor="edit-assigned">Assigned To</Label>
              <Input
                id="edit-assigned"
                placeholder="Technician name..."
                value={m.editForm.assignedTo || ""}
                onChange={(e) => m.setEditForm((prev) => ({ ...prev, assignedTo: e.target.value }))}
                data-testid="input-edit-assigned"
              />
            </div>
            <div>
              <Label htmlFor="edit-description">Description</Label>
              <Textarea
                id="edit-description"
                placeholder="Details about this maintenance..."
                value={m.editForm.description || ""}
                onChange={(e) =>
                  m.setEditForm((prev) => ({ ...prev, description: e.target.value }))
                }
                rows={3}
                data-testid="textarea-edit-description"
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => m.setEditModalOpen(false)}>
              Cancel
            </Button>
            <Button
              onClick={m.handleEditSubmit}
              disabled={m.updateMutation.isPending}
              data-testid="button-submit-edit-schedule"
            >
              {m.updateMutation.isPending ? "Updating..." : "Update Schedule"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
