import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription } from "@/components/ui/alert";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import { AlertTriangle, Info, Loader2, Trash2 } from "lucide-react";
import type { MLTrainingData } from "./ml-training-types";

interface ResetDataTabProps {
  training: MLTrainingData;
  ackResetKeepModels: boolean;
  setAckResetKeepModels: (value: boolean) => void;
  ackResetAll: boolean;
  setAckResetAll: (value: boolean) => void;
}

export function ResetDataTab({
  training: t,
  ackResetKeepModels,
  setAckResetKeepModels,
  ackResetAll,
  setAckResetAll,
}: ResetDataTabProps) {
  return (
    <>
      <Alert variant="destructive" className="border-2">
        <AlertTriangle className="h-5 w-5" />
        <AlertDescription className="text-lg font-semibold">
          ⚠️ DESTRUCTIVE OPERATION - ADMIN ONLY
        </AlertDescription>
      </Alert>
      <Card className="border-destructive border-2">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-destructive">
            <Trash2 className="h-5 w-5" />
            Reset ML Training Data
          </CardTitle>
          <CardDescription>
            Permanently delete synthetic telemetry data and optionally trained models to start fresh
            with real equipment data
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <Alert className="bg-amber-50 dark:bg-amber-950 border-amber-300 dark:border-amber-700">
            <Info className="h-4 w-4 text-amber-600 dark:text-amber-400" />
            <AlertDescription className="text-amber-900 dark:text-amber-100">
              <strong>When to use this:</strong> This reset function is designed for development and
              testing. Use it to clear synthetic/test data before deploying to production with real
              equipment telemetry.
            </AlertDescription>
          </Alert>
          <div className="space-y-4 p-4 bg-muted rounded-lg">
            <h3 className="font-semibold text-destructive">What will be deleted:</h3>
            <ul className="space-y-2 text-sm">
              <li className="flex items-start gap-2">
                <span className="text-destructive">•</span>
                <span>
                  <strong>All telemetry records</strong> for your organization (
                  {t.mlModels.length > 0 ? "7,369 synthetic records" : "all current data"})
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-destructive">•</span>
                <span>
                  <strong>All failure predictions</strong> generated by ML models
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-destructive">•</span>
                <span>
                  <strong>All anomaly detections</strong> from monitoring systems
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-destructive">•</span>
                <span>
                  <strong>Optionally:</strong> All trained ML models (LSTM, Random Forest, XGBoost)
                </span>
              </li>
            </ul>
          </div>
          <Alert className="bg-blue-50 dark:bg-blue-950 border-blue-200 dark:border-blue-800">
            <Info className="h-4 w-4 text-blue-600 dark:text-blue-400" />
            <AlertDescription className="text-blue-900 dark:text-blue-100">
              <strong>What is preserved:</strong> Equipment records, sensor configurations, alert
              settings, and maintenance schedules remain intact.
            </AlertDescription>
          </Alert>
          <div className="pt-4 space-y-3">
            <AlertDialog onOpenChange={(open) => !open && setAckResetKeepModels(false)}>
              <AlertDialogTrigger asChild>
                <Button
                  variant="destructive"
                  size="lg"
                  className="w-full"
                  disabled={t.resetMLData.isPending}
                  data-testid="button-reset-ml-data-keep-models"
                >
                  {t.resetMLData.isPending ? (
                    <>
                      <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                      Deleting...
                    </>
                  ) : (
                    <>
                      <Trash2 className="mr-2 h-5 w-5" />
                      Reset Training Data (Keep Models)
                    </>
                  )}
                </Button>
              </AlertDialogTrigger>
              <AlertDialogContent>
                <AlertDialogHeader>
                  <AlertDialogTitle className="flex items-center gap-2 text-destructive">
                    <AlertTriangle className="h-5 w-5" />
                    Confirm ML Data Reset
                  </AlertDialogTitle>
                  <AlertDialogDescription className="space-y-3 pt-2">
                    <p className="font-semibold">
                      This will permanently delete all telemetry, predictions, and anomaly data.
                    </p>
                    <p>Trained ML models will be preserved.</p>
                    <p className="text-destructive font-semibold">This action cannot be undone.</p>
                  </AlertDialogDescription>
                </AlertDialogHeader>
                <div className="flex items-start gap-2">
                  <Checkbox
                    id="ack-reset-keep-models"
                    checked={ackResetKeepModels}
                    onCheckedChange={(checked) => setAckResetKeepModels(checked === true)}
                    data-testid="checkbox-ack-reset-keep-models"
                  />
                  <Label htmlFor="ack-reset-keep-models" className="text-sm font-normal">
                    I understand this permanently deletes telemetry, predictions, and anomalies
                  </Label>
                </div>
                <AlertDialogFooter>
                  <AlertDialogCancel data-testid="button-cancel-reset">Cancel</AlertDialogCancel>
                  <AlertDialogAction
                    disabled={!ackResetKeepModels}
                    onClick={() => t.resetMLData.mutate({ deleteModels: false })}
                    className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
                    data-testid="button-confirm-reset-keep-models"
                  >
                    Yes, Delete Training Data
                  </AlertDialogAction>
                </AlertDialogFooter>
              </AlertDialogContent>
            </AlertDialog>
            <AlertDialog onOpenChange={(open) => !open && setAckResetAll(false)}>
              <AlertDialogTrigger asChild>
                <Button
                  variant="outline"
                  size="lg"
                  className="w-full border-destructive text-destructive hover:bg-destructive hover:text-destructive-foreground"
                  disabled={t.resetMLData.isPending}
                  data-testid="button-reset-ml-data-delete-models"
                >
                  {t.resetMLData.isPending ? (
                    <>
                      <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                      Deleting...
                    </>
                  ) : (
                    <>
                      <Trash2 className="mr-2 h-5 w-5" />
                      Reset Everything (Including Models)
                    </>
                  )}
                </Button>
              </AlertDialogTrigger>
              <AlertDialogContent>
                <AlertDialogHeader>
                  <AlertDialogTitle className="flex items-center gap-2 text-destructive">
                    <AlertTriangle className="h-5 w-5" />
                    Confirm Complete Reset
                  </AlertDialogTitle>
                  <AlertDialogDescription className="space-y-3 pt-2">
                    <p className="font-semibold text-destructive">
                      This will permanently delete ALL ML data including trained models.
                    </p>
                    <p>You will need to retrain all models from scratch. This includes:</p>
                    <ul className="list-disc list-inside space-y-1 text-sm">
                      <li>LSTM neural network model</li>
                      <li>Random Forest classifier</li>
                      <li>XGBoost model</li>
                      <li>All telemetry and prediction data</li>
                    </ul>
                    <p className="text-destructive font-bold">
                      This action cannot be undone. Are you absolutely sure?
                    </p>
                  </AlertDialogDescription>
                </AlertDialogHeader>
                <div className="flex items-start gap-2">
                  <Checkbox
                    id="ack-reset-all"
                    checked={ackResetAll}
                    onCheckedChange={(checked) => setAckResetAll(checked === true)}
                    data-testid="checkbox-ack-reset-all"
                  />
                  <Label htmlFor="ack-reset-all" className="text-sm font-normal">
                    I understand this permanently deletes telemetry, predictions, anomalies, and all
                    trained models
                  </Label>
                </div>
                <AlertDialogFooter>
                  <AlertDialogCancel data-testid="button-cancel-reset-all">
                    Cancel
                  </AlertDialogCancel>
                  <AlertDialogAction
                    disabled={!ackResetAll}
                    onClick={() => t.resetMLData.mutate({ deleteModels: true })}
                    className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
                    data-testid="button-confirm-reset-all"
                  >
                    Yes, Delete Everything
                  </AlertDialogAction>
                </AlertDialogFooter>
              </AlertDialogContent>
            </AlertDialog>
          </div>
          <Alert>
            <Info className="h-4 w-4" />
            <AlertDescription className="text-xs">
              <strong>Admin Authentication Required:</strong> This operation requires admin
              privileges and is logged for audit purposes.
            </AlertDescription>
          </Alert>
        </CardContent>
      </Card>
    </>
  );
}
