import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Plus, Settings, Lock, Search } from "lucide-react";
import { TableSkeleton, ErrorState } from "@/components/patterns";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { SensorTemplateCreateDialog, SensorTemplateEditDialog } from "@/components/sensors/SensorTemplateFormDialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { useSensorTemplatesPage } from "@/features/telemetry";

const SENSOR_KINDS = ["vibration", "pressure", "temperature", "flow", "level", "voltage", "current", "frequency", "rpm", "oil_debris", "acoustic", "position"];
const EQUIPMENT_TYPES = ["main_engine", "auxiliary_engine", "gearbox", "marine_pump", "compressor", "generator", "boiler", "heat_exchanger", "propeller", "rudder", "thruster", "winch", "crane", "ballast_pump", "fire_pump", "hvac", "navigation_system"];

const getKindBadge = (kind: string) => { const colorMap: Record<string, string> = { vibration: "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200", pressure: "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200", temperature: "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200", flow: "bg-cyan-100 text-cyan-800 dark:bg-cyan-900 dark:text-cyan-200", level: "bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200", voltage: "bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200", current: "bg-indigo-100 text-indigo-800 dark:bg-indigo-900 dark:text-indigo-200", frequency: "bg-pink-100 text-pink-800 dark:bg-pink-900 dark:text-pink-200", rpm: "bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200", oil_debris: "bg-amber-100 text-amber-800 dark:bg-amber-900 dark:text-amber-200", acoustic: "bg-teal-100 text-teal-800 dark:bg-teal-900 dark:text-teal-200" }; return <Badge variant="secondary" className={colorMap[kind] || "bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-200"}>{kind}</Badge>; };

export default function SensorTemplatesPage() {
  const { selectedTemplate, isCreateDialogOpen, setIsCreateDialogOpen, isEditDialogOpen, setIsEditDialogOpen, deleteTemplate, setDeleteTemplate, searchQuery, setSearchQuery, kindFilter, setKindFilter, equipmentTypeFilter, setEquipmentTypeFilter, page, setPage, isLoading, error, systemTemplates, customTemplates, paginatedCustomTemplates, paginationMeta, handleEdit, handleDelete, clearFilters, hasActiveFilters, deleteMutation } = useSensorTemplatesPage();

  if (isLoading) {return <div className="container mx-auto p-6 space-y-6"><Card><CardHeader><CardTitle>Loading Templates...</CardTitle></CardHeader><CardContent><TableSkeleton rows={5} columns={6} /></CardContent></Card></div>;}
  if (error) {return <div className="container mx-auto p-6 space-y-6"><ErrorState error={error} onRetry={() => globalThis.location.reload()} /></div>;}

  return (
    <div className="min-h-screen">
      <div className="container mx-auto p-6 space-y-6">
        <div className="flex items-center justify-end"><Button onClick={() => setIsCreateDialogOpen(true)} data-testid="button-create-template"><Plus className="h-4 w-4 mr-2" />Create Template</Button></div>

      <Card><CardHeader><CardTitle className="text-lg">Filters</CardTitle></CardHeader><CardContent><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><div className="space-y-2"><Label htmlFor="search">Search</Label><div className="relative"><Search className="absolute left-2 top-2.5 h-4 w-4 text-muted-foreground" /><Input id="search" placeholder="Search templates..." value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} className="pl-8" data-testid="input-search" /></div></div><div className="space-y-2"><Label htmlFor="kind-filter">Sensor Kind</Label><Select value={kindFilter} onValueChange={setKindFilter}><SelectTrigger id="kind-filter" data-testid="select-kind-filter"><SelectValue placeholder="All kinds" /></SelectTrigger><SelectContent><SelectItem value="all">All kinds</SelectItem>{SENSOR_KINDS.map((kind) => <SelectItem key={kind} value={kind}>{kind}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="equipment-filter">Equipment Type</Label><Select value={equipmentTypeFilter} onValueChange={setEquipmentTypeFilter}><SelectTrigger id="equipment-filter" data-testid="select-equipment-filter"><SelectValue placeholder="All types" /></SelectTrigger><SelectContent><SelectItem value="all">All types</SelectItem>{EQUIPMENT_TYPES.map((type) => <SelectItem key={type} value={type}>{type.replaceAll('_', " ")}</SelectItem>)}</SelectContent></Select></div></div>{hasActiveFilters && <div className="mt-4"><Button variant="outline" size="sm" onClick={clearFilters} data-testid="button-clear-filters">Clear Filters</Button></div>}</CardContent></Card>

      {systemTemplates.length > 0 && <Card><CardHeader><div className="flex items-center gap-2"><Lock className="h-5 w-5 text-muted-foreground" /><CardTitle>System Templates</CardTitle></div><CardDescription>Read-only templates provided by the system ({systemTemplates.length} templates)</CardDescription></CardHeader><CardContent><div className="rounded-md border"><Table><TableHeader><TableRow><TableHead>Template ID</TableHead><TableHead>Name</TableHead><TableHead>Kind</TableHead><TableHead>Unit</TableHead><TableHead>Equipment Types</TableHead><TableHead>Notes</TableHead></TableRow></TableHeader><TableBody>{systemTemplates.map((template) => <TableRow key={template.id} data-testid={`row-template-${template.templateId}`}><TableCell className="font-medium font-mono text-sm">{template.templateId}</TableCell><TableCell>{template.name}</TableCell><TableCell>{getKindBadge(template.kind)}</TableCell><TableCell>{template.unit || "-"}</TableCell><TableCell>{template.equipmentTypes && template.equipmentTypes.length > 0 ? <div className="flex flex-wrap gap-1">{template.equipmentTypes.slice(0, 3).map((type) => <Badge key={type} variant="outline" className="text-xs">{type.replaceAll('_', " ")}</Badge>)}{template.equipmentTypes.length > 3 && <Badge variant="outline" className="text-xs">+{template.equipmentTypes.length - 3} more</Badge>}</div> : "-"}</TableCell><TableCell className="max-w-xs truncate text-sm">{template.notes || "-"}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>}

      <Card><CardHeader><CardTitle>Custom Templates</CardTitle><CardDescription>Organization-specific templates ({customTemplates.length} templates)</CardDescription></CardHeader><CardContent>{customTemplates.length === 0 ? <div className="text-center py-12 text-muted-foreground"><Settings className="h-12 w-12 mx-auto mb-4 opacity-50" /><p className="font-medium">No custom templates yet</p><p className="text-sm mt-2">Create your first template to get started.</p></div> : <><div className="rounded-md border"><Table><TableHeader><TableRow><TableHead>Template ID</TableHead><TableHead>Name</TableHead><TableHead>Kind</TableHead><TableHead>Unit</TableHead><TableHead>Equipment Types</TableHead><TableHead>Notes</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{paginatedCustomTemplates.map((template) => <TableRow key={template.id} data-testid={`row-template-${template.templateId}`}><TableCell className="font-medium font-mono text-sm">{template.templateId}</TableCell><TableCell>{template.name}</TableCell><TableCell>{getKindBadge(template.kind)}</TableCell><TableCell>{template.unit || "-"}</TableCell><TableCell>{template.equipmentTypes && template.equipmentTypes.length > 0 ? <div className="flex flex-wrap gap-1">{template.equipmentTypes.slice(0, 2).map((type) => <Badge key={type} variant="outline" className="text-xs">{type.replaceAll('_', " ")}</Badge>)}{template.equipmentTypes.length > 2 && <Badge variant="outline" className="text-xs">+{template.equipmentTypes.length - 2}</Badge>}</div> : "-"}</TableCell><TableCell className="max-w-xs truncate text-sm">{template.notes || "-"}</TableCell><TableCell className="text-right"><div className="flex gap-2 justify-end"><Button size="sm" variant="outline" onClick={() => handleEdit(template)} data-testid={`button-edit-${template.templateId}`}>Edit</Button><Button size="sm" variant="destructive" onClick={() => setDeleteTemplate(template)} data-testid={`button-delete-${template.templateId}`}>Delete</Button></div></TableCell></TableRow>)}</TableBody></Table></div>{paginationMeta.totalPages > 1 && <div className="flex items-center justify-between mt-4"><div className="text-sm text-muted-foreground">Showing {(page - 1) * 50 + 1} to {Math.min(page * 50, paginationMeta.total)} of {paginationMeta.total} custom templates</div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => setPage((p) => Math.max(1, p - 1))} disabled={page === 1} data-testid="button-prev-page">Previous</Button><Button variant="outline" size="sm" onClick={() => setPage((p) => Math.min(paginationMeta.totalPages, p + 1))} disabled={page === paginationMeta.totalPages} data-testid="button-next-page">Next</Button></div></div>}</>}</CardContent></Card>

      <SensorTemplateCreateDialog open={isCreateDialogOpen} onOpenChange={setIsCreateDialogOpen} />
      {selectedTemplate && <SensorTemplateEditDialog open={isEditDialogOpen} onOpenChange={setIsEditDialogOpen} template={selectedTemplate} />}
      <AlertDialog open={!!deleteTemplate} onOpenChange={(open) => !open && setDeleteTemplate(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete Template</AlertDialogTitle><AlertDialogDescription>Are you sure you want to delete template "{deleteTemplate?.name}"? This action cannot be undone.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel data-testid="button-cancel-delete">Cancel</AlertDialogCancel><AlertDialogAction onClick={handleDelete} className="bg-destructive hover:bg-destructive/90" data-testid="button-confirm-delete">{deleteMutation.isPending ? "Deleting..." : "Delete"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
      </div>
    </div>
  );
}
