import { Link } from "wouter";
import { ArrowLeft, Ship, Server, Wrench, Users, TrendingUp, AlertCircle } from "lucide-react";
import { PowerSTWChart } from "@/components/analytics/PowerSTWChart";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { formatDistanceToNow } from "date-fns";
import { Skeleton } from "@/components/ui/skeleton";
import { ActiveDtcsPanel } from "@/components/ActiveDtcsPanel";
import { CIIBadge } from "@/components/compliance/CIIBadge";
import { OperatingModeChip } from "@/components/context/OperatingModeChip";
import { NarrativeSummaryCard } from "@/components/analytics/NarrativeSummaryCard";
import { useVesselDetail } from "@/features/vessels";
import { PageHeader } from "@/components/navigation";

export default function VesselDetail() {
  const { match, vesselId, vessel, vesselLoading, equipment, equipmentLoading, workOrdersLoading, crewLoading, schedulesLoading, vesselWorkOrders, vesselCrew, vesselMaintenanceSchedules, activeWorkOrders, completedWorkOrders, utilizationRate, totalCost, powerSTWDateRange } = useVesselDetail();

  if (!match || vesselLoading) {return <div className="p-6 space-y-6"><Skeleton className="h-8 w-64" /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Skeleton className="h-32" /><Skeleton className="h-32" /><Skeleton className="h-32" /><Skeleton className="h-32" /></div></div>;}
  if (!vessel) {return <div className="p-6"><Card><CardContent className="pt-6"><div className="text-center"><AlertCircle className="mx-auto h-12 w-12 text-muted-foreground" /><h3 className="mt-4 text-lg font-semibold">Vessel not found</h3><p className="text-muted-foreground">The vessel you're looking for doesn't exist.</p><Button asChild className="mt-4"><Link href="/vessel-management">Back to Vessels</Link></Button></div></CardContent></Card></div>;}

  return (
    <div className="min-h-screen" data-testid="vessel-detail-page">
      <PageHeader title={vessel.name} />
      <div className="p-6 space-y-6">
        <div className="flex flex-wrap items-center justify-end gap-2">
          <Badge variant={vessel.onlineStatus === "online" ? "default" : "secondary"}>{vessel.onlineStatus?.toUpperCase()}</Badge>
          <CIIBadge vesselId={vesselId!} vesselName={vessel.name} />
          <OperatingModeChip vesselId={vesselId!} />
        </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <Card><CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2"><CardTitle className="text-sm font-medium">Equipment</CardTitle><Server className="h-4 w-4 text-muted-foreground" /></CardHeader><CardContent><div className="text-2xl font-bold">{equipment.length}</div><p className="text-xs text-muted-foreground">Total registered equipment</p></CardContent></Card>
        <Card><CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2"><CardTitle className="text-sm font-medium">Active Work Orders</CardTitle><Wrench className="h-4 w-4 text-muted-foreground" /></CardHeader><CardContent><div className="text-2xl font-bold">{activeWorkOrders.length}</div><p className="text-xs text-muted-foreground">{completedWorkOrders.length} completed</p></CardContent></Card>
        <Card><CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2"><CardTitle className="text-sm font-medium">Crew Assigned</CardTitle><Users className="h-4 w-4 text-muted-foreground" /></CardHeader><CardContent><div className="text-2xl font-bold">{vesselCrew.length}</div><p className="text-xs text-muted-foreground">Active crew members</p></CardContent></Card>
        <Card><CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2"><CardTitle className="text-sm font-medium">Utilization Rate</CardTitle><TrendingUp className="h-4 w-4 text-muted-foreground" /></CardHeader><CardContent><div className="text-2xl font-bold">{utilizationRate}%</div><p className="text-xs text-muted-foreground">{vessel.operationDays || 0} days operational</p></CardContent></Card>
      </div>

      <Tabs defaultValue="overview" className="space-y-4">
        <div className="overflow-x-auto -mx-6 px-6 lg:mx-0 lg:px-0"><TabsList className="inline-flex w-auto min-w-full lg:w-full"><TabsTrigger value="overview" data-testid="tab-overview" className="whitespace-nowrap">Overview</TabsTrigger><TabsTrigger value="equipment" data-testid="tab-equipment" className="whitespace-nowrap">Equipment ({equipment.length})</TabsTrigger><TabsTrigger value="work-orders" data-testid="tab-work-orders" className="whitespace-nowrap">Work Orders ({activeWorkOrders.length})</TabsTrigger><TabsTrigger value="crew" data-testid="tab-crew" className="whitespace-nowrap">Crew ({vesselCrew.length})</TabsTrigger><TabsTrigger value="maintenance" data-testid="tab-maintenance" className="whitespace-nowrap">Maintenance ({vesselMaintenanceSchedules.length})</TabsTrigger><TabsTrigger value="performance" data-testid="tab-performance" className="whitespace-nowrap">Performance</TabsTrigger></TabsList></div>

        <TabsContent value="overview" className="space-y-4"><div className="grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle>Vessel Information</CardTitle></CardHeader><CardContent className="space-y-2"><div className="flex justify-between"><span className="text-muted-foreground">Class:</span><span className="font-medium">{vessel.vesselClass?.replace("_", " ") || "N/A"}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Condition:</span><span className="font-medium">{vessel.condition || "N/A"}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Status:</span><span className="font-medium">{vessel.onlineStatus || "N/A"}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Day Rate:</span><span className="font-medium">SGD {vessel.dayRateSgd || "N/A"}</span></div></CardContent></Card><Card><CardHeader><CardTitle>Financial Summary</CardTitle></CardHeader><CardContent className="space-y-2"><div className="flex justify-between"><span className="text-muted-foreground">Operation Days:</span><span className="font-medium">{vessel.operationDays || 0}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Downtime Days:</span><span className="font-medium">{vessel.downtimeDays || 0}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Total Revenue:</span><span className="font-medium">SGD {totalCost}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Utilization:</span><span className="font-medium">{utilizationRate}%</span></div></CardContent></Card></div></TabsContent>

        <TabsContent value="equipment" className="space-y-6"><Card><CardHeader><CardTitle>Equipment List</CardTitle><CardDescription>All equipment registered to this vessel</CardDescription></CardHeader><CardContent>{equipmentLoading ? <div className="space-y-2"><Skeleton className="h-12" /><Skeleton className="h-12" /></div> : equipment.length === 0 ? <div className="text-center py-8 text-muted-foreground">No equipment found for this vessel</div> : <div className="relative"><div className="absolute right-0 top-0 bottom-0 w-8 bg-gradient-to-l from-background to-transparent pointer-events-none z-10 lg:hidden" /><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>ID</TableHead><TableHead>Name</TableHead><TableHead>Type</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{equipment.map((eq) => <TableRow key={eq.id}><TableCell className="font-mono">{eq.id}</TableCell><TableCell>{eq.name}</TableCell><TableCell>{eq.type || "N/A"}</TableCell><TableCell><Badge variant="outline">{eq.status || "Unknown"}</Badge></TableCell></TableRow>)}</TableBody></Table></div></div>}</CardContent></Card>{!equipmentLoading && equipment.length > 0 && <div className="space-y-4"><h3 className="text-lg font-semibold">Active Diagnostic Codes</h3>{equipment.map((eq) => <ActiveDtcsPanel key={eq.id} equipmentId={eq.id} equipmentName={eq.name || eq.id} />)}</div>}</TabsContent>

        <TabsContent value="work-orders"><Card><CardHeader><CardTitle>Work Orders</CardTitle><CardDescription>Active and completed maintenance work</CardDescription></CardHeader><CardContent>{workOrdersLoading ? <div className="space-y-2"><Skeleton className="h-12" /><Skeleton className="h-12" /></div> : vesselWorkOrders.length === 0 ? <div className="text-center py-8 text-muted-foreground">No work orders found for this vessel</div> : <div className="relative"><div className="absolute right-0 top-0 bottom-0 w-8 bg-gradient-to-l from-background to-transparent pointer-events-none z-10 lg:hidden" /><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>ID</TableHead><TableHead>Equipment</TableHead><TableHead>Description</TableHead><TableHead>Status</TableHead><TableHead>Created</TableHead></TableRow></TableHeader><TableBody>{vesselWorkOrders.map((wo) => <TableRow key={wo.id}><TableCell className="font-mono text-sm">{wo.id.slice(0, 8)}</TableCell><TableCell>{wo.equipmentId}</TableCell><TableCell className="max-w-xs truncate">{wo.description}</TableCell><TableCell><Badge variant={wo.status === "completed" ? "default" : wo.status === "in_progress" ? "secondary" : "outline"}>{wo.status}</Badge></TableCell><TableCell className="text-sm text-muted-foreground">{formatDistanceToNow(new Date(wo.createdAt), { addSuffix: true })}</TableCell></TableRow>)}</TableBody></Table></div></div>}</CardContent></Card></TabsContent>

        <TabsContent value="crew"><Card><CardHeader><CardTitle>Crew Members</CardTitle><CardDescription>Personnel assigned to this vessel</CardDescription></CardHeader><CardContent>{crewLoading ? <div className="space-y-2"><Skeleton className="h-12" /><Skeleton className="h-12" /></div> : vesselCrew.length === 0 ? <div className="text-center py-8 text-muted-foreground">No crew members assigned to this vessel</div> : <div className="relative"><div className="absolute right-0 top-0 bottom-0 w-8 bg-gradient-to-l from-background to-transparent pointer-events-none z-10 lg:hidden" /><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Name</TableHead><TableHead>Role</TableHead><TableHead>Rank</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{vesselCrew.map((member) => <TableRow key={member.id}><TableCell className="font-medium">{member.name}</TableCell><TableCell>{member.role || "N/A"}</TableCell><TableCell>{member.rank || "N/A"}</TableCell><TableCell><Badge variant="outline">{member.status || "Active"}</Badge></TableCell></TableRow>)}</TableBody></Table></div></div>}</CardContent></Card></TabsContent>

        <TabsContent value="maintenance"><Card><CardHeader><CardTitle>Maintenance Schedules</CardTitle><CardDescription>Scheduled and predictive maintenance</CardDescription></CardHeader><CardContent>{schedulesLoading ? <div className="space-y-2"><Skeleton className="h-12" /><Skeleton className="h-12" /></div> : vesselMaintenanceSchedules.length === 0 ? <div className="text-center py-8 text-muted-foreground">No maintenance schedules found for this vessel</div> : <div className="relative"><div className="absolute right-0 top-0 bottom-0 w-8 bg-gradient-to-l from-background to-transparent pointer-events-none z-10 lg:hidden" /><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Equipment</TableHead><TableHead>Type</TableHead><TableHead>Scheduled Date</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{vesselMaintenanceSchedules.map((schedule) => <TableRow key={schedule.id}><TableCell>{schedule.equipmentId}</TableCell><TableCell><Badge variant="outline">{schedule.isPredictive ? "Predictive" : "Scheduled"}</Badge></TableCell><TableCell>{new Date(schedule.scheduledDate).toLocaleDateString()}</TableCell><TableCell><Badge variant={schedule.status === "completed" ? "default" : schedule.status === "in_progress" ? "secondary" : "outline"}>{schedule.status}</Badge></TableCell></TableRow>)}</TableBody></Table></div></div>}</CardContent></Card></TabsContent>

        <TabsContent value="performance" className="space-y-6"><div className="grid gap-6 lg:grid-cols-3"><div className="lg:col-span-2"><PowerSTWChart vesselId={vesselId!} startDate={powerSTWDateRange.startDate} endDate={powerSTWDateRange.endDate} /></div><div className="lg:col-span-1"><NarrativeSummaryCard vesselId={vesselId!} vesselName={vessel.name} chartType="power_stw" currentMetrics={{ avgPower: equipment.length > 0 ? 150 : undefined }} /></div></div></TabsContent>
      </Tabs>
      </div>
    </div>
  );
}
