import { generalApiRateLimit, requireOrgId } from "./route-dependencies";

import type { DomainRouterConfig } from "./domain-router-config-types";

export const mountedDomainRouters: DomainRouterConfig[] = [
  // ===== Direct router mounts (mountPath mode — no wrapper layer) =====

  {
    name: "BeastMode",
    importPath: "../beast/index.js",
    functionName: "beastModeRouter",
    mountPath: "/api/beast",
    middlewareKeys: ["generalApiRateLimit"],
    getDeps: () => ({ generalApiRateLimit }),
  },
  {
    name: "Governance",
    importPath: "../governance/routes.js",
    functionName: "default",
    mountPath: "/api/governance",
    middlewareKeys: ["generalApiRateLimit"],
    getDeps: () => ({ generalApiRateLimit }),
  },
  {
    name: "ComplianceLegacy",
    importPath: "../compliance/routes.js",
    functionName: "default",
    mountPath: "/api/compliance",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },
  {
    name: "SensorBundles",
    importPath: "../routes/sensorBundles.js",
    functionName: "default",
    mountPath: "/api/sensor-bundles",
    middlewareKeys: ["generalApiRateLimit"],
    getDeps: () => ({ generalApiRateLimit }),
  },
  {
    name: "SensorTemplates",
    importPath: "../routes/sensorTemplates.js",
    functionName: "default",
    mountPath: "/api/sensor-templates",
    middlewareKeys: ["generalApiRateLimit"],
    getDeps: () => ({ generalApiRateLimit }),
  },
  {
    name: "Suppliers",
    importPath: "../suppliers/index.js",
    functionName: "suppliersRouter",
    mountPath: "/api",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },
  {
    name: "Purchasing",
    importPath: "../purchasing/index.js",
    functionName: "purchasingRouter",
    mountPath: "/api",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },
  {
    name: "ServiceOrders",
    importPath: "../service-orders/index.js",
    functionName: "serviceOrderRoutes",
    mountPath: "/api/service-orders",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },
  {
    name: "Diagnostics",
    importPath: "../routes/diagnostics.js",
    functionName: "default",
    mountPath: "/api/diagnostics",
    middlewareKeys: ["generalApiRateLimit"],
    getDeps: () => ({ generalApiRateLimit }),
  },
  {
    name: "MlAiStudio",
    importPath: "../ml-routes.js",
    functionName: "mlRouter",
    mountPath: "/api",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },
  {
    name: "AgentLegacy",
    importPath: "../routes/agent-routes.js",
    functionName: "default",
    mountPath: "/api",
    middlewareKeys: [],
    getDeps: () => ({}),
  },

  // ===== PdM Domain — Direct router mounts =====

  {
    name: "PdmDashboard",
    importPath: "../pdm/routes.js",
    functionName: "pdmRouter",
    mountPath: "/api/pdm",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },
  {
    name: "PdmFeatureStore",
    importPath: "../domains/pdm-platform/interfaces/index.js",
    functionName: "featureStoreRouter",
    mountPath: "/api/pdm/features",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },
  {
    // The PdM equipment-detail page's health query. Documented in
    // swagger/paths-pdm.ts long before it was implemented — keep this
    // mount or the page crashes on Vite's HTML 404 fallback.
    name: "PdmHealth",
    importPath: "../domains/pdm-platform/interfaces/index.js",
    functionName: "pdmHealthRouter",
    mountPath: "/api/pdm/health",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },
  {
    name: "PdmFleetAnalytics",
    importPath: "../domains/pdm-platform/interfaces/index.js",
    functionName: "fleetAnalyticsRouter",
    mountPath: "/api/pdm/fleet",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },
  {
    name: "PdmModelRegistry",
    importPath: "../domains/pdm-platform/interfaces/index.js",
    functionName: "modelRegistryRouter",
    mountPath: "/api/pdm/models",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },
  {
    name: "PdmInference",
    importPath: "../domains/pdm-platform/interfaces/index.js",
    functionName: "inferenceRouter",
    mountPath: "/api/pdm/infer",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },
  {
    name: "PdmDecisionSupport",
    importPath: "../domains/pdm-platform/interfaces/index.js",
    functionName: "pdmDecisionSupportRouter",
    mountPath: "/api/pdm/decision-support",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },
  {
    name: "PdmMonitoring",
    importPath: "../domains/pdm-platform/interfaces/index.js",
    functionName: "monitoringRouter",
    mountPath: "/api/pdm/drift",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },
  {
    name: "PredictionGovernance",
    importPath: "../domains/pdm-platform/interfaces/index.js",
    functionName: "predictionGovernanceRouter",
    mountPath: "/api/pdm/governance",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },
  {
    name: "TrainingPipeline",
    importPath: "../domains/pdm-platform/interfaces/index.js",
    functionName: "trainingPipelineRouter",
    mountPath: "/api/pdm/training",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },

  // ===== Digital Twin — Direct router mounts =====

  {
    name: "TwinDefinition",
    importPath: "../domains/pdm-platform/interfaces/index.js",
    functionName: "twinDefinitionRouter",
    mountPath: "/api/pdm/twin/def",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },
  {
    name: "TwinState",
    importPath: "../domains/pdm-platform/interfaces/index.js",
    functionName: "twinStateRouter",
    mountPath: "/api/pdm/twin/state",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },
  {
    name: "ResidualAnalysis",
    importPath: "../domains/pdm-platform/interfaces/index.js",
    functionName: "residualAnalysisRouter",
    mountPath: "/api/pdm/twin/residuals",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },
  {
    name: "ScenarioSim",
    importPath: "../domains/pdm-platform/interfaces/index.js",
    functionName: "scenarioSimRouter",
    mountPath: "/api/pdm/twin/scenarios",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },
  {
    name: "Replay",
    importPath: "../domains/pdm-platform/interfaces/index.js",
    functionName: "replayRouter",
    mountPath: "/api/pdm/twin/replay",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },
  {
    name: "TwinUpdates",
    importPath: "../domains/pdm-platform/interfaces/index.js",
    functionName: "twinUpdatesRouter",
    mountPath: "/api/pdm/twin/updates",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },
  {
    name: "Vessel3D",
    importPath: "../routes/vessel-3d-routes.js",
    functionName: "vessel3dRouter",
    mountPath: "/api/v1",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },
  {
    name: "EquipmentDependencies",
    importPath: "../routes/equipment-dependencies-routes.js",
    functionName: "equipmentDependenciesRouter",
    mountPath: "/api/v1",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },
  {
    name: "EquipmentCrossClass",
    importPath: "../routes/equipment-cross-class-routes.js",
    functionName: "equipmentCrossClassRouter",
    mountPath: "/api/v1",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },

  // ===== Other direct mounts =====

  {
    name: "EquipmentIntelligence",
    importPath: "../domains/equipment-intelligence/interfaces/routes.js",
    functionName: "default",
    mountPath: "/api/equipment-intelligence",
    middlewareKeys: ["requireOrgId", "generalApiRateLimit"],
    getDeps: () => ({ requireOrgId, generalApiRateLimit }),
  },
  {
    name: "AmosImport",
    importPath: "../import-adapters/amos/index.js",
    functionName: "amosImportRouter",
    mountPath: "/",
    middlewareKeys: ["generalApiRateLimit"],
    getDeps: () => ({ generalApiRateLimit }),
  },
  {
    name: "ShipmateImport",
    importPath: "../import-adapters/shipmate/index.js",
    functionName: "shipmateImportRouter",
    mountPath: "/api/import/shipmate",
    middlewareKeys: [],
    getDeps: () => ({}),
  },

  {
    name: "MqttHealth",
    importPath: "./mqtt-health-routes.js",
    functionName: "mqttHealthRouter",
    mountPath: "/api/mqtt/reliable-sync",
    middlewareKeys: ["generalApiRateLimit"],
    getDeps: () => ({ generalApiRateLimit }),
  },
  {
    name: "EquipmentLoadDistribution",
    importPath: "./equipment-load-distribution-routes.js",
    functionName: "equipmentLoadDistributionRouter",
    mountPath: "/api/equipment",
    middlewareKeys: ["generalApiRateLimit"],
    getDeps: () => ({ generalApiRateLimit }),
  },

  {
    name: "InfrastructureInline",
    importPath: "./inline-routes.js",
    functionName: "registerInlineRoutes",
    getDeps: () => ({}),
  },
];
