/**
 * Default Compliance Rules
 *
 * Predefined rules for deck and engine logbook compliance.
 */

import type { InsertComplianceRule } from "@shared/schema";

export const DEFAULT_DECK_RULES: Omit<InsertComplianceRule, "orgId">[] = [
  {
    ruleCode: "DLB_MISSING_WATCH",
    ruleName: "Missing Watch Officer Assignment",
    description:
      "Deck logbook daily record must have watch officer assignments for all 4 watch periods",
    sourceType: "logbook_deck",
    category: "operational",
    severity: "warning",
    ruleType: "missing_data",
    ruleConfig: { watchPeriods: ["00-06", "06-12", "12-18", "18-24"] },
    notifyOnTrigger: true,
    notifyRoles: ["Master", "ChiefOfficer"],
    notifyEmails: null,
    enabled: true,
  },
  {
    ruleCode: "DLB_MISSING_HOURLY",
    ruleName: "Incomplete Hourly Entries",
    description: "Deck logbook should have hourly navigation entries for operational hours",
    sourceType: "logbook_deck",
    category: "data_integrity",
    severity: "warning",
    ruleType: "missing_data",
    ruleConfig: { minHourlyEntries: 12 },
    notifyOnTrigger: true,
    notifyRoles: ["Master"],
    notifyEmails: null,
    enabled: true,
  },
  {
    ruleCode: "DLB_UNSIGNED",
    ruleName: "Unsigned Daily Record",
    description: "Deck logbook daily record should be signed before end of day",
    sourceType: "logbook_deck",
    category: "regulatory",
    severity: "critical",
    ruleType: "missing_data",
    ruleConfig: { graceHours: 24 },
    notifyOnTrigger: true,
    notifyRoles: ["Master", "ChiefOfficer"],
    notifyEmails: null,
    enabled: true,
  },
  {
    ruleCode: "DLB_MISSING_POSITION",
    ruleName: "Missing Noon Position",
    description: "Deck logbook should have noon position recorded for voyage tracking",
    sourceType: "logbook_deck",
    category: "operational",
    severity: "info",
    ruleType: "missing_data",
    ruleConfig: {},
    notifyOnTrigger: false,
    notifyRoles: null,
    notifyEmails: null,
    enabled: true,
  },
];

export const DEFAULT_ENGINE_RULES: Omit<InsertComplianceRule, "orgId">[] = [
  {
    ruleCode: "ER_MISSING_WATCH",
    ruleName: "Missing Engine Watch Assignment",
    description: "Engine room logbook must have watch engineer assignments for all watch periods",
    sourceType: "logbook_engine",
    category: "operational",
    severity: "warning",
    ruleType: "missing_data",
    ruleConfig: { watchPeriods: ["00-06", "06-12", "12-18", "18-24"] },
    notifyOnTrigger: true,
    notifyRoles: ["ChiefEngineer", "SecondEngineer"],
    notifyEmails: null,
    enabled: true,
  },
  {
    ruleCode: "ER_ME_OVERTEMP",
    ruleName: "Main Engine Overtemperature",
    description: "Main engine exhaust gas temperature exceeds safe threshold",
    sourceType: "logbook_engine",
    category: "safety",
    severity: "critical",
    ruleType: "threshold",
    ruleConfig: { maxExhaustTemp: 450, field: "meExhaustGasTemp" },
    notifyOnTrigger: true,
    notifyRoles: ["ChiefEngineer"],
    notifyEmails: null,
    enabled: true,
  },
  {
    ruleCode: "ER_ME_OVERLOAD",
    ruleName: "Main Engine Overload",
    description: "Main engine load exceeds maximum continuous rating",
    sourceType: "logbook_engine",
    category: "safety",
    severity: "warning",
    ruleType: "threshold",
    ruleConfig: { maxLoad: 90, field: "meLoad" },
    notifyOnTrigger: true,
    notifyRoles: ["ChiefEngineer"],
    notifyEmails: null,
    enabled: true,
  },
  {
    ruleCode: "ER_LOW_FUEL",
    ruleName: "Low Fuel ROB Warning",
    description: "Fuel remaining on board is below minimum threshold",
    sourceType: "logbook_engine",
    category: "operational",
    severity: "warning",
    ruleType: "threshold",
    ruleConfig: { minHfoRob: 50, minMdoRob: 20 },
    notifyOnTrigger: true,
    notifyRoles: ["ChiefEngineer", "Master"],
    notifyEmails: null,
    enabled: true,
  },
  {
    ruleCode: "ER_UNSIGNED",
    ruleName: "Unsigned Engine Log",
    description: "Engine room logbook should be signed before end of day",
    sourceType: "logbook_engine",
    category: "regulatory",
    severity: "critical",
    ruleType: "missing_data",
    ruleConfig: { graceHours: 24 },
    notifyOnTrigger: true,
    notifyRoles: ["ChiefEngineer"],
    notifyEmails: null,
    enabled: true,
  },
  {
    ruleCode: "ER_MISSING_HOURLY",
    ruleName: "Incomplete Hourly Engine Entries",
    description: "Engine room logbook should have hourly readings for operational hours",
    sourceType: "logbook_engine",
    category: "data_integrity",
    severity: "warning",
    ruleType: "missing_data",
    ruleConfig: { minHourlyEntries: 12 },
    notifyOnTrigger: true,
    notifyRoles: ["ChiefEngineer"],
    notifyEmails: null,
    enabled: true,
  },
  {
    ruleCode: "ER_BILGE_HIGH",
    ruleName: "High Bilge Level",
    description: "Engine room bilge level is above acceptable threshold",
    sourceType: "logbook_engine",
    category: "safety",
    severity: "warning",
    ruleType: "threshold",
    ruleConfig: { maxBilgeLevel: 80 },
    notifyOnTrigger: true,
    notifyRoles: ["ChiefEngineer"],
    notifyEmails: null,
    enabled: true,
  },
];
