/**
 * SQLite Schema Maintenance Module
 * Schedules, records, costs, templates, checklists, windows
 */

import { sqliteTable, text, integer, real, index } from "./base";

export const maintenanceSchedulesSqlite = sqliteTable(
  "maintenance_schedules",
  {
    id: text("id").primaryKey(),
    orgId: text("org_id").notNull(),
    equipmentId: text("equipment_id").notNull(),
    vesselId: text("vessel_id"),
    scheduledDate: integer("scheduled_date", { mode: "timestamp" }).notNull(),
    maintenanceType: text("maintenance_type").notNull(),
    priority: integer("priority").notNull().default(2),
    estimatedDuration: integer("estimated_duration"),
    description: text("description"),
    status: text("status").notNull().default("scheduled"),
    assignedTo: text("assigned_to"),
    pdmScore: real("pdm_score"),
    autoGenerated: integer("auto_generated", { mode: "boolean" }).default(false),
    workOrderId: text("work_order_id"),
    createdAt: integer("created_at", { mode: "timestamp" }),
    updatedAt: integer("updated_at", { mode: "timestamp" }),
  },
  (table) => ({
    equipmentIdx: index("idx_ms_equipment").on(table.equipmentId),
    vesselIdx: index("idx_ms_vessel").on(table.vesselId),
    scheduledDateIdx: index("idx_ms_scheduled_date").on(table.scheduledDate),
    statusIdx: index("idx_ms_status").on(table.status),
  })
);

export const maintenanceRecordsSqlite = sqliteTable(
  "maintenance_records",
  {
    id: text("id").primaryKey(),
    orgId: text("org_id").notNull(),
    scheduleId: text("schedule_id").notNull(),
    equipmentId: text("equipment_id").notNull(),
    maintenanceType: text("maintenance_type").notNull(),
    actualStartTime: integer("actual_start_time", { mode: "timestamp" }),
    actualEndTime: integer("actual_end_time", { mode: "timestamp" }),
    actualDuration: integer("actual_duration"),
    technician: text("technician"),
    notes: text("notes"),
    partsUsed: text("parts_used"),
    laborHours: real("labor_hours"),
    downtimeMinutes: integer("downtime_minutes"),
    completionStatus: text("completion_status").notNull().default("completed"),
    followUpRequired: integer("follow_up_required", { mode: "boolean" }).default(false),
    createdAt: integer("created_at", { mode: "timestamp" }),
  },
  (table) => ({
    scheduleIdx: index("idx_mr_schedule").on(table.scheduleId),
    equipmentIdx: index("idx_mr_equipment").on(table.equipmentId),
  })
);

export const maintenanceCostsSqlite = sqliteTable(
  "maintenance_costs",
  {
    id: text("id").primaryKey(),
    recordId: text("record_id"),
    scheduleId: text("schedule_id"),
    equipmentId: text("equipment_id").notNull(),
    workOrderId: text("work_order_id"),
    costType: text("cost_type").notNull(),
    amount: real("amount").notNull(),
    currency: text("currency").notNull().default("USD"),
    description: text("description"),
    createdAt: integer("created_at", { mode: "timestamp" }),
  },
  (table) => ({
    equipmentIdx: index("idx_mc_equipment").on(table.equipmentId),
    workOrderIdx: index("idx_mc_work_order").on(table.workOrderId),
  })
);

export const maintenanceTemplatesSqlite = sqliteTable(
  "maintenance_templates",
  {
    id: text("id").primaryKey(),
    orgId: text("org_id").notNull(),
    name: text("name").notNull(),
    description: text("description"),
    equipmentType: text("equipment_type").notNull(),
    manufacturer: text("manufacturer"),
    model: text("model"),
    maintenanceType: text("maintenance_type").notNull(),
    frequencyDays: integer("frequency_days"),
    frequencyHours: integer("frequency_hours"),
    estimatedDurationHours: real("estimated_duration_hours"),
    priority: integer("priority").default(3),
    requiredSkills: text("required_skills"),
    requiredParts: text("required_parts"),
    safetyNotes: text("safety_notes"),
    isActive: integer("is_active", { mode: "boolean" }).default(true),
    createdAt: integer("created_at", { mode: "timestamp" }),
    updatedAt: integer("updated_at", { mode: "timestamp" }),
  },
  (table) => ({
    typeIdx: index("idx_mt_type").on(table.equipmentType),
    activeIdx: index("idx_mt_active").on(table.isActive),
  })
);

export const maintenanceChecklistItemsSqlite = sqliteTable(
  "maintenance_checklist_items",
  {
    id: text("id").primaryKey(),
    templateId: text("template_id").notNull(),
    stepNumber: integer("step_number").notNull(),
    title: text("title").notNull(),
    description: text("description"),
    category: text("category"),
    required: integer("required", { mode: "boolean" }).default(true),
    imageUrl: text("image_url"),
    estimatedMinutes: integer("estimated_minutes"),
    safetyWarning: text("safety_warning"),
    expectedResult: text("expected_result"),
    acceptanceCriteria: text("acceptance_criteria"),
  },
  (table) => ({
    templateIdx: index("idx_mci_template").on(table.templateId, table.stepNumber),
  })
);

export const maintenanceChecklistCompletionsSqlite = sqliteTable(
  "maintenance_checklist_completions",
  {
    id: text("id").primaryKey(),
    workOrderId: text("work_order_id").notNull(),
    itemId: text("item_id").notNull(),
    completedAt: integer("completed_at", { mode: "timestamp" }),
    completedBy: text("completed_by"),
    completedByName: text("completed_by_name"),
    status: text("status").notNull().default("pending"),
    passed: integer("passed", { mode: "boolean" }),
    actualValue: text("actual_value"),
    notes: text("notes"),
    photoUrls: text("photo_urls"),
  },
  (table) => ({
    workOrderIdx: index("idx_mcc_work_order").on(table.workOrderId),
    itemIdx: index("idx_mcc_item").on(table.itemId),
  })
);

export const maintenanceWindowsSqlite = sqliteTable(
  "maintenance_windows",
  {
    id: text("id").primaryKey(),
    orgId: text("org_id").notNull(),
    title: text("title").notNull(),
    windowType: text("window_type").notNull(),
    startTime: integer("start_time", { mode: "timestamp" }).notNull(),
    endTime: integer("end_time", { mode: "timestamp" }).notNull(),
    isRecurring: integer("is_recurring", { mode: "boolean" }).default(false),
    recurrencePattern: text("recurrence_pattern"),
    vesselId: text("vessel_id"),
    equipmentIds: text("equipment_ids"),
    notes: text("notes"),
    createdAt: integer("created_at", { mode: "timestamp" }),
    updatedAt: integer("updated_at", { mode: "timestamp" }),
  },
  (table) => ({
    orgIdx: index("idx_mw_org").on(table.orgId),
    vesselIdx: index("idx_mw_vessel").on(table.vesselId),
    timeIdx: index("idx_mw_time").on(table.startTime, table.endTime),
  })
);

export const portCallSqlite = sqliteTable(
  "port_call",
  {
    id: text("id").primaryKey(),
    orgId: text("org_id").notNull(),
    vesselId: text("vessel_id").notNull(),
    port: text("port"),
    start: integer("start", { mode: "timestamp" }),
    end: integer("end", { mode: "timestamp" }),
    arrivalTime: integer("arrival_time", { mode: "timestamp" }),
    departureTime: integer("departure_time", { mode: "timestamp" }),
    notes: text("notes"),
    createdAt: integer("created_at", { mode: "timestamp" }),
  },
  (table) => ({
    vesselIdx: index("idx_pc_vessel").on(table.vesselId),
    arrivalIdx: index("idx_pc_arrival").on(table.arrivalTime),
  })
);

export const drydockWindowSqlite = sqliteTable(
  "drydock_window",
  {
    id: text("id").primaryKey(),
    orgId: text("org_id").notNull(),
    vesselId: text("vessel_id").notNull(),
    yard: text("yard"),
    start: integer("start", { mode: "timestamp" }),
    end: integer("end", { mode: "timestamp" }),
    workType: text("work_type"),
    status: text("status").notNull().default("planned"),
    actualCost: real("actual_cost"),
    notes: text("notes"),
    createdAt: integer("created_at", { mode: "timestamp" }),
  },
  (table) => ({
    vesselIdx: index("idx_dw_vessel").on(table.vesselId),
  })
);

export const expensesSqlite = sqliteTable(
  "expenses",
  {
    id: text("id").primaryKey(),
    orgId: text("org_id").notNull(),
    vesselId: text("vessel_id"),
    equipmentId: text("equipment_id"),
    workOrderId: text("work_order_id"),
    category: text("category").notNull(),
    amount: real("amount").notNull(),
    currency: text("currency").notNull().default("USD"),
    description: text("description"),
    incurredAt: integer("incurred_at", { mode: "timestamp" }),
    approvedBy: text("approved_by"),
    approvedAt: integer("approved_at", { mode: "timestamp" }),
    receiptUrl: text("receipt_url"),
    createdAt: integer("created_at", { mode: "timestamp" }),
  },
  (table) => ({
    orgIdx: index("idx_exp_org").on(table.orgId),
    categoryIdx: index("idx_exp_category").on(table.category),
  })
);

export const laborRatesSqlite = sqliteTable(
  "labor_rates",
  {
    id: text("id").primaryKey(),
    orgId: text("org_id").notNull(),
    skillType: text("skill_type").notNull(),
    ratePerHour: real("rate_per_hour").notNull(),
    currency: text("currency").notNull().default("USD"),
    effectiveFrom: integer("effective_from", { mode: "timestamp" }),
    effectiveTo: integer("effective_to", { mode: "timestamp" }),
    notes: text("notes"),
    createdAt: integer("created_at", { mode: "timestamp" }),
  },
  (table) => ({
    orgSkillIdx: index("idx_lr_org_skill").on(table.orgId, table.skillType),
  })
);
