/**
 * Default Role Templates - Maritime Crew Hierarchies
 *
 * Pre-configured permission sets for common maritime positions.
 * Organizations can use these as starting points.
 */

export interface RoleTemplateConfig {
  name: string;
  displayName: string;
  description: string;
  department: "bridge" | "engine" | "deck" | "steward" | "admin";
  hierarchyLevel: number;
  permissions: Array<{ resource: string; action: string }>;
  fleetType?: "deep_sea" | "offshore" | "cruise" | "cargo" | "tanker";
}

export const DEFAULT_ROLE_TEMPLATES: RoleTemplateConfig[] = [
  // Admin Level
  {
    name: "company_admin",
    displayName: "Company Administrator",
    description: "Full access to all features and settings",
    department: "admin",
    hierarchyLevel: 1,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "vessels", action: "create" },
      { resource: "vessels", action: "edit" },
      { resource: "vessels", action: "delete" },
      { resource: "vessels", action: "export" },
      { resource: "equipment", action: "view" },
      { resource: "equipment", action: "create" },
      { resource: "equipment", action: "edit" },
      { resource: "equipment", action: "delete" },
      { resource: "equipment", action: "manage_config" },
      { resource: "sensors", action: "view" },
      { resource: "sensors", action: "create" },
      { resource: "sensors", action: "edit" },
      { resource: "sensors", action: "delete" },
      { resource: "sensors", action: "manage_config" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "create" },
      { resource: "work_orders", action: "edit" },
      { resource: "work_orders", action: "delete" },
      { resource: "work_orders", action: "assign" },
      { resource: "work_orders", action: "complete" },
      { resource: "work_orders", action: "manage_parts" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "maintenance_schedules", action: "create" },
      { resource: "maintenance_schedules", action: "edit" },
      { resource: "maintenance_schedules", action: "delete" },
      { resource: "maintenance_schedules", action: "approve" },
      { resource: "maintenance_templates", action: "view" },
      { resource: "maintenance_templates", action: "create" },
      { resource: "maintenance_templates", action: "edit" },
      { resource: "maintenance_templates", action: "delete" },
      { resource: "alerts", action: "view" },
      { resource: "alerts", action: "edit" },
      { resource: "alerts", action: "delete" },
      { resource: "alerts", action: "manage_config" },
      { resource: "crew_members", action: "view" },
      { resource: "crew_members", action: "create" },
      { resource: "crew_members", action: "edit" },
      { resource: "crew_members", action: "delete" },
      { resource: "crew_members", action: "export" },
      { resource: "crew_schedules", action: "view" },
      { resource: "crew_schedules", action: "create" },
      { resource: "crew_schedules", action: "edit" },
      { resource: "crew_schedules", action: "delete" },
      { resource: "crew_schedules", action: "assign" },
      { resource: "rest_hours", action: "view" },
      { resource: "rest_hours", action: "create" },
      { resource: "rest_hours", action: "edit" },
      { resource: "rest_hours", action: "delete" },
      { resource: "rest_hours", action: "approve" },
      { resource: "rest_hours", action: "sign_off" },
      { resource: "certifications", action: "view" },
      { resource: "certifications", action: "create" },
      { resource: "certifications", action: "edit" },
      { resource: "certifications", action: "delete" },
      { resource: "safety_alarms", action: "view" },
      { resource: "safety_alarms", action: "trigger" },
      { resource: "safety_alarms", action: "clear" },
      { resource: "safety_alarms", action: "acknowledge" },
      { resource: "safety_alarms", action: "export" },
      { resource: "safety_alarm_types", action: "view" },
      { resource: "safety_alarm_types", action: "manage" },
      { resource: "leave_requests", action: "view" },
      { resource: "leave_requests", action: "create" },
      { resource: "leave_requests", action: "edit" },
      { resource: "leave_requests", action: "delete" },
      { resource: "leave_requests", action: "approve" },
      { resource: "inventory", action: "view" },
      { resource: "inventory", action: "create" },
      { resource: "inventory", action: "edit" },
      { resource: "inventory", action: "delete" },
      { resource: "inventory", action: "export" },
      { resource: "inventory_movements", action: "view" },
      { resource: "inventory_movements", action: "create" },
      { resource: "inventory_movements", action: "edit" },
      { resource: "inventory_movements", action: "delete" },
      { resource: "purchase_requests", action: "view" },
      { resource: "purchase_requests", action: "create" },
      { resource: "purchase_requests", action: "edit" },
      { resource: "purchase_requests", action: "delete" },
      { resource: "purchase_requests", action: "approve" },
      { resource: "suppliers", action: "view" },
      { resource: "suppliers", action: "create" },
      { resource: "suppliers", action: "edit" },
      { resource: "suppliers", action: "delete" },
      { resource: "deck_logbook", action: "view" },
      { resource: "deck_logbook", action: "create" },
      { resource: "deck_logbook", action: "edit" },
      { resource: "deck_logbook", action: "delete" },
      { resource: "deck_logbook", action: "sign_off" },
      { resource: "deck_logbook", action: "export" },
      { resource: "engine_logbook", action: "view" },
      { resource: "engine_logbook", action: "create" },
      { resource: "engine_logbook", action: "edit" },
      { resource: "engine_logbook", action: "delete" },
      { resource: "engine_logbook", action: "sign_off" },
      { resource: "engine_logbook", action: "export" },
      { resource: "compliance_findings", action: "view" },
      { resource: "compliance_findings", action: "create" },
      { resource: "compliance_findings", action: "edit" },
      { resource: "compliance_findings", action: "delete" },
      { resource: "compliance_findings", action: "approve" },
      { resource: "compliance_reports", action: "view" },
      { resource: "compliance_reports", action: "create" },
      { resource: "compliance_reports", action: "export" },
      { resource: "analytics_dashboard", action: "view" },
      { resource: "analytics_dashboard", action: "export" },
      { resource: "predictive_maintenance", action: "view" },
      { resource: "predictive_maintenance", action: "manage_config" },
      { resource: "predictive_maintenance", action: "override" },
      { resource: "condition_monitoring", action: "view" },
      { resource: "condition_monitoring", action: "create" },
      { resource: "condition_monitoring", action: "edit" },
      { resource: "condition_monitoring", action: "delete" },
      { resource: "ai_reports", action: "view" },
      { resource: "ai_reports", action: "create" },
      { resource: "ai_reports", action: "export" },
      { resource: "cost_savings", action: "view" },
      { resource: "cost_savings", action: "export" },
      { resource: "organization_settings", action: "view" },
      { resource: "organization_settings", action: "edit" },
      { resource: "user_management", action: "view" },
      { resource: "user_management", action: "create" },
      { resource: "user_management", action: "edit" },
      { resource: "user_management", action: "delete" },
      { resource: "permission_management", action: "view" },
      { resource: "permission_management", action: "create" },
      { resource: "permission_management", action: "edit" },
      { resource: "permission_management", action: "delete" },
      { resource: "system_settings", action: "view" },
      { resource: "system_settings", action: "edit" },
      { resource: "system_settings", action: "manage_config" },
      { resource: "integrations", action: "view" },
      { resource: "integrations", action: "create" },
      { resource: "integrations", action: "edit" },
      { resource: "integrations", action: "delete" },
      { resource: "integrations", action: "manage_config" },
      { resource: "audit_log", action: "view" },
      { resource: "audit_log", action: "export" },
    ],
  },

  {
    name: "super_admin",
    displayName: "Super Administrator",
    description:
      "Unrestricted system-level administrator for all hubs, roles, access, and safety controls",
    department: "admin",
    hierarchyLevel: 1,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "crew_members", action: "view" },
      { resource: "crew_members", action: "create" },
      { resource: "crew_members", action: "edit" },
      { resource: "crew_members", action: "delete" },
      { resource: "crew_members", action: "export" },
      { resource: "safety_alarms", action: "view" },
      { resource: "safety_alarms", action: "trigger" },
      { resource: "safety_alarms", action: "clear" },
      { resource: "safety_alarms", action: "acknowledge" },
      { resource: "safety_alarms", action: "export" },
      { resource: "safety_alarm_types", action: "view" },
      { resource: "safety_alarm_types", action: "manage" },
      { resource: "organization_settings", action: "view" },
      { resource: "organization_settings", action: "edit" },
      { resource: "user_management", action: "view" },
      { resource: "user_management", action: "create" },
      { resource: "user_management", action: "edit" },
      { resource: "user_management", action: "delete" },
      { resource: "permission_management", action: "view" },
      { resource: "permission_management", action: "create" },
      { resource: "permission_management", action: "edit" },
      { resource: "permission_management", action: "delete" },
      { resource: "system_settings", action: "view" },
      { resource: "system_settings", action: "edit" },
      { resource: "system_settings", action: "manage_config" },
      { resource: "audit_log", action: "view" },
      { resource: "audit_log", action: "export" },
      { resource: "predictive_maintenance", action: "view" },
      { resource: "predictive_maintenance", action: "manage_config" },
      { resource: "predictive_maintenance", action: "override" },
    ],
  },

  {
    name: "admin",
    displayName: "Administrator",
    description: "Administrative role for crew, access, settings, and operational configuration",
    department: "admin",
    hierarchyLevel: 5,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "crew_members", action: "view" },
      { resource: "crew_members", action: "create" },
      { resource: "crew_members", action: "edit" },
      { resource: "crew_members", action: "delete" },
      { resource: "crew_members", action: "export" },
      { resource: "safety_alarms", action: "view" },
      { resource: "safety_alarms", action: "trigger" },
      { resource: "safety_alarms", action: "clear" },
      { resource: "safety_alarms", action: "acknowledge" },
      { resource: "safety_alarms", action: "export" },
      { resource: "safety_alarm_types", action: "view" },
      { resource: "safety_alarm_types", action: "manage" },
      { resource: "organization_settings", action: "view" },
      { resource: "organization_settings", action: "edit" },
      { resource: "user_management", action: "view" },
      { resource: "user_management", action: "create" },
      { resource: "user_management", action: "edit" },
      { resource: "permission_management", action: "view" },
      { resource: "permission_management", action: "edit" },
      { resource: "audit_log", action: "view" },
      { resource: "predictive_maintenance", action: "view" },
      { resource: "predictive_maintenance", action: "manage_config" },
      { resource: "predictive_maintenance", action: "override" },
    ],
  },

  {
    name: "fleet_manager",
    displayName: "Fleet Manager",
    description: "Fleet-level operational manager with broad vessel, crew, and safety visibility",
    department: "admin",
    hierarchyLevel: 8,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "equipment", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "assign" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "maintenance_schedules", action: "approve" },
      { resource: "crew_members", action: "view" },
      { resource: "crew_members", action: "edit" },
      { resource: "crew_schedules", action: "view" },
      { resource: "crew_schedules", action: "assign" },
      { resource: "safety_alarms", action: "view" },
      { resource: "safety_alarms", action: "trigger" },
      { resource: "safety_alarms", action: "clear" },
      { resource: "safety_alarms", action: "acknowledge" },
      { resource: "safety_alarms", action: "export" },
      { resource: "safety_alarm_types", action: "view" },
      { resource: "analytics_dashboard", action: "view" },
      { resource: "audit_log", action: "view" },
    ],
  },

  // Bridge Department
  {
    name: "captain",
    displayName: "Captain / Master",
    description: "Vessel master with command authority",
    department: "bridge",
    hierarchyLevel: 10,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "vessels", action: "edit" },
      { resource: "equipment", action: "view" },
      { resource: "equipment", action: "edit" },
      { resource: "sensors", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "create" },
      { resource: "work_orders", action: "edit" },
      { resource: "work_orders", action: "assign" },
      { resource: "work_orders", action: "complete" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "maintenance_schedules", action: "approve" },
      { resource: "alerts", action: "view" },
      { resource: "alerts", action: "edit" },
      { resource: "crew_members", action: "view" },
      { resource: "crew_members", action: "edit" },
      { resource: "crew_schedules", action: "view" },
      { resource: "crew_schedules", action: "create" },
      { resource: "crew_schedules", action: "edit" },
      { resource: "crew_schedules", action: "assign" },
      { resource: "rest_hours", action: "view" },
      { resource: "rest_hours", action: "approve" },
      { resource: "rest_hours", action: "sign_off" },
      { resource: "certifications", action: "view" },
      { resource: "safety_alarms", action: "view" },
      { resource: "safety_alarms", action: "trigger" },
      { resource: "safety_alarms", action: "clear" },
      { resource: "safety_alarms", action: "acknowledge" },
      { resource: "safety_alarms", action: "export" },
      { resource: "safety_alarm_types", action: "view" },
      { resource: "leave_requests", action: "view" },
      { resource: "leave_requests", action: "approve" },
      { resource: "inventory", action: "view" },
      { resource: "purchase_requests", action: "view" },
      { resource: "purchase_requests", action: "approve" },
      { resource: "deck_logbook", action: "view" },
      { resource: "deck_logbook", action: "create" },
      { resource: "deck_logbook", action: "edit" },
      { resource: "deck_logbook", action: "sign_off" },
      { resource: "deck_logbook", action: "export" },
      { resource: "engine_logbook", action: "view" },
      { resource: "engine_logbook", action: "sign_off" },
      { resource: "compliance_findings", action: "view" },
      { resource: "compliance_findings", action: "approve" },
      { resource: "compliance_reports", action: "view" },
      { resource: "compliance_reports", action: "create" },
      { resource: "compliance_reports", action: "export" },
      { resource: "analytics_dashboard", action: "view" },
      { resource: "analytics_dashboard", action: "export" },
      { resource: "predictive_maintenance", action: "view" },
      { resource: "predictive_maintenance", action: "override" },
      { resource: "condition_monitoring", action: "view" },
      { resource: "ai_reports", action: "view" },
      { resource: "ai_reports", action: "create" },
      { resource: "cost_savings", action: "view" },
      { resource: "audit_log", action: "view" },
    ],
  },

  {
    name: "vessel_master",
    displayName: "Vessel Master",
    description: "Command authority for vessel operations, crew readiness, and safety alarms",
    department: "bridge",
    hierarchyLevel: 10,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "vessels", action: "edit" },
      { resource: "equipment", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "create" },
      { resource: "work_orders", action: "edit" },
      { resource: "work_orders", action: "assign" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "maintenance_schedules", action: "approve" },
      { resource: "crew_members", action: "view" },
      { resource: "crew_members", action: "edit" },
      { resource: "crew_schedules", action: "view" },
      { resource: "crew_schedules", action: "assign" },
      { resource: "rest_hours", action: "view" },
      { resource: "rest_hours", action: "approve" },
      { resource: "safety_alarms", action: "view" },
      { resource: "safety_alarms", action: "trigger" },
      { resource: "safety_alarms", action: "clear" },
      { resource: "safety_alarms", action: "acknowledge" },
      { resource: "safety_alarm_types", action: "view" },
      { resource: "deck_logbook", action: "view" },
      { resource: "deck_logbook", action: "sign_off" },
      { resource: "engine_logbook", action: "view" },
      { resource: "compliance_reports", action: "view" },
      { resource: "analytics_dashboard", action: "view" },
    ],
  },

  {
    name: "chief_officer",
    displayName: "Chief Officer / First Mate",
    description: "Second in command, deck operations",
    department: "bridge",
    hierarchyLevel: 20,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "equipment", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "create" },
      { resource: "work_orders", action: "edit" },
      { resource: "work_orders", action: "assign" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "alerts", action: "view" },
      { resource: "crew_members", action: "view" },
      { resource: "crew_schedules", action: "view" },
      { resource: "crew_schedules", action: "create" },
      { resource: "crew_schedules", action: "edit" },
      { resource: "rest_hours", action: "view" },
      { resource: "rest_hours", action: "create" },
      { resource: "rest_hours", action: "edit" },
      { resource: "certifications", action: "view" },
      { resource: "safety_alarms", action: "view" },
      { resource: "safety_alarms", action: "trigger" },
      { resource: "safety_alarms", action: "clear" },
      { resource: "safety_alarms", action: "acknowledge" },
      { resource: "safety_alarms", action: "export" },
      { resource: "safety_alarm_types", action: "view" },
      { resource: "leave_requests", action: "view" },
      { resource: "leave_requests", action: "create" },
      { resource: "inventory", action: "view" },
      { resource: "deck_logbook", action: "view" },
      { resource: "deck_logbook", action: "create" },
      { resource: "deck_logbook", action: "edit" },
      { resource: "engine_logbook", action: "view" },
      { resource: "compliance_findings", action: "view" },
      { resource: "compliance_findings", action: "create" },
      { resource: "analytics_dashboard", action: "view" },
      { resource: "predictive_maintenance", action: "view" },
      { resource: "condition_monitoring", action: "view" },
    ],
  },

  // Engine Department
  {
    name: "chief_engineer",
    displayName: "Chief Engineer",
    description: "Head of engine department with full maintenance authority",
    department: "engine",
    hierarchyLevel: 15,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "equipment", action: "view" },
      { resource: "equipment", action: "create" },
      { resource: "equipment", action: "edit" },
      { resource: "equipment", action: "manage_config" },
      { resource: "sensors", action: "view" },
      { resource: "sensors", action: "create" },
      { resource: "sensors", action: "edit" },
      { resource: "sensors", action: "manage_config" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "create" },
      { resource: "work_orders", action: "edit" },
      { resource: "work_orders", action: "delete" },
      { resource: "work_orders", action: "assign" },
      { resource: "work_orders", action: "complete" },
      { resource: "work_orders", action: "manage_parts" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "maintenance_schedules", action: "create" },
      { resource: "maintenance_schedules", action: "edit" },
      { resource: "maintenance_schedules", action: "approve" },
      { resource: "maintenance_templates", action: "view" },
      { resource: "maintenance_templates", action: "create" },
      { resource: "maintenance_templates", action: "edit" },
      { resource: "alerts", action: "view" },
      { resource: "alerts", action: "edit" },
      { resource: "alerts", action: "manage_config" },
      { resource: "crew_members", action: "view" },
      { resource: "crew_schedules", action: "view" },
      { resource: "crew_schedules", action: "create" },
      { resource: "crew_schedules", action: "edit" },
      { resource: "crew_schedules", action: "assign" },
      { resource: "rest_hours", action: "view" },
      { resource: "rest_hours", action: "create" },
      { resource: "rest_hours", action: "edit" },
      { resource: "rest_hours", action: "approve" },
      { resource: "inventory", action: "view" },
      { resource: "inventory", action: "create" },
      { resource: "inventory", action: "edit" },
      { resource: "inventory_movements", action: "view" },
      { resource: "inventory_movements", action: "create" },
      { resource: "purchase_requests", action: "view" },
      { resource: "purchase_requests", action: "create" },
      { resource: "purchase_requests", action: "approve" },
      { resource: "suppliers", action: "view" },
      { resource: "engine_logbook", action: "view" },
      { resource: "engine_logbook", action: "create" },
      { resource: "engine_logbook", action: "edit" },
      { resource: "engine_logbook", action: "sign_off" },
      { resource: "engine_logbook", action: "export" },
      { resource: "deck_logbook", action: "view" },
      { resource: "compliance_findings", action: "view" },
      { resource: "compliance_findings", action: "create" },
      { resource: "analytics_dashboard", action: "view" },
      { resource: "analytics_dashboard", action: "export" },
      { resource: "predictive_maintenance", action: "view" },
      { resource: "predictive_maintenance", action: "manage_config" },
      { resource: "condition_monitoring", action: "view" },
      { resource: "condition_monitoring", action: "create" },
      { resource: "condition_monitoring", action: "edit" },
      { resource: "ai_reports", action: "view" },
      { resource: "ai_reports", action: "create" },
      { resource: "cost_savings", action: "view" },
    ],
  },

  {
    name: "second_engineer",
    displayName: "Second Engineer",
    description: "Deputy engine department head with maintenance execution authority",
    department: "engine",
    hierarchyLevel: 25,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "equipment", action: "view" },
      { resource: "equipment", action: "edit" },
      { resource: "sensors", action: "view" },
      { resource: "sensors", action: "edit" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "create" },
      { resource: "work_orders", action: "edit" },
      { resource: "work_orders", action: "complete" },
      { resource: "work_orders", action: "manage_parts" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "maintenance_schedules", action: "create" },
      { resource: "maintenance_schedules", action: "edit" },
      { resource: "maintenance_templates", action: "view" },
      { resource: "alerts", action: "view" },
      { resource: "alerts", action: "edit" },
      { resource: "crew_schedules", action: "view" },
      { resource: "rest_hours", action: "view" },
      { resource: "rest_hours", action: "create" },
      { resource: "inventory", action: "view" },
      { resource: "inventory", action: "edit" },
      { resource: "inventory_movements", action: "view" },
      { resource: "inventory_movements", action: "create" },
      { resource: "purchase_requests", action: "view" },
      { resource: "purchase_requests", action: "create" },
      { resource: "engine_logbook", action: "view" },
      { resource: "engine_logbook", action: "create" },
      { resource: "engine_logbook", action: "edit" },
      { resource: "analytics_dashboard", action: "view" },
      { resource: "predictive_maintenance", action: "view" },
      { resource: "condition_monitoring", action: "view" },
      { resource: "condition_monitoring", action: "create" },
    ],
  },

  {
    name: "third_engineer",
    displayName: "Third Engineer",
    description: "Junior engineer with limited maintenance authority",
    department: "engine",
    hierarchyLevel: 35,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "equipment", action: "view" },
      { resource: "sensors", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "create" },
      { resource: "work_orders", action: "edit" },
      { resource: "work_orders", action: "complete" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "alerts", action: "view" },
      { resource: "inventory", action: "view" },
      { resource: "inventory_movements", action: "view" },
      { resource: "engine_logbook", action: "view" },
      { resource: "engine_logbook", action: "create" },
      { resource: "analytics_dashboard", action: "view" },
      { resource: "condition_monitoring", action: "view" },
    ],
  },

  // Deck Department
  {
    name: "bosun",
    displayName: "Bosun",
    description: "Senior deck rating, supervises deck crew",
    department: "deck",
    hierarchyLevel: 40,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "equipment", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "create" },
      { resource: "work_orders", action: "complete" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "alerts", action: "view" },
      { resource: "crew_schedules", action: "view" },
      { resource: "rest_hours", action: "view" },
      { resource: "rest_hours", action: "create" },
      { resource: "inventory", action: "view" },
      { resource: "deck_logbook", action: "view" },
      { resource: "deck_logbook", action: "create" },
    ],
  },

  {
    name: "able_seaman",
    displayName: "Able Seaman (AB)",
    description: "Qualified deck rating",
    department: "deck",
    hierarchyLevel: 50,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "equipment", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "complete" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "alerts", action: "view" },
      { resource: "rest_hours", action: "view" },
      { resource: "rest_hours", action: "create" },
      { resource: "deck_logbook", action: "view" },
    ],
  },

  {
    name: "oiler",
    displayName: "Oiler / Motorman",
    description: "Engine room rating",
    department: "engine",
    hierarchyLevel: 50,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "equipment", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "complete" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "alerts", action: "view" },
      { resource: "rest_hours", action: "view" },
      { resource: "rest_hours", action: "create" },
      { resource: "engine_logbook", action: "view" },
      { resource: "condition_monitoring", action: "view" },
    ],
  },

  {
    name: "technician",
    displayName: "Technician",
    description:
      "Maintenance technician focused on assigned work, equipment checks, and task closeout",
    department: "engine",
    hierarchyLevel: 55,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "equipment", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "edit" },
      { resource: "work_orders", action: "complete" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "alerts", action: "view" },
      { resource: "inventory", action: "view" },
      { resource: "condition_monitoring", action: "view" },
    ],
  },

  {
    name: "supervisor",
    displayName: "Supervisor",
    description:
      "Department supervisor for crew coordination, assigned work, and readiness follow-up",
    department: "deck",
    hierarchyLevel: 45,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "equipment", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "assign" },
      { resource: "work_orders", action: "complete" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "crew_members", action: "view" },
      { resource: "crew_schedules", action: "view" },
      { resource: "crew_schedules", action: "assign" },
      { resource: "safety_alarms", action: "view" },
      { resource: "safety_alarms", action: "acknowledge" },
      { resource: "alerts", action: "view" },
    ],
  },

  {
    name: "safety_officer",
    displayName: "Safety Officer",
    description: "Safety lead for alarms, acknowledgements, bulletins, and compliance follow-up",
    department: "deck",
    hierarchyLevel: 30,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "crew_members", action: "view" },
      { resource: "safety_alarms", action: "view" },
      { resource: "safety_alarms", action: "trigger" },
      { resource: "safety_alarms", action: "clear" },
      { resource: "safety_alarms", action: "acknowledge" },
      { resource: "safety_alarms", action: "export" },
      { resource: "safety_alarm_types", action: "view" },
      { resource: "compliance_findings", action: "view" },
      { resource: "compliance_findings", action: "create" },
      { resource: "compliance_reports", action: "view" },
      { resource: "audit_log", action: "view" },
    ],
  },

  {
    name: "logistics_user",
    displayName: "Logistics User",
    description:
      "Logistics and procurement user for inventory, purchase requests, and vessel supplies",
    department: "admin",
    hierarchyLevel: 60,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "inventory", action: "view" },
      { resource: "inventory", action: "create" },
      { resource: "inventory", action: "edit" },
      { resource: "inventory_movements", action: "view" },
      { resource: "inventory_movements", action: "create" },
      { resource: "purchase_requests", action: "view" },
      { resource: "purchase_requests", action: "create" },
      { resource: "suppliers", action: "view" },
      { resource: "suppliers", action: "create" },
      { resource: "work_orders", action: "view" },
    ],
  },

  {
    name: "crew_member",
    displayName: "Crew Member",
    description:
      "Standard crew portal user for vessel assignment, watch status, safety, and assigned tasks",
    department: "deck",
    hierarchyLevel: 80,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "complete" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "alerts", action: "view" },
      { resource: "rest_hours", action: "view" },
      { resource: "rest_hours", action: "create" },
      { resource: "safety_alarms", action: "view" },
      { resource: "safety_alarms", action: "acknowledge" },
    ],
  },

  // Viewer role (read-only)
  {
    name: "viewer",
    displayName: "Viewer",
    description: "Read-only access to non-sensitive data",
    department: "admin",
    hierarchyLevel: 100,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "equipment", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "alerts", action: "view" },
      { resource: "crew_members", action: "view" },
      { resource: "inventory", action: "view" },
      { resource: "analytics_dashboard", action: "view" },
    ],
  },
];

export function getTemplateByName(name: string): RoleTemplateConfig | undefined {
  return DEFAULT_ROLE_TEMPLATES.find((t) => t.name === name);
}

export function getTemplatesByDepartment(
  department: RoleTemplateConfig["department"]
): RoleTemplateConfig[] {
  return DEFAULT_ROLE_TEMPLATES.filter((t) => t.department === department);
}
