/**
 * Schema Maintenance - Schedules, Records, Templates, Costs, and Condition Monitoring
 * 
 * Maintenance planning, execution tracking, and condition-based maintenance.
 */

import {
  sql,
  pgTable,
  text,
  varchar,
  integer,
  real,
  numeric,
  timestamp,
  boolean,
  jsonb,
  index,
  createInsertSchema,
  z,
} from "./base";
import { organizations } from "./core";
import { vessels } from "./vessels";
import { equipment } from "./equipment";
import { workOrders } from "./work-orders";

// Maintenance schedules
export const maintenanceSchedules = pgTable("maintenance_schedules", {
  id: varchar("id")
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  orgId: varchar("org_id")
    .notNull()
    .references(() => organizations.id),
  equipmentId: varchar("equipment_id")
    .notNull()
    .references(() => equipment.id),
  vesselId: varchar("vessel_id").references(() => vessels.id),
  scheduledDate: timestamp("scheduled_date", { mode: "date" }).notNull(),
  maintenanceType: text("maintenance_type").notNull(),
  priority: integer("priority").notNull().default(2),
  estimatedDuration: integer("estimated_duration"),
  description: text("description"),
  status: text("status").notNull().default("scheduled"),
  assignedTo: text("assigned_to"),
  pdmScore: real("pdm_score"),
  autoGenerated: boolean("auto_generated").default(false),
  workOrderId: text("work_order_id"),
  createdAt: timestamp("created_at", { mode: "date" }).defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "date" }).defaultNow(),
});

// Maintenance records
export const maintenanceRecords = pgTable(
  "maintenance_records",
  {
    id: varchar("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    orgId: varchar("org_id")
      .notNull()
      .references(() => organizations.id),
    equipmentId: varchar("equipment_id")
      .notNull()
      .references(() => equipment.id),
    scheduledDate: timestamp("scheduled_date", { mode: "date" }),
    completedDate: timestamp("completed_date", { mode: "date" }),
    maintenanceType: text("maintenance_type").notNull(),
    description: text("description"),
    performedBy: text("performed_by"),
    notes: text("notes"),
    cost: real("cost"),
    createdAt: timestamp("created_at", { mode: "date" }).defaultNow(),
  },
  (table) => ({
    equipmentIdx: index("idx_maintenance_records_equipment").on(table.equipmentId),
  })
);

// Maintenance costs
export const maintenanceCosts = pgTable(
  "maintenance_costs",
  {
    id: varchar("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    orgId: varchar("org_id")
      .notNull()
      .references(() => organizations.id),
    equipmentId: varchar("equipment_id")
      .notNull()
      .references(() => equipment.id),
    costType: text("cost_type").notNull(),
    amount: real("amount").notNull(),
    currency: text("currency").default("SGD"),
    description: text("description"),
    incurredAt: timestamp("incurred_at", { mode: "date" }).notNull(),
    workOrderId: varchar("work_order_id"),
    createdAt: timestamp("created_at", { mode: "date" }).defaultNow(),
  },
  (table) => ({
    equipmentCostIdx: index("idx_maintenance_costs_equipment").on(table.equipmentId, table.incurredAt),
  })
);

// Maintenance templates
export const maintenanceTemplates = pgTable("maintenance_templates", {
  id: varchar("id")
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  orgId: varchar("org_id")
    .notNull()
    .references(() => organizations.id),
  name: text("name").notNull(),
  description: text("description"),
  equipmentType: text("equipment_type").notNull(),
  manufacturer: text("manufacturer"),
  model: text("model"),
  maintenanceType: text("maintenance_type").notNull(),
  frequencyDays: integer("frequency_days"),
  frequencyHours: integer("frequency_hours"),
  estimatedDurationHours: real("estimated_duration_hours"),
  priority: integer("priority").default(3),
  requiredSkills: text("required_skills").array(),
  requiredParts: jsonb("required_parts"),
  safetyNotes: text("safety_notes"),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at", { mode: "date" }).defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "date" }).defaultNow(),
  estimatedDurationMinutes: integer("estimated_duration_minutes"),
  checklistItems: jsonb("checklist_items"),
  intervalDays: integer("interval_days"),
  intervalHours: numeric("interval_hours"),
});

// Maintenance checklist items
// Drizzle schema is now aligned with the deployed PG schema (verified via \d).
// db-checklists.ts uses the canonical names: stepNumber, title, category, etc.
export const maintenanceChecklistItems = pgTable("maintenance_checklist_items", {
  id: varchar("id")
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  orgId: varchar("org_id")
    .notNull()
    .references(() => organizations.id),
  templateId: varchar("template_id")
    .notNull()
    .references(() => maintenanceTemplates.id),
  stepNumber: integer("step_number").notNull(),
  title: text("title").notNull(),
  description: text("description"),
  category: text("category"),
  required: boolean("required").default(true),
  imageUrl: text("image_url"),
  estimatedMinutes: integer("estimated_minutes"),
  safetyWarning: text("safety_warning"),
  expectedResult: text("expected_result"),
  acceptanceCriteria: text("acceptance_criteria"),
});

// Maintenance checklist completions
export const maintenanceChecklistCompletions = pgTable("maintenance_checklist_completions", {
  id: varchar("id")
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  orgId: varchar("org_id")
    .notNull()
    .references(() => organizations.id),
  workOrderId: varchar("work_order_id")
    .notNull()
    .references(() => workOrders.id),
  itemId: varchar("item_id")
    .notNull()
    .references(() => maintenanceChecklistItems.id),
  status: text("status").notNull().default("pending"),
  passed: boolean("passed"),
  actualValue: text("actual_value"),
  notes: text("notes"),
  photoUrls: text("photo_urls").array(),
  completedAt: timestamp("completed_at", { mode: "date" }),
  completedBy: varchar("completed_by"),
  completedByName: text("completed_by_name"),
});

// ========================================
// Condition Monitoring Tables
// ========================================

// Oil analysis for condition-based maintenance
export const oilAnalysis = pgTable("oil_analysis", {
  id: varchar("id")
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  orgId: varchar("org_id")
    .notNull()
    .references(() => organizations.id),
  equipmentId: varchar("equipment_id")
    .notNull()
    .references(() => equipment.id),
  sampleDate: timestamp("sample_date", { mode: "date" }).notNull(),
  sampleNumber: text("sample_number").notNull(),
  oilType: text("oil_type").notNull(),
  oilGrade: text("oil_grade"),
  serviceHours: real("service_hours"),
  viscosity40C: real("viscosity_40c"),
  viscosity100C: real("viscosity_100c"),
  viscosityIndex: real("viscosity_index"),
  density15C: real("density_15c"),
  flashPoint: real("flash_point"),
  pourPoint: real("pour_point"),
  acidNumber: real("acid_number"),
  baseNumber: real("base_number"),
  waterContent: real("water_content"),
  fuelDilution: real("fuel_dilution"),
  oxidation: real("oxidation"),
  nitration: real("nitration"),
  sulfation: real("sulfation"),
  iron: real("iron"),
  chromium: real("chromium"),
  lead: real("lead"),
  copper: real("copper"),
  tin: real("tin"),
  aluminum: real("aluminum"),
  nickel: real("nickel"),
  silver: real("silver"),
  molybdenum: real("molybdenum"),
  titanium: real("titanium"),
  vanadium: real("vanadium"),
  calcium: real("calcium"),
  magnesium: real("magnesium"),
  zinc: real("zinc"),
  phosphorus: real("phosphorus"),
  sulfur: real("sulfur"),
  barium: real("barium"),
  boron: real("boron"),
  silicon: real("silicon"),
  sodium: real("sodium"),
  potassium: real("potassium"),
  iso4406: text("iso_4406"),
  particleCount4: integer("particle_count_4"),
  particleCount6: integer("particle_count_6"),
  particleCount14: integer("particle_count_14"),
  particleCount21: integer("particle_count_21"),
  particleCount38: integer("particle_count_38"),
  particleCount70: integer("particle_count_70"),
  condition: text("condition").notNull().default("normal"),
  recommendations: text("recommendations"),
  labComments: text("lab_comments"),
  analysisMetadata: jsonb("analysis_metadata"),
  createdAt: timestamp("created_at", { mode: "date" }).defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "date" }).defaultNow(),
});

// Wear particle analysis - ferrography
export const wearParticleAnalysis = pgTable("wear_particle_analysis", {
  id: varchar("id")
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  orgId: varchar("org_id")
    .notNull()
    .references(() => organizations.id),
  equipmentId: varchar("equipment_id")
    .notNull()
    .references(() => equipment.id),
  oilAnalysisId: varchar("oil_analysis_id").references(() => oilAnalysis.id),
  analysisDate: timestamp("analysis_date", { mode: "date" }).notNull(),
  sampleNumber: text("sample_number").notNull(),
  dl: real("dl"),
  ds: real("ds"),
  pqIndex: real("pq_index"),
  wpc: real("wpc"),
  severity: text("severity").notNull().default("normal"),
  cuttingParticles: real("cutting_particles"),
  slidingParticles: real("sliding_particles"),
  fatigueParticles: real("fatigue_particles"),
  sphericalParticles: real("spherical_particles"),
  fibersContaminants: real("fibers_contaminants"),
  ferroMagnetic: real("ferro_magnetic"),
  nonFerrous: real("non_ferrous"),
  largeParticles: real("large_particles"),
  mediumParticles: real("medium_particles"),
  smallParticles: real("small_particles"),
  gearWear: real("gear_wear"),
  bearingWear: real("bearing_wear"),
  pumpWear: real("pump_wear"),
  cylinderWear: real("cylinder_wear"),
  wearMode: text("wear_mode"),
  wearSeverity: text("wear_severity").notNull().default("normal"),
  suspectedComponent: text("suspected_component"),
  recommendations: text("recommendations"),
  analystComments: text("analyst_comments"),
  magnification: text("magnification"),
  analysisMethod: text("analysis_method").notNull().default("ferrography"),
  imageUrls: text("image_urls").array(),
  analysisMetadata: jsonb("analysis_metadata"),
  createdAt: timestamp("created_at", { mode: "date" }).defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "date" }).defaultNow(),
});

// Condition monitoring summary
export const conditionMonitoring = pgTable("condition_monitoring", {
  id: varchar("id")
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  orgId: varchar("org_id")
    .notNull()
    .references(() => organizations.id),
  equipmentId: varchar("equipment_id")
    .notNull()
    .references(() => equipment.id),
  assessmentDate: timestamp("assessment_date", { mode: "date" }).notNull(),
  oilConditionScore: real("oil_condition_score"),
  wearConditionScore: real("wear_condition_score"),
  vibrationScore: real("vibration_score"),
  thermalScore: real("thermal_score"),
  overallConditionScore: real("overall_condition_score").notNull(),
  trend: text("trend").notNull().default("stable"),
  trendConfidence: real("trend_confidence"),
  failureRisk: text("failure_risk").notNull().default("low"),
  estimatedTtf: real("estimated_ttf"),
  confidenceInterval: real("confidence_interval"),
  maintenanceAction: text("maintenance_action"),
  maintenanceUrgency: text("maintenance_urgency").notNull().default("routine"),
  maintenanceWindow: real("maintenance_window"),
  costEstimate: real("cost_estimate"),
  lastOilAnalysisId: varchar("last_oil_analysis_id").references(() => oilAnalysis.id),
  lastWearAnalysisId: varchar("last_wear_analysis_id").references(() => wearParticleAnalysis.id),
  assessmentMethod: text("assessment_method").notNull().default("combined"),
  analysisSummary: text("analysis_summary"),
  recommendations: text("recommendations"),
  analystId: varchar("analyst_id"),
  analysisMetadata: jsonb("analysis_metadata"),
  createdAt: timestamp("created_at", { mode: "date" }).defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "date" }).defaultNow(),
});

// Oil change records
export const oilChangeRecords = pgTable("oil_change_records", {
  id: varchar("id")
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  orgId: varchar("org_id")
    .notNull()
    .references(() => organizations.id),
  equipmentId: varchar("equipment_id")
    .notNull()
    .references(() => equipment.id),
  changeDate: timestamp("change_date", { mode: "date" }).notNull(),
  serviceHours: real("service_hours").notNull(),
  oilType: text("oil_type").notNull(),
  oilGrade: text("oil_grade").notNull(),
  quantityLiters: real("quantity_liters").notNull(),
  oilManufacturer: text("oil_manufacturer"),
  batchNumber: text("batch_number"),
  changeReason: text("change_reason").notNull(),
  filterChanged: boolean("filter_changed").default(true),
  filterType: text("filter_type"),
  laborHours: real("labor_hours"),
  totalCost: real("total_cost"),
  preChangeCondition: text("pre_change_condition"),
  draineOilAnalysisId: varchar("drained_oil_analysis_id").references(() => oilAnalysis.id),
  technicianId: varchar("technician_id"),
  workOrderId: varchar("work_order_id").references(() => workOrders.id),
  serviceNotes: text("service_notes"),
  createdAt: timestamp("created_at", { mode: "date" }).defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "date" }).defaultNow(),
});

// Insert schemas
export const insertMaintenanceScheduleSchema = createInsertSchema(maintenanceSchedules)
  .omit({ id: true, createdAt: true, updatedAt: true })
  .extend({
    maintenanceType: z.enum(["preventive", "corrective", "predictive"]),
    status: z.enum(["scheduled", "in_progress", "completed", "cancelled"]).default("scheduled"),
    priority: z.number().min(1).max(3).default(2),
    pdmScore: z.number().min(0).max(100).optional(),
    scheduledDate: z.string().or(z.date()).transform((val) => (typeof val === "string" ? new Date(val) : val)),
  });

export const insertMaintenanceRecordSchema = createInsertSchema(maintenanceRecords)
  .omit({ id: true, createdAt: true })
  .extend({
    maintenanceType: z.enum(["preventive", "corrective", "predictive", "emergency"]),
  });

export const insertMaintenanceCostSchema = createInsertSchema(maintenanceCosts)
  .omit({ id: true, createdAt: true })
  .extend({
    costType: z.enum(["labor", "parts", "consumables", "external", "downtime"]),
  });

export const insertMaintenanceTemplateSchema = createInsertSchema(maintenanceTemplates).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertMaintenanceChecklistItemSchema = createInsertSchema(maintenanceChecklistItems).omit({
  id: true,
});

export const insertMaintenanceChecklistCompletionSchema = createInsertSchema(maintenanceChecklistCompletions).omit({
  id: true,
});

// Condition Monitoring Insert Schemas
export const insertOilAnalysisSchema = createInsertSchema(oilAnalysis).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertWearParticleAnalysisSchema = createInsertSchema(wearParticleAnalysis).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertConditionMonitoringSchema = createInsertSchema(conditionMonitoring).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertOilChangeRecordSchema = createInsertSchema(oilChangeRecords).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

// Types
export type MaintenanceSchedule = typeof maintenanceSchedules.$inferSelect;
export type InsertMaintenanceSchedule = z.infer<typeof insertMaintenanceScheduleSchema>;
export type MaintenanceRecord = typeof maintenanceRecords.$inferSelect;
export type InsertMaintenanceRecord = z.infer<typeof insertMaintenanceRecordSchema>;
export type MaintenanceCost = typeof maintenanceCosts.$inferSelect;
export type InsertMaintenanceCost = z.infer<typeof insertMaintenanceCostSchema>;
export type MaintenanceTemplate = typeof maintenanceTemplates.$inferSelect;
export type InsertMaintenanceTemplate = z.infer<typeof insertMaintenanceTemplateSchema>;
export type MaintenanceChecklistItem = typeof maintenanceChecklistItems.$inferSelect;
export type InsertMaintenanceChecklistItem = z.infer<typeof insertMaintenanceChecklistItemSchema>;
export type MaintenanceChecklistCompletion = typeof maintenanceChecklistCompletions.$inferSelect;
export type InsertMaintenanceChecklistCompletion = z.infer<typeof insertMaintenanceChecklistCompletionSchema>;

// Condition Monitoring Types
export type OilAnalysis = typeof oilAnalysis.$inferSelect;
export type InsertOilAnalysis = z.infer<typeof insertOilAnalysisSchema>;
export type WearParticleAnalysis = typeof wearParticleAnalysis.$inferSelect;
export type InsertWearParticleAnalysis = z.infer<typeof insertWearParticleAnalysisSchema>;
export type ConditionMonitoring = typeof conditionMonitoring.$inferSelect;
export type InsertConditionMonitoring = z.infer<typeof insertConditionMonitoringSchema>;
export type OilChangeRecord = typeof oilChangeRecords.$inferSelect;
export type InsertOilChangeRecord = z.infer<typeof insertOilChangeRecordSchema>;
