export { dbDevicesStorage } from "./db/devices/index.js";
export { dbWorkOrderStorage } from "./db/workorders/index.js";
export { dbEquipmentStorage } from "./db/equipment/index.js";
export { dbVesselStorage } from "./db/vessels/index.js";
export { dbAlertStorage } from "./db/alerts/index.js";
export { dbInventoryStorage } from "./db/inventory/index.js";
export { dbCrewStorage } from "./db/crew/index.js";
export { dbCrewExtensionsStorage } from "./db/crew-extensions/index.js";
export { dbSensorsStorage } from "./db/sensors/index.js";
export { dbTelemetryStorage } from "./db/telemetry/index.js";
export { dbMlAnalyticsStorage } from "./db/ml-analytics/index.js";
export { dbMaintenanceStorage } from "./db/maintenance/index.js";
export { dbMaintenanceTemplatesStorage } from "./db/maintenance-templates/index.js";
export { dbAnalyticsStorage } from "./db/analytics/index.js";
export { dbSystemAdminStorage } from "./db/system-admin/index.js";
export { dbDtcStorage } from "./db/dtc/index.js";
export { dbNotificationsStorage } from "./db/notifications/index.js";
export { dbChecklistsStorage } from "./db/checklists/index.js";
export { dbStcwStorage } from "./db/stcw/index.js";
export { dbUserStorage } from "./db/users/index.js";
export { dbOptimizerStorage } from "./db/optimizer/index.js";
export { dbHubSyncStorage } from "./db/hub-sync/index.js";
export { dbStormGeoStorage } from "./db/stormgeo/index.js";
export { dbSchedulerStorage } from "./db/scheduler/index.js";

export { workOrderService } from "./services/domains/work-order-service";
export { vesselService } from "./services/domains/vessel-service";
export { crewService } from "./services/domains/crew-service";

import { DbDeckLogStorage } from "./storage/domains/logbook/deck-log/index.js";
import { DbEngineLogStorage } from "./storage/domains/logbook/engine-log/index.js";

export const deckLogStorage = new DbDeckLogStorage();
export const engineLogStorage = new DbEngineLogStorage();

import { DatabaseAnalyticsInsightsAdapter, type AnalyticsDependencies } from "./storage/domains/analytics-insights-adapter";
import { dbDevicesStorage } from "./db/devices/index.js";
import { dbEquipmentStorage } from "./db/equipment/index.js";
import { dbTelemetryStorage } from "./db/telemetry/index.js";
import { dbAnalyticsStorage } from "./db/analytics/index.js";
import { workOrderService } from "./services/domains/work-order-service";
import { vesselService } from "./services/domains/vessel-service";

const analyticsDeps: AnalyticsDependencies = {
  getDevices: async (orgId) => dbDevicesStorage.getDevices(orgId),
  getHeartbeats: async (orgId) => dbDevicesStorage.getHeartbeatsByOrg(orgId),
  getWorkOrders: async (eqId, st, pr, orgId) => workOrderService.getWorkOrdersWithDetails(eqId, orgId, st ? { status: st } : undefined),
  getPdmScores: async (eqId, orgId) => dbDevicesStorage.getPdmScores(eqId, orgId),
  getLatestTelemetryReadings: async (vesselId, equipmentId, sensorType, limit, _orgId) => dbTelemetryStorage.getLatestTelemetryReadings(equipmentId, limit || 500, vesselId, sensorType),
  getEquipmentRegistry: async (orgId) => dbEquipmentStorage.getEquipmentRegistry(orgId),
  getMetricsHistory: async (orgId, days) => dbAnalyticsStorage.getMetricsHistory(orgId, days),
  getVessels: async (orgId) => vesselService.getVessels(orgId),
  getEquipment: async (id) => dbEquipmentStorage.getEquipmentRegistry().then(eq => eq.find(e => e.id === id)),
};
export const analyticsInsightsAdapter = new DatabaseAnalyticsInsightsAdapter(analyticsDeps);

import { DbMaintenanceSchedulingAdapter, type MaintenanceSchedulingDeps } from "./storage/domains/maintenance-scheduling-adapter";
import { dbMaintenanceStorage } from "./db/maintenance/index.js";
import { dbAlertStorage } from "./db/alerts/index.js";
import { maintenanceSchedules } from "@shared/schema-runtime";
import { and, eq, sql } from "drizzle-orm";
import { db } from "./db-config";

const schedulingDeps: MaintenanceSchedulingDeps = {
  getExistingAutoSchedules: async (eqId) => db.select().from(maintenanceSchedules).where(and(eq(maintenanceSchedules.equipmentId, eqId), eq(maintenanceSchedules.autoGenerated, true), eq(maintenanceSchedules.status, "scheduled"))),
  createSchedule: async (s) => dbMaintenanceStorage.createMaintenanceSchedule(s),
  getEquipmentLifecycle: async (eqId) => dbAnalyticsStorage.getEquipmentLifecycle(eqId).then(d => d[0] || null),
  getMaintenanceRecords: async (eqId, from, to) => dbMaintenanceStorage.getMaintenanceRecords(eqId, from, to),
  getPerformanceMetrics: async (eqId, from, to) => dbAnalyticsStorage.getPerformanceMetrics(eqId, from, to),
  getAlertNotifications: async () => dbAlertStorage.getAlertNotifications()
};
export const schedulingAdapter = new DbMaintenanceSchedulingAdapter(schedulingDeps);

import { dbInventoryStorage } from "./db/inventory/index.js";
import { dbCrewStorage } from "./db/crew/index.js";
import { dbCrewExtensionsStorage } from "./db/crew-extensions/index.js";
import { dbSensorsStorage } from "./db/sensors/index.js";
import { dbMlAnalyticsStorage } from "./db/ml-analytics/index.js";
import { dbSystemAdminStorage } from "./db/system-admin/index.js";
import { dbDtcStorage } from "./db/dtc/index.js";
import { dbNotificationsStorage } from "./db/notifications/index.js";
import { dbChecklistsStorage } from "./db/checklists/index.js";
import { dbStcwStorage } from "./db/stcw/index.js";
import { dbUserStorage } from "./db/users/index.js";
import { dbStormGeoStorage } from "./db/stormgeo/index.js";
import { dbSchedulerStorage } from "./db/scheduler/index.js";
import { dbVesselStorage } from "./db/vessels/index.js";
import { dbWorkOrderStorage } from "./db/workorders/index.js";

export type { IStorage } from "./storage/interfaces/storage.types";

function createStorageFacade() {
  return {
    validateOrgId(orgId: string | undefined, operation: string): asserts orgId is string {
      if (!orgId || orgId.trim() === "") { throw new Error(`[Security] orgId is required for ${operation}.`); }
    },
    getDevices: (orgId?: string) => dbDevicesStorage.getDevices(orgId),
    getDevice: (id: string, orgId?: string) => dbDevicesStorage.getDevice(id, orgId),
    getPdmScores: (equipmentId: string | undefined, orgId: string) => dbDevicesStorage.getPdmScores(equipmentId, orgId),
    getWorkOrders: (equipmentId?: string, orgId?: string, filters?: any) => workOrderService.getWorkOrdersWithDetails(equipmentId, orgId, filters),
    getWorkOrderById: (id: string, orgId: string) => workOrderService.getWorkOrderById(id, orgId),
    generateWorkOrderNumber: (orgId: string) => workOrderService.generateWorkOrderNumber(orgId),
    createWorkOrder: (order: any) => workOrderService.createWorkOrder(order),
    updateWorkOrder: (id: string, updates: any) => workOrderService.updateWorkOrderWithDowntimeTracking(id, updates),
    getWorkOrderCompletions: (filters?: any) => dbWorkOrderStorage.getWorkOrderCompletions(filters),
    createTelemetryReading: (reading: any) => dbTelemetryStorage.createTelemetryReading(reading),
    getTelemetryHistory: (arg1: string, arg2: string, arg3?: any, arg4?: any, arg5?: any) => dbTelemetryStorage.getTelemetryHistory(arg1, arg2, arg3, arg4, arg5),
    getTelemetryByEquipmentAndDateRange: (equipmentId: string, startDate: Date, endDate: Date, orgId?: string) => dbTelemetryStorage.getTelemetryByEquipmentAndDateRange(equipmentId, startDate, endDate, orgId),
    getLatestTelemetryReadings: (vesselId?: string, equipmentId?: string, sensorType?: string, limit?: number, _orgId?: string) => dbTelemetryStorage.getLatestTelemetryReadings(equipmentId, limit || 500, vesselId, sensorType),
    upsertTelemetry: (reading: any) => dbTelemetryStorage.createTelemetryReading(reading),
    getTelemetry: (eqId: string, _orgId?: string) => dbTelemetryStorage.getLatestTelemetryReadings(eqId, 500),
    getTelemetryByEquipment: (equipmentId: string, startDate: Date, endDate: Date, orgId?: string) => dbTelemetryStorage.getTelemetryByEquipmentAndDateRange(equipmentId, startDate, endDate, orgId),
    getSensorConfigurations: (orgId?: string, equipmentId?: string, sensorType?: string) => dbSensorsStorage.getSensorConfigurations(orgId, equipmentId, sensorType),
    getSensorConfiguration: (equipmentId: string, sensorType: string, orgId?: string) => dbSensorsStorage.getSensorConfiguration(equipmentId, sensorType, orgId),
    createSensorConfiguration: (config: any) => dbSensorsStorage.createSensorConfiguration(config),
    updateSensorConfiguration: (equipmentId: string, sensorType: string, config: any, orgId?: string) => dbSensorsStorage.updateSensorConfiguration(equipmentId, sensorType, config, orgId),
    getAlertConfigurations: (equipmentId?: string) => dbAlertStorage.getAlertConfigurations(equipmentId),
    createAlertConfiguration: (config: any) => dbAlertStorage.createAlertConfiguration(config),
    updateAlertConfiguration: (id: string, config: any, orgId?: string) => dbAlertStorage.updateAlertConfiguration(id, config, orgId),
    getAlertNotifications: (acknowledged?: boolean, orgId?: string) => dbAlertStorage.getAlertNotifications(acknowledged, orgId),
    createAlertNotification: (notification: any) => dbAlertStorage.createAlertNotification(notification),
    hasRecentAlert: (equipmentId: string, sensorType: string, alertType: string, minutesBack?: number) => dbAlertStorage.hasRecentAlert(equipmentId, sensorType, alertType, minutesBack),
    isAlertSuppressed: (equipmentId: string, sensorType: string, alertType: string) => dbAlertStorage.isAlertSuppressed(equipmentId, sensorType, alertType),
    getSettings: () => dbSystemAdminStorage.getSettings(),
    getSystemSettings: () => dbSystemAdminStorage.getSettings(),
    createCrewRestSheet: (sheet: any) => dbStcwStorage.createCrewRestSheet(sheet),
    upsertCrewRestDay: (sheetId: string, dayData: any) => dbStcwStorage.upsertCrewRestDay(sheetId, dayData),
    getCrewRestRange: (crewId: string, startDate: string, endDate: string) => dbStcwStorage.getCrewRestRange(crewId, startDate, endDate),
    getCrewRestByDateRange: (vesselId?: string, startDate?: string, endDate?: string, complianceFilter?: boolean) => dbStcwStorage.getCrewRestByDateRange(vesselId, startDate, endDate, complianceFilter),
    markSchedulerRunHorGenerated: (runId: string) => dbSchedulerStorage.markSchedulerRunHorGenerated(runId),
    getWorkOrderWorklogs: (workOrderId?: string, orgId?: string) => dbChecklistsStorage.getWorkOrderWorklogs(workOrderId, orgId),
    getParts: (orgId?: string) => dbInventoryStorage.getParts(orgId),
    getPartsInventory: (category?: string, orgId?: string, search?: string, sortBy?: string, sortOrder?: "asc" | "desc") => dbInventoryStorage.getPartsInventory(category, orgId, search, sortBy, sortOrder),
    getPartById: (id: string, orgId?: string) => dbInventoryStorage.getPartById(id, orgId),
    createPartInventory: (part: any) => dbInventoryStorage.createPartsInventory(part),
    getPartByNumber: (partNo: string, orgId?: string) => orgId ? dbInventoryStorage.getPartByPartNumber(partNo, orgId) : Promise.resolve(undefined),
    getStockByPart: (partId: string, orgId?: string) => dbInventoryStorage.getStockByPart(partId, orgId),
    getWorkOrderParts: (workOrderId?: string, orgId?: string) => workOrderId ? dbWorkOrderStorage.getWorkOrderParts(workOrderId, orgId) : Promise.resolve([]),
    getWorkOrderPartsByEquipment: (orgId: string, equipmentId: string) => dbInventoryStorage.getWorkOrderPartsByEquipment(orgId, equipmentId),
    getWorkOrderPartsByPartId: (orgId: string, partId: string) => dbInventoryStorage.getWorkOrderPartsByPartId(orgId, partId),
    getMaintenanceSchedules: (equipmentId?: string, orgId?: string, filters?: any) => dbMaintenanceStorage.getMaintenanceSchedules(equipmentId, orgId, filters),
    getMaintenanceSchedule: (id: string) => dbMaintenanceStorage.getMaintenanceSchedule(id),
    createMaintenanceSchedule: (schedule: any) => dbMaintenanceStorage.createMaintenanceSchedule(schedule),
    updateMaintenanceSchedule: (id: string, updates: any) => dbMaintenanceStorage.updateMaintenanceSchedule(id, updates),
    getMaintenanceRecords: (equipmentId?: string, orgId?: string, filters?: any) => dbMaintenanceStorage.getMaintenanceRecords(equipmentId, orgId, filters),
    autoScheduleMaintenance: (equipmentId: string, pdmScore: number) => schedulingAdapter.autoScheduleMaintenance(equipmentId, pdmScore),
    getCrew: (orgId?: string, vesselId?: string) => dbCrewStorage.getCrew(orgId, vesselId),
    getCrewMember: (id: string, orgId?: string) => dbCrewStorage.getCrewMember(id, orgId),
    getCrewMembers: (orgId?: string) => dbCrewStorage.getCrew(orgId),
    getAllCrew: (orgId?: string) => dbCrewStorage.getCrew(orgId),
    getDeckLogDaily: (orgId: string, filters?: any) => deckLogStorage.getDeckLogDaily(orgId, filters),
    getDeckLogDailyByDate: (vesselId: string, logDate: string, orgId: string) => deckLogStorage.getDeckLogDailyByDate(vesselId, logDate, orgId),
    createDeckLogDaily: (entry: any) => deckLogStorage.createDeckLogDaily(entry),
    upsertDeckLogHourly: (entry: any) => deckLogStorage.upsertDeckLogHourly(entry),
    createDeckLogEvent: (event: any) => deckLogStorage.createDeckLogEvent(event),
    getEngineLogDaily: (orgId: string, filters?: any) => engineLogStorage.getEngineLogDaily(orgId, filters),
    getEngineLogDailyByDate: (vesselId: string, logDate: string, orgId: string) => engineLogStorage.getEngineLogDailyByDate(vesselId, logDate, orgId),
    createEngineLogDaily: (entry: any) => engineLogStorage.createEngineLogDaily(entry),
    updateEngineLogDaily: (id: string, entry: any, orgId: string) => engineLogStorage.updateEngineLogDaily(id, entry, orgId),
    getEngineLogHourly: (dailyLogId: string, orgId: string) => engineLogStorage.getEngineLogHourly(dailyLogId, orgId),
    upsertEngineLogHourly: (entry: any) => engineLogStorage.upsertEngineLogHourly(entry),
    getEngineLogGenerator: (dailyLogId: string, orgId: string) => engineLogStorage.getEngineLogGenerator(dailyLogId, orgId),
    upsertEngineLogGenerator: (entry: any) => engineLogStorage.upsertEngineLogGenerator(entry),
    createEngineLogEvent: (event: any) => engineLogStorage.createEngineLogEvent(event),
    getStormgeoSettings: (orgId: string, vesselId?: string) => dbStormGeoStorage.getStormgeoSettings(orgId, vesselId),
    createStormgeoSettings: (settings: any) => dbStormGeoStorage.createStormgeoSettings(settings),
    updateStormgeoSettings: (id: string, settings: any, orgId: string) => dbStormGeoStorage.updateStormgeoSettings(id, settings, orgId),
    getStormgeoSnapshots: (orgId: string, filters?: any) => dbStormGeoStorage.getStormgeoSnapshots(orgId, filters),
    getStormgeoSnapshotForTime: (vesselId: string, forecastTime: Date, orgId: string) => dbStormGeoStorage.getStormgeoSnapshotForTime(vesselId, forecastTime, orgId),
    createStormgeoSnapshot: (snapshot: any) => dbStormGeoStorage.createStormgeoSnapshot(snapshot),
    bulkCreateStormgeoSnapshots: (snapshots: any[]) => dbStormGeoStorage.bulkCreateStormgeoSnapshots(snapshots),
    createDeckLogHourlyAutoFill: (autoFill: any) => dbStormGeoStorage.createDeckLogHourlyAutoFill(autoFill),
    getStormgeoImportHistory: (orgId: string, filters?: any) => dbStormGeoStorage.getStormgeoImportHistory(orgId, filters),
    createStormgeoImportHistory: (history: any) => dbStormGeoStorage.createStormgeoImportHistory(history),
    updateStormgeoImportHistory: (id: string, history: any, orgId: string) => dbStormGeoStorage.updateStormgeoImportHistory(id, history, orgId),
    getCrewCertifications: (crewId: string, orgId: string) => dbCrewExtensionsStorage.getCrewCertifications(crewId, orgId),
    getComplianceFindings: async (orgId: string, filters?: any) => { const result = await db.execute(sql`SELECT * FROM compliance_findings WHERE org_id = ${orgId} ${filters?.vesselId ? sql`AND vessel_id = ${filters.vesselId}` : sql``} ${filters?.sourceType ? sql`AND source_type = ${filters.sourceType}` : sql``} ${filters?.severity ? sql`AND severity = ${filters.severity}` : sql``} ${filters?.status ? sql`AND status = ${filters.status}` : sql``} ${filters?.ruleCode ? sql`AND rule_code = ${filters.ruleCode}` : sql``} ${filters?.startDate ? sql`AND found_at >= ${filters.startDate}::timestamp` : sql``} ${filters?.endDate ? sql`AND found_at <= ${filters.endDate}::timestamp` : sql``} ORDER BY found_at DESC`); return result.rows; },
    getComplianceRules: async (orgId: string, filters?: any) => { const result = await db.execute(sql`SELECT * FROM compliance_rules WHERE org_id = ${orgId} ${filters?.sourceType ? sql`AND source_type = ${filters.sourceType}` : sql``} ${filters?.category ? sql`AND category = ${filters.category}` : sql``} ${filters?.enabled !== undefined ? sql`AND enabled = ${filters.enabled}` : sql``} ORDER BY rule_name ASC`); return result.rows; },
    createComplianceFinding: async (data: any) => { const result = await db.execute(sql`INSERT INTO compliance_findings (org_id, vessel_id, source_type, severity, status, rule_code, title, description, found_at) VALUES (${data.orgId}, ${data.vesselId}, ${data.sourceType}, ${data.severity}, ${data.status || 'open'}, ${data.ruleCode}, ${data.title}, ${data.description}, NOW()) RETURNING *`); return result.rows[0]; },
    createComplianceRule: async (data: any) => { const result = await db.execute(sql`INSERT INTO compliance_rules (org_id, source_type, category, rule_name, rule_code, description, severity, enabled) VALUES (${data.orgId}, ${data.sourceType}, ${data.category}, ${data.ruleName}, ${data.ruleCode}, ${data.description}, ${data.severity}, ${data.enabled ?? true}) RETURNING *`); return result.rows[0]; },
    resolveComplianceFinding: async (id: string, orgId: string) => { const result = await db.execute(sql`UPDATE compliance_findings SET status = 'resolved', resolved_at = NOW() WHERE id = ${id} AND org_id = ${orgId} RETURNING *`); return result.rows[0]; },
    acknowledgeComplianceFinding: async (id: string, orgId: string) => { const result = await db.execute(sql`UPDATE compliance_findings SET status = 'acknowledged' WHERE id = ${id} AND org_id = ${orgId} RETURNING *`); return result.rows[0]; },
    suppressComplianceFinding: async (id: string, orgId: string) => { const result = await db.execute(sql`UPDATE compliance_findings SET status = 'suppressed' WHERE id = ${id} AND org_id = ${orgId} RETURNING *`); return result.rows[0]; },
    getVessels: (orgId?: string) => vesselService.getVessels(orgId),
    getVessel: (id: string, orgId?: string) => vesselService.getVessel(id, orgId),
    createVessel: (vessel: any) => vesselService.createVessel(vessel),
    updateVessel: (id: string, updates: any, orgId: string) => vesselService.updateVessel(id, updates, orgId),
    getPortCalls: (vesselId?: string, orgId?: string) => vesselId && orgId ? dbVesselStorage.getPortCalls(vesselId, orgId) : dbVesselStorage.getAllPortCalls(orgId),
    getDrydockWindows: (orgId?: string, vesselId?: string) => vesselId && orgId ? dbVesselStorage.getDrydockWindows(vesselId, orgId) : dbVesselStorage.getAllDrydockWindows(orgId),
    getShiftTemplates: (orgId?: string) => dbCrewStorage.getShiftTemplates(orgId),
    getCrewAssignments: (orgId: string, date?: string, vesselId?: string) => dbCrewStorage.getCrewAssignments(orgId, { date, vesselId }),
    createCrewAssignment: (data: any) => dbCrewStorage.createCrewAssignment(data),
    getCrewAssignmentsByDateRange: (from: Date, to: Date, orgId?: string) => dbCrewStorage.getCrewAssignmentsByDateRange(from, to, orgId),
    deleteCrewAssignmentsByRunId: (orgId: string, runId: string) => dbCrewStorage.deleteCrewAssignmentsByRunId(orgId, runId),
    getCrewLeave: (crewId: string, orgId: string) => dbCrewStorage.getCrewLeave(crewId, orgId),
    getCrewSkills: (crewId: string) => dbCrewStorage.getCrewSkills(crewId),
    getSchedulerRuns: (orgId: string, limit?: number) => dbSchedulerStorage.getSchedulerRuns(orgId, undefined, limit),
    getSchedulerRun: (id: string) => dbSchedulerStorage.getSchedulerRun(id),
    getScheduleAssignmentsByRun: (runId: string) => dbSchedulerStorage.getScheduleAssignmentsByRun(runId),
    createSchedulerRun: (run: any) => dbSchedulerStorage.createSchedulerRun(run),
    deleteSchedulerRuns: (orgId: string) => dbSchedulerStorage.deleteSchedulerRuns(orgId),
    deleteScheduleAssignmentsByOrg: (orgId: string) => dbSchedulerStorage.deleteScheduleAssignmentsByOrg(orgId),
    deleteScheduleUnfilledByOrg: (orgId: string) => dbSchedulerStorage.deleteScheduleUnfilledByOrg(orgId),
    deleteScheduleAssignmentsByDateRange: (orgId: string, from: Date, to: Date) => dbSchedulerStorage.deleteScheduleAssignmentsByDateRange(orgId, from, to),
    findRecentSchedulerRunByHash: (orgId: string, hash: string) => dbSchedulerStorage.findRecentSchedulerRunByHash(orgId, hash),
    createBulkScheduleAssignments: (assignments: any[]) => dbSchedulerStorage.createBulkScheduleAssignments(assignments),
    createBulkScheduleUnfilled: (unfilled: any[]) => dbSchedulerStorage.createBulkScheduleUnfilled(unfilled),
    updateSchedulerRun: (id: string, updates: any) => dbSchedulerStorage.updateSchedulerRun(id, updates),
    getSchedulingSettings: (orgId: string) => dbSchedulerStorage.getSchedulingSettings(orgId),
    getSchedulingSettingsByVessel: (orgId: string, vesselId: string) => dbSchedulerStorage.getSchedulingSettingsByVessel(orgId, vesselId),
    createInsightSnapshot: (snapshot: any) => analyticsInsightsAdapter.createInsightSnapshot(snapshot),
    getLatestInsightSnapshot: (orgId: string, scope: string) => dbAnalyticsStorage.getLatestInsightSnapshot(orgId, scope),
    getAdminSessionByToken: (tokenHash: string) => dbSystemAdminStorage.getAdminSessionByToken(tokenHash),
    updateAdminSessionActivity: (sessionId: string) => dbSystemAdminStorage.updateAdminSessionActivity(sessionId),
    createAdminAuditEvent: (event: any) => dbSystemAdminStorage.createAdminAuditEvent(event),
    updateAdminAuditEvent: (id: string, updates: any) => dbSystemAdminStorage.updateAdminAuditEvent(id, updates),
    getMlModels: (orgId?: string, modelType?: string) => dbMlAnalyticsStorage.getMlModels(orgId, modelType),
    getMlModel: (id: string) => dbMlAnalyticsStorage.getMlModel(id),
    createMlModel: (model: any) => dbMlAnalyticsStorage.createMlModel(model),
    updateMlModel: (id: string, updates: any) => dbMlAnalyticsStorage.updateMlModel(id, updates),
    deleteMlModel: (id: string) => dbMlAnalyticsStorage.deleteMlModel(id),
    getMlModelAccuracyHistory: (modelId: string) => dbMlAnalyticsStorage.getMlModelAccuracyHistory(modelId),
    getEngineerOverrides: (orgId: string, filters?: any) => dbMlAnalyticsStorage.getEngineerOverrides(orgId, filters),
    createEngineerOverride: (override: any, orgId: string) => dbMlAnalyticsStorage.createEngineerOverride(override, orgId),
    getEquipmentRegistry: (orgId?: string) => dbEquipmentStorage.getEquipmentRegistry(orgId),
    getEquipment: (orgId: string, equipmentId: string) => dbEquipmentStorage.getEquipment(orgId, equipmentId),
    getEquipmentHealth: (orgId: string, vesselId?: string, equipmentId?: string) => dbEquipmentStorage.getEquipmentHealth(orgId, { vesselId, equipmentId }),
    createEquipment: (data: any) => dbEquipmentStorage.createEquipment(data),
    updateEquipment: (id: string, updates: any, orgId?: string) => dbEquipmentStorage.updateEquipment(id, updates, orgId || ''),
    getVesselEquipment: (vesselId: string, orgId?: string) => dbEquipmentStorage.getEquipmentByVessel(vesselId, orgId || ''),
    getEquipmentByVessel: (vesselId: string, orgId?: string) => dbEquipmentStorage.getEquipmentByVessel(vesselId, orgId || ''),
    getEquipmentSensorTypes: (orgId: string, equipmentId: string) => dbEquipmentStorage.getEquipmentSensorTypes(orgId, equipmentId),
    assignEquipmentToVessel: (vesselId: string, equipmentId: string, orgId?: string) => dbEquipmentStorage.associateEquipmentToVessel(equipmentId, vesselId, orgId || ''),
    unassignEquipmentFromVessel: (vesselId: string, equipmentId: string, orgId?: string) => dbEquipmentStorage.disassociateEquipmentFromVessel(equipmentId, orgId || ''),
    getDeviceById: (id: string, orgId?: string) => dbDevicesStorage.getDevice(id, orgId),
    getOrganization: (id: string) => dbUserStorage.getOrganization(id),
    createOrganization: (org: any) => dbUserStorage.createOrganization(org),
    updateOrganization: (id: string, updates: any) => dbUserStorage.updateOrganization(id, updates),
    getUsers: (orgId?: string) => dbUserStorage.getUsers(orgId),
    getUsersByOrg: (orgId: string) => dbUserStorage.getUsers(orgId),
    getUser: (id: string) => dbUserStorage.getUser(id),
    getUserByEmail: (email: string, orgId?: string) => dbUserStorage.getUserByEmail(email, orgId),
    createUser: (user: any) => dbUserStorage.createUser(user),
    getActiveDtcs: (equipmentId: string, orgId?: string) => dbDtcStorage.getActiveDtcs(equipmentId, orgId),
    getNotificationSettings: (orgId?: string, filters?: any) => dbNotificationsStorage.getNotificationSettings(orgId, filters?.userId),
    getNotificationQueue: (orgId?: string, filters?: any) => dbNotificationsStorage.getEmailQueue(filters?.status, undefined, orgId),
    createNotificationQueueItem: (item: any) => dbNotificationsStorage.createEmailQueueItem(item),
    updateNotificationQueueItem: (id: string, updates: any) => dbNotificationsStorage.updateEmailQueueItem(id, updates),
    getKbDocs: (orgId?: string) => analyticsInsightsAdapter.getKbDocs(orgId),
    getDigitalTwin: (twinId: string, orgId: string) => Promise.resolve(null as any),
    updateDigitalTwin: (twinId: string, orgId: string, updates: any) => Promise.resolve(null as any),
    getWorkOrder: (orgId: string, id: string) => workOrderService.getWorkOrderById(id, orgId),
    getWorkOrderPartsByEquipment2: (orgId: string, equipmentId: string) => dbInventoryStorage.getWorkOrderPartsByEquipment(orgId, equipmentId),
    getWorkOrderPartsByPartId2: (orgId: string, partId: string) => dbInventoryStorage.getWorkOrderPartsByPartId(orgId, partId),
  };
}

export const storage = createStorageFacade();
