import { dbDevicesStorage } from "./db/devices/index.js";
import { dbWorkOrderStorage } from "./db/workorders/index.js";
import { dbEquipmentStorage } from "./db/equipment/index.js";
import { dbVesselStorage } from "./db/vessels/index.js";
import { dbAlertStorage } from "./db/alerts/index.js";
import { dbInventoryStorage } from "./db/inventory/index.js";
import { dbCrewStorage } from "./db/crew/index.js";
import { dbCrewExtensionsStorage } from "./db/crew-extensions/index.js";
import { dbSensorsStorage } from "./db/sensors/index.js";
import { dbTelemetryStorage } from "./db/telemetry/index.js";
import { dbMlAnalyticsStorage } from "./db/ml-analytics/index.js";
import { dbMaintenanceStorage } from "./db/maintenance/index.js";
import { dbMaintenanceTemplatesStorage } from "./db/maintenance-templates/index.js";
import { dbAnalyticsStorage } from "./db/analytics/index.js";
export {
  dbDevicesStorage,
  dbWorkOrderStorage,
  dbEquipmentStorage,
  dbVesselStorage,
  dbAlertStorage,
  dbInventoryStorage,
  dbCrewStorage,
  dbCrewExtensionsStorage,
  dbSensorsStorage,
  dbTelemetryStorage,
  dbMlAnalyticsStorage,
  dbMaintenanceStorage,
  dbMaintenanceTemplatesStorage,
  dbAnalyticsStorage,
};
export { dbSystemAdminStorage } from "./db/system-admin/index.js";
export { dbDtcStorage } from "./db/dtc/index.js";
export { dbNotificationsStorage } from "./db/notifications/index.js";
export { dbChecklistsStorage } from "./db/checklists/index.js";
export { dbStcwStorage } from "./db/stcw/index.js";
export { dbUserStorage } from "./db/users/index.js";
export { dbOptimizerStorage } from "./db/optimizer/index.js";
export { dbHubSyncStorage } from "./db/hub-sync/index.js";
export { dbStormGeoStorage } from "./db/stormgeo/index.js";
export { dbSchedulerStorage } from "./db/scheduler/index.js";

export { workOrderService } from "./services/domains/work-order-service";
export { vesselService } from "./services/domains/vessel-service";
export { crewService } from "./services/domains/crew-service";

import { DbDeckLogStorage } from "./storage/domains/logbook/deck-log/index.js";
import { DbEngineLogStorage } from "./storage/domains/logbook/engine-log/index.js";

export const deckLogStorage = new DbDeckLogStorage();
export const engineLogStorage = new DbEngineLogStorage();

import {
  DatabaseAnalyticsInsightsAdapter,
  type AnalyticsDependencies,
} from "./storage/domains/analytics-insights-adapter";
import { workOrderService } from "./services/domains/work-order-service";
import { vesselService } from "./services/domains/vessel-service";

const analyticsDeps: AnalyticsDependencies = {
  getDevices: async (orgId) => dbDevicesStorage.getDevices(orgId),
  getHeartbeats: async (orgId) => dbDevicesStorage.getHeartbeatsByOrg(orgId),
  getWorkOrders: async (eqId, st, pr, orgId) =>
    workOrderService.getWorkOrdersWithDetails(eqId, orgId, st ? { status: st } : undefined),
  getPdmScores: async (eqId, orgId) => dbDevicesStorage.getPdmScores(eqId, orgId),
  getLatestTelemetryReadings: async (vesselId, equipmentId, sensorType, limit, _orgId) =>
    dbTelemetryStorage.getLatestTelemetryReadings(equipmentId, limit || 500, vesselId, sensorType),
  getEquipmentRegistry: async (orgId) => dbEquipmentStorage.getEquipmentRegistry(orgId),
  getMetricsHistory: async (orgId, days) => dbAnalyticsStorage.getMetricsHistory(orgId, days),
  getVessels: async (orgId) => vesselService.getVessels(orgId),
  getEquipment: async (id) =>
    dbEquipmentStorage.getEquipmentRegistry().then((eq) => eq.find((e) => e.id === id)),
};
export const analyticsInsightsAdapter = new DatabaseAnalyticsInsightsAdapter(analyticsDeps);

import {
  DbMaintenanceSchedulingAdapter,
  type MaintenanceSchedulingDeps,
} from "./storage/domains/maintenance-scheduling-adapter";
import { maintenanceSchedules } from "@shared/schema-runtime";
import { and, eq } from "drizzle-orm";
import { db } from "./db-config";

const schedulingDeps: MaintenanceSchedulingDeps = {
  getExistingAutoSchedules: async (eqId) =>
    db
      .select()
      .from(maintenanceSchedules)
      .where(
        and(
          eq(maintenanceSchedules.equipmentId, eqId),
          eq(maintenanceSchedules.autoGenerated, true),
          eq(maintenanceSchedules.status, "scheduled")
        )
      ),
  createSchedule: async (s) => dbMaintenanceStorage.createMaintenanceSchedule(s),
  getEquipmentLifecycle: async (eqId) =>
    dbAnalyticsStorage.getEquipmentLifecycle(eqId).then((d) => d[0] || null),
  getMaintenanceRecords: async (eqId, from, to) => {
    const fromTime = (from instanceof Date ? from : new Date(from)).getTime();
    const toTime = (to instanceof Date ? to : new Date(to)).getTime();
    const records = await dbMaintenanceStorage.getMaintenanceRecords(eqId);
    return records.filter((r) => {
      const created = r.createdAt ? new Date(r.createdAt).getTime() : 0;
      return created >= fromTime && created <= toTime;
    });
  },
  getPerformanceMetrics: async (eqId, from, to) =>
    dbAnalyticsStorage.getPerformanceMetrics(eqId, from, to),
  getAlertNotifications: async () => dbAlertStorage.getAlertNotifications(),
};
export const schedulingAdapter = new DbMaintenanceSchedulingAdapter(schedulingDeps);

// The legacy aggregated `storage` Proxy facade was removed in task 96.
// All callers now import the specific `db*Storage` singleton (or the
// owning domain service) they actually need.
