import type { WidenPartial } from "../../lib/widen-partial";
/**
 * Maintenance Service - Backward Compatibility Shim
 *
 * This file maintains backward compatibility with existing code
 * while delegating to the new hexagonal application service.
 *
 * Migration path:
 * 1. New code should import from './application'
 * 2. This shim will be deprecated once all consumers migrate
 */

import type {
  MaintenanceSchedule,
  InsertMaintenanceSchedule,
  MaintenanceTemplate,
  InsertMaintenanceTemplate,
} from "@shared/schema";
import { maintenanceAppService } from "./application";
import type {
  CreateScheduleCommand,
  UpdateScheduleCommand,
  CreateTemplateCommand,
  UpdateTemplateCommand,
  MaintenanceScheduleEntity,
  MaintenanceTemplateEntity,
} from "./domain/types";

const PRIORITY_TO_INT: Record<string, number> = {
  low: 1,
  medium: 2,
  high: 3,
  critical: 4,
};

function scheduleEntityToSchema(entity: MaintenanceScheduleEntity): MaintenanceSchedule {
  return {
    id: entity.id,
    orgId: entity.orgId,
    equipmentId: entity.equipmentId,
    vesselId: null,
    scheduledDate: entity.scheduledDate,
    maintenanceType: entity.maintenanceType,
    priority: PRIORITY_TO_INT[entity.priority] ?? 2,
    estimatedDuration: entity.estimatedDuration ?? null,
    description: entity.description ?? null,
    status: entity.status,
    assignedTo: entity.assignedTo ?? null,
    pdmScore: null,
    autoGenerated: false,
    workOrderId: null,
    createdAt: entity.createdAt ?? null,
    updatedAt: entity.updatedAt ?? null,
  };
}

function templateEntityToSchema(entity: MaintenanceTemplateEntity): MaintenanceTemplate {
  return {
    id: entity.id,
    orgId: entity.orgId,
    name: entity.name,
    description: entity.description ?? null,
    equipmentType: entity.equipmentType ?? "",
    manufacturer: null,
    model: null,
    maintenanceType: entity.maintenanceType,
    frequencyDays: null,
    frequencyHours: null,
    estimatedDurationHours: entity.estimatedDuration ?? null,
    priority: 3,
    requiredSkills: null,
    requiredParts: entity.requiredParts ?? null,
    safetyNotes: null,
    isActive: entity.isActive,
    createdAt: entity.createdAt ?? null,
    updatedAt: entity.updatedAt ?? null,
    estimatedDurationMinutes: null,
    checklistItems: entity.checklistItems ?? null,
    intervalDays: entity.intervalDays ?? null,
    intervalHours: entity.intervalHours ?? null,
  };
}

/**
 * Legacy insert shapes occasionally carried an `estimatedDurationHours` /
 * `notes` field that the hexagonal domain models as `estimatedDuration` /
 * `notes`. These helpers narrow the legacy payload without `any` casts.
 */
type LegacyScheduleExtras = {
  estimatedDurationHours?: number | undefined;
  notes?: string | undefined;
};
type LegacyTemplateExtras = {
  estimatedDurationHours?: number | undefined;
};

function pickLegacyScheduleExtras(
  data: WidenPartial<InsertMaintenanceSchedule>,
): LegacyScheduleExtras {
  const record = data as Record<string, unknown>;
  return {
    estimatedDurationHours:
      typeof record['estimatedDurationHours'] === "number"
        ? record['estimatedDurationHours']
        : undefined,
    notes: typeof record['notes'] === "string" ? record['notes'] : undefined,
  };
}

function pickLegacyTemplateExtras(
  data: WidenPartial<InsertMaintenanceTemplate>,
): LegacyTemplateExtras {
  const record = data as Record<string, unknown>;
  return {
    estimatedDurationHours:
      typeof record['estimatedDurationHours'] === "number"
        ? record['estimatedDurationHours']
        : undefined,
  };
}

/**
 * Maintenance Service (Legacy API)
 * Wraps the new hexagonal application service for backward compatibility
 */
export class MaintenanceService {
  // ========== Maintenance Schedules ==========

  async listSchedules(
    orgId: string,
    equipmentId?: string,
    status?: string,
  ): Promise<MaintenanceSchedule[]> {
    const entities = await maintenanceAppService.listSchedules(orgId, equipmentId, status);
    return entities.map(scheduleEntityToSchema);
  }

  async getScheduleById(id: string, orgId: string): Promise<MaintenanceSchedule | undefined> {
    const entity = await maintenanceAppService.getScheduleById(id, orgId);
    return entity ? scheduleEntityToSchema(entity) : undefined;
  }

  async createSchedule(
    data: InsertMaintenanceSchedule,
    userId?: string
  ): Promise<MaintenanceSchedule> {
    const extras = pickLegacyScheduleExtras(data);
    const command: CreateScheduleCommand = {
      orgId: data.orgId,
      equipmentId: data.equipmentId,
      scheduledDate: data.scheduledDate,
      status: data.status ?? undefined,
      priority: data.priority != null ? String(data.priority) : undefined,
      maintenanceType: data.maintenanceType,
      description: data.description ?? undefined,
      estimatedDuration: extras.estimatedDurationHours,
      assignedTo: data.assignedTo ?? undefined,
    };
    const entity = await maintenanceAppService.createSchedule(command, userId);
    return scheduleEntityToSchema(entity);
  }

  async updateSchedule(
    id: string,
    data: WidenPartial<InsertMaintenanceSchedule>,
    orgId: string,
    userId?: string
  ): Promise<MaintenanceSchedule> {
    const extras = pickLegacyScheduleExtras(data);
    const command: UpdateScheduleCommand = {
      scheduledDate: data.scheduledDate,
      status: data.status ?? undefined,
      priority: data.priority != null ? String(data.priority) : undefined,
      maintenanceType: data.maintenanceType ?? undefined,
      description: data.description ?? undefined,
      estimatedDuration: extras.estimatedDurationHours,
      assignedTo: data.assignedTo ?? undefined,
      notes: extras.notes,
    };
    const entity = await maintenanceAppService.updateSchedule(id, command, orgId, userId);
    return scheduleEntityToSchema(entity);
  }

  async deleteSchedule(id: string, orgId: string, userId?: string): Promise<void> {
    await maintenanceAppService.deleteSchedule(id, orgId, userId);
  }

  async getUpcomingSchedules(
    orgId: string,
    daysAhead: number = 30
  ): Promise<MaintenanceSchedule[]> {
    const entities = await maintenanceAppService.getUpcomingSchedules(orgId, daysAhead);
    return entities.map(scheduleEntityToSchema);
  }

  async autoScheduleForEquipment(
    equipmentId: string,
    pdmScore: number,
    userId?: string
  ): Promise<MaintenanceSchedule> {
    const entity = await maintenanceAppService.autoScheduleForEquipment(
      equipmentId,
      pdmScore,
      userId
    );
    return scheduleEntityToSchema(entity);
  }

  // ========== Maintenance Templates ==========

  async listTemplates(
    orgId?: string,
    equipmentType?: string,
    isActive?: boolean
  ): Promise<MaintenanceTemplate[]> {
    const entities = await maintenanceAppService.listTemplates(orgId, equipmentType, isActive);
    return entities.map(templateEntityToSchema);
  }

  async getTemplateById(id: string, orgId: string): Promise<MaintenanceTemplate | undefined> {
    const entity = await maintenanceAppService.getTemplateById(id, orgId);
    return entity ? templateEntityToSchema(entity) : undefined;
  }

  async createTemplate(
    data: InsertMaintenanceTemplate,
    userId?: string
  ): Promise<MaintenanceTemplate> {
    const extras = pickLegacyTemplateExtras(data);
    const command: CreateTemplateCommand = {
      orgId: data.orgId,
      name: data.name,
      equipmentType: data.equipmentType ?? undefined,
      maintenanceType: data.maintenanceType,
      description: data.description ?? undefined,
      estimatedDuration: extras.estimatedDurationHours,
      requiredParts: (data.requiredParts as string[] | null | undefined) ?? undefined,
      checklistItems: (data.checklistItems as string[] | null | undefined) ?? undefined,
      intervalDays: data.intervalDays ?? undefined,
      intervalHours: data.intervalHours ?? undefined,
      isActive: data.isActive ?? undefined,
    };
    const entity = await maintenanceAppService.createTemplate(command, userId);
    return templateEntityToSchema(entity);
  }

  async updateTemplate(
    id: string,
    data: WidenPartial<InsertMaintenanceTemplate>,
    orgId: string,
    userId?: string
  ): Promise<MaintenanceTemplate> {
    const extras = pickLegacyTemplateExtras(data);
    const command: UpdateTemplateCommand = {
      name: data.name ?? undefined,
      equipmentType: data.equipmentType ?? undefined,
      maintenanceType: data.maintenanceType ?? undefined,
      description: data.description ?? undefined,
      estimatedDuration: extras.estimatedDurationHours,
      requiredParts: (data.requiredParts as string[] | null | undefined) ?? undefined,
      checklistItems: (data.checklistItems as string[] | null | undefined) ?? undefined,
      intervalDays: data.intervalDays ?? undefined,
      intervalHours: data.intervalHours ?? undefined,
      isActive: data.isActive ?? undefined,
    };
    const entity = await maintenanceAppService.updateTemplate(id, command, orgId, userId);
    return templateEntityToSchema(entity);
  }

  async deleteTemplate(id: string, orgId: string, userId?: string): Promise<void> {
    await maintenanceAppService.deleteTemplate(id, orgId, userId);
  }
}

export const maintenanceService = new MaintenanceService();
