/**
 * Checklists - Database Storage
 */

import { eq, and, desc, sql } from "drizzle-orm";
import { randomUUID } from "node:crypto";
import { db } from "../../db-config";
import { recordAndPublish, publishEvent } from "../../sync-events";
import { maintenanceTemplates, maintenanceChecklistItems, maintenanceChecklistCompletions, workOrders, workOrderTasks, workOrderChecklists, workOrderWorklogs, type MaintenanceTemplate, type InsertMaintenanceTemplate, type MaintenanceChecklistItem, type InsertMaintenanceChecklistItem, type MaintenanceChecklistCompletion, type InsertMaintenanceChecklistCompletion, type WorkOrder, type WorkOrderTask, type InsertWorkOrderTask, type WorkOrderChecklist, type InsertWorkOrderChecklist, type WorkOrderWorklog, type InsertWorkOrderWorklog } from "@shared/schema-runtime";

export class DatabaseChecklistsStorage {
  async getMaintenanceTemplates(orgId?: string, equipmentType?: string, isActive?: boolean): Promise<MaintenanceTemplate[]> { const c = []; if (orgId) {c.push(eq(maintenanceTemplates.orgId, orgId));} if (equipmentType) {c.push(eq(maintenanceTemplates.equipmentType, equipmentType));} if (isActive !== undefined) {c.push(eq(maintenanceTemplates.isActive, isActive));} let q = db.select().from(maintenanceTemplates); if (c.length > 0) {q = q.where(and(...c));} return q.orderBy(maintenanceTemplates.name); }
  async getMaintenanceTemplate(id: string, orgId?: string): Promise<MaintenanceTemplate | undefined> { const c = [eq(maintenanceTemplates.id, id)]; if (orgId) {c.push(eq(maintenanceTemplates.orgId, orgId));} const r = await db.select().from(maintenanceTemplates).where(and(...c)); return r[0]; }
  async createMaintenanceTemplate(template: InsertMaintenanceTemplate): Promise<MaintenanceTemplate> { const [n] = await recordAndPublish(db.insert(maintenanceTemplates).values(template).returning(), "maintenance_template", "create"); return n; }
  async updateMaintenanceTemplate(id: string, template: Partial<InsertMaintenanceTemplate>, orgId?: string): Promise<MaintenanceTemplate> { const c = [eq(maintenanceTemplates.id, id)]; if (orgId) {c.push(eq(maintenanceTemplates.orgId, orgId));} const [u] = await recordAndPublish(db.update(maintenanceTemplates).set({ ...template, updatedAt: new Date() }).where(and(...c)).returning(), "maintenance_template", "update"); if (!u) {throw new Error(`Maintenance template ${id} not found`);} return u; }
  async deleteMaintenanceTemplate(id: string, orgId?: string): Promise<void> { const c = [eq(maintenanceTemplates.id, id)]; if (orgId) {c.push(eq(maintenanceTemplates.orgId, orgId));} const r = await recordAndPublish(db.delete(maintenanceTemplates).where(and(...c)).returning(), "maintenance_template", "delete"); if (r.length === 0) {throw new Error(`Maintenance template ${id} not found`);} }
  async cloneMaintenanceTemplate(id: string, newName: string, orgId?: string): Promise<MaintenanceTemplate> { return db.transaction(async (tx) => { const c = [eq(maintenanceTemplates.id, id)]; if (orgId) {c.push(eq(maintenanceTemplates.orgId, orgId));} const [o] = await tx.select().from(maintenanceTemplates).where(and(...c)); if (!o) {throw new Error(`Maintenance template ${id} not found`);} const [cloned] = await tx.insert(maintenanceTemplates).values({ ...o, id: undefined, name: newName, createdAt: new Date(), updatedAt: new Date() }).returning(); const oi = await tx.select().from(maintenanceChecklistItems).where(eq(maintenanceChecklistItems.templateId, id)).orderBy(maintenanceChecklistItems.stepNumber); if (oi.length > 0) {await tx.insert(maintenanceChecklistItems).values(oi.map(item => ({ ...item, id: undefined, templateId: cloned.id })));} await publishEvent("maintenance_template", "create", cloned); return cloned; }); }

  async getMaintenanceChecklistItems(templateId: string): Promise<MaintenanceChecklistItem[]> { return db.select().from(maintenanceChecklistItems).where(eq(maintenanceChecklistItems.templateId, templateId)).orderBy(maintenanceChecklistItems.stepNumber); }
  async getMaintenanceChecklistItem(id: string): Promise<MaintenanceChecklistItem | undefined> { const r = await db.select().from(maintenanceChecklistItems).where(eq(maintenanceChecklistItems.id, id)); return r[0]; }
  async createMaintenanceChecklistItem(item: InsertMaintenanceChecklistItem): Promise<MaintenanceChecklistItem> { const [n] = await recordAndPublish(db.insert(maintenanceChecklistItems).values(item).returning(), "maintenance_checklist_item", "create"); return n; }
  async updateMaintenanceChecklistItem(id: string, item: Partial<InsertMaintenanceChecklistItem>): Promise<MaintenanceChecklistItem> { const [u] = await recordAndPublish(db.update(maintenanceChecklistItems).set(item).where(eq(maintenanceChecklistItems.id, id)).returning(), "maintenance_checklist_item", "update"); if (!u) {throw new Error(`Maintenance checklist item ${id} not found`);} return u; }
  async deleteMaintenanceChecklistItem(id: string): Promise<void> { const r = await recordAndPublish(db.delete(maintenanceChecklistItems).where(eq(maintenanceChecklistItems.id, id)).returning(), "maintenance_checklist_item", "delete"); if (r.length === 0) {throw new Error(`Maintenance checklist item ${id} not found`);} }
  async bulkCreateChecklistItems(items: InsertMaintenanceChecklistItem[]): Promise<MaintenanceChecklistItem[]> { if (items.length === 0) {return [];} return db.transaction(async (tx) => { const created = await tx.insert(maintenanceChecklistItems).values(items).returning(); for (const item of created) {await publishEvent("maintenance_checklist_item", "create", item);} return created; }); }
  async reorderChecklistItems(templateId: string, itemIds: string[]): Promise<void> { await db.transaction(async (tx) => { for (let i = 0; i < itemIds.length; i++) {await tx.update(maintenanceChecklistItems).set({ stepNumber: i + 1 }).where(and(eq(maintenanceChecklistItems.id, itemIds[i]), eq(maintenanceChecklistItems.templateId, templateId)));} }); }

  async getMaintenanceChecklistCompletions(workOrderId: string): Promise<(MaintenanceChecklistCompletion & { description?: string; category?: string; stepNumber?: number })[]> { return db.select({ id: maintenanceChecklistCompletions.id, orgId: maintenanceChecklistCompletions.orgId, workOrderId: maintenanceChecklistCompletions.workOrderId, itemId: maintenanceChecklistCompletions.itemId, completedAt: maintenanceChecklistCompletions.completedAt, completedBy: maintenanceChecklistCompletions.completedBy, completedByName: maintenanceChecklistCompletions.completedByName, status: maintenanceChecklistCompletions.status, passed: maintenanceChecklistCompletions.passed, actualValue: maintenanceChecklistCompletions.actualValue, notes: maintenanceChecklistCompletions.notes, photoUrls: maintenanceChecklistCompletions.photoUrls, description: maintenanceChecklistItems.title, category: maintenanceChecklistItems.category, stepNumber: maintenanceChecklistItems.stepNumber }).from(maintenanceChecklistCompletions).leftJoin(maintenanceChecklistItems, eq(maintenanceChecklistCompletions.itemId, maintenanceChecklistItems.id)).where(eq(maintenanceChecklistCompletions.workOrderId, workOrderId)).orderBy(maintenanceChecklistItems.stepNumber); }
  async getMaintenanceChecklistCompletion(id: string): Promise<MaintenanceChecklistCompletion | undefined> { const r = await db.select().from(maintenanceChecklistCompletions).where(eq(maintenanceChecklistCompletions.id, id)); return r[0]; }
  async createMaintenanceChecklistCompletion(completion: InsertMaintenanceChecklistCompletion): Promise<MaintenanceChecklistCompletion> { const [n] = await recordAndPublish(db.insert(maintenanceChecklistCompletions).values(completion).returning(), "maintenance_checklist_completion", "create"); return n; }
  async updateMaintenanceChecklistCompletion(id: string, completion: Partial<InsertMaintenanceChecklistCompletion>): Promise<MaintenanceChecklistCompletion> { const [u] = await recordAndPublish(db.update(maintenanceChecklistCompletions).set(completion).where(eq(maintenanceChecklistCompletions.id, id)).returning(), "maintenance_checklist_completion", "update"); if (!u) {throw new Error(`Maintenance checklist completion ${id} not found`);} return u; }

  async completeChecklistItem(workOrderId: string, itemId: string, completedBy: string | null, completedByName: string | null, passed?: boolean | null, actualValue?: string, notes?: string | null, photoUrls?: string[]): Promise<MaintenanceChecklistCompletion> { const [existing] = await db.select().from(maintenanceChecklistCompletions).where(and(eq(maintenanceChecklistCompletions.workOrderId, workOrderId), eq(maintenanceChecklistCompletions.itemId, itemId))); const getStatus = (p: boolean | null | undefined): string => { if (p === null) {return 'pending';} if (p === true) {return 'completed';} if (p === false) {return 'failed';} return 'pending'; }; if (existing) { const isPassedProvided = passed !== undefined; const newPassed = isPassedProvided ? passed : existing.passed; const newStatus = isPassedProvided ? getStatus(newPassed) : existing.status; let newCompletedAt: Date | null; if (!isPassedProvided) {newCompletedAt = existing.completedAt;} else if (passed === null) {newCompletedAt = null;} else {newCompletedAt = new Date();} const [u] = await db.update(maintenanceChecklistCompletions).set({ completedBy: completedBy ?? existing.completedBy, completedByName: completedByName ?? existing.completedByName, passed: newPassed, status: newStatus, actualValue: actualValue ?? existing.actualValue, notes: notes === undefined ? existing.notes : notes, photoUrls: photoUrls ?? existing.photoUrls, completedAt: newCompletedAt }).where(eq(maintenanceChecklistCompletions.id, existing.id)).returning(); if (!u) {throw new Error(`Failed to update checklist completion ${existing.id}`);} await publishEvent("maintenance_checklist_completion", "update", u); return u; }  const [wo] = await db.select().from(workOrders).where(eq(workOrders.id, workOrderId)).limit(1); if (!wo) {throw new Error(`Work order ${workOrderId} not found`);} const [c] = await db.insert(maintenanceChecklistCompletions).values({ orgId: wo.orgId, workOrderId, itemId, completedBy, completedByName, passed: passed ?? null, status: getStatus(passed), actualValue: actualValue || null, notes: notes || null, photoUrls: photoUrls || null, completedAt: passed === true || passed === false ? new Date() : null }).returning(); if (!c) {throw new Error('Failed to create checklist completion');} await publishEvent("maintenance_checklist_completion", "create", c); return c;  }
  async bulkCompleteChecklistItems(workOrderId: string, completions: Array<{ itemId: string; completedBy: string; completedByName: string; passed?: boolean; actualValue?: string; notes?: string }>): Promise<MaintenanceChecklistCompletion[]> { if (completions.length === 0) {return [];} return db.transaction(async (tx) => { const created = await tx.insert(maintenanceChecklistCompletions).values(completions.map(c => ({ workOrderId, itemId: c.itemId, completedBy: c.completedBy, completedByName: c.completedByName, passed: c.passed ?? null, actualValue: c.actualValue ?? null, notes: c.notes ?? null, photoUrls: null, completedAt: new Date() }))).returning(); for (const completion of created) {await publishEvent("maintenance_checklist_completion", "create", completion);} return created; }); }
  async getChecklistCompletionProgress(workOrderId: string): Promise<{ totalItems: number; completedItems: number; pendingItems: number; skippedItems: number; failedItems: number; percentComplete: number }> { const wo = await db.select().from(workOrders).where(eq(workOrders.id, workOrderId)).limit(1); if (wo.length === 0 || !wo[0].maintenanceTemplateId) {return { totalItems: 0, completedItems: 0, pendingItems: 0, skippedItems: 0, failedItems: 0, percentComplete: 0 };} const items = await db.select().from(maintenanceChecklistItems).where(eq(maintenanceChecklistItems.templateId, wo[0].maintenanceTemplateId)); const totalItems = items.length; if (totalItems === 0) {return { totalItems: 0, completedItems: 0, pendingItems: 0, skippedItems: 0, failedItems: 0, percentComplete: 0 };} const completions = await db.select().from(maintenanceChecklistCompletions).where(eq(maintenanceChecklistCompletions.workOrderId, workOrderId)); const completedItems = completions.filter(c => c.status === 'completed' || (c.passed === true && c.completedAt !== null)).length; const failedItems = completions.filter(c => c.status === 'failed' || (c.passed === false && c.completedAt !== null)).length; const skippedItems = completions.filter(c => c.status === 'skipped').length; const pendingItems = completions.filter(c => c.status === 'pending' || (c.passed === null && c.completedAt === null)).length + (totalItems - completions.length); const reviewedItems = completedItems + failedItems; const percentComplete = totalItems > 0 ? Math.round((reviewedItems / totalItems) * 100) : 0; return { totalItems, completedItems, pendingItems, skippedItems, failedItems, percentComplete }; }
  async linkWorkOrderToTemplate(workOrderId: string, templateId: string, orgId?: string): Promise<WorkOrder> { const c = [eq(workOrders.id, workOrderId)]; if (orgId) {c.push(eq(workOrders.orgId, orgId));} const [u] = await recordAndPublish(db.update(workOrders).set({ maintenanceTemplateId: templateId, updatedAt: new Date() }).where(and(...c)).returning(), "work_order", "update"); if (!u) {throw new Error(`Work order ${workOrderId} not found`);} return u; }
  async initializeChecklistFromTemplate(workOrderId: string, templateId: string): Promise<MaintenanceChecklistCompletion[]> { return db.transaction(async (tx) => { const [template] = await tx.select().from(maintenanceTemplates).where(eq(maintenanceTemplates.id, templateId)).limit(1); if (!template) {throw new Error(`Maintenance template ${templateId} not found`);} const [wo] = await tx.select().from(workOrders).where(eq(workOrders.id, workOrderId)).limit(1); if (!wo) {throw new Error(`Work order ${workOrderId} not found`);} await tx.update(workOrders).set({ maintenanceTemplateId: templateId, updatedAt: new Date() }).where(eq(workOrders.id, workOrderId)); const items = await tx.select().from(maintenanceChecklistItems).where(eq(maintenanceChecklistItems.templateId, templateId)).orderBy(maintenanceChecklistItems.stepNumber); if (items.length === 0) {return [];} const created = await tx.insert(maintenanceChecklistCompletions).values(items.map(item => ({ orgId: wo.orgId, workOrderId, itemId: item.id, completedBy: null, completedByName: null, passed: null, actualValue: null, notes: null, photoUrls: null, completedAt: null }))).returning(); for (const c of created) {await publishEvent("maintenance_checklist_completion", "create", c);} return created; }); }

  async getWorkOrderTasks(workOrderId: string, orgId?: string): Promise<WorkOrderTask[]> { if (!orgId) { throw new Error("orgId is required for tenant isolation"); } return db.select().from(workOrderTasks).where(and(eq(workOrderTasks.workOrderId, workOrderId), eq(workOrderTasks.orgId, orgId))).orderBy(workOrderTasks.sortOrder); }
  async createWorkOrderTask(task: InsertWorkOrderTask): Promise<WorkOrderTask> { if (!task.orgId) { throw new Error("orgId is required for tenant isolation"); } const [n] = await db.insert(workOrderTasks).values({ id: randomUUID(), ...task, createdAt: new Date(), updatedAt: new Date() }).returning(); return n; }
  async updateWorkOrderTask(id: string, updates: Partial<InsertWorkOrderTask>, orgId?: string): Promise<WorkOrderTask> { if (!orgId) { throw new Error("orgId is required for tenant isolation"); } const [u] = await db.update(workOrderTasks).set({ ...updates, updatedAt: new Date() }).where(and(eq(workOrderTasks.id, id), eq(workOrderTasks.orgId, orgId))).returning(); if (!u) { throw new Error(`Work order task ${id} not found`); } return u; }
  async deleteWorkOrderTask(id: string, orgId?: string): Promise<void> { if (!orgId) { throw new Error("orgId is required for tenant isolation"); } await db.delete(workOrderTasks).where(and(eq(workOrderTasks.id, id), eq(workOrderTasks.orgId, orgId))); }

  async getWorkOrderChecklists(workOrderId?: string, orgId?: string): Promise<WorkOrderChecklist[]> { if (!orgId) { throw new Error("orgId is required for tenant isolation"); } const c = [eq(workOrderChecklists.orgId, orgId)]; if (workOrderId) { c.push(eq(workOrderChecklists.workOrderId, workOrderId)); } return db.select().from(workOrderChecklists).where(and(...c)).orderBy(workOrderChecklists.sortOrder); }
  async createWorkOrderChecklist(checklist: InsertWorkOrderChecklist): Promise<WorkOrderChecklist> { if (!checklist.orgId) { throw new Error("orgId is required for tenant isolation"); } const [n] = await db.insert(workOrderChecklists).values({ id: randomUUID(), ...checklist, createdAt: new Date(), updatedAt: new Date() }).returning(); return n; }
  async updateWorkOrderChecklist(id: string, updates: Partial<InsertWorkOrderChecklist>, orgId?: string): Promise<WorkOrderChecklist> { if (!orgId) { throw new Error("orgId is required for tenant isolation"); } const [u] = await db.update(workOrderChecklists).set({ ...updates, updatedAt: new Date() }).where(and(eq(workOrderChecklists.id, id), eq(workOrderChecklists.orgId, orgId))).returning(); if (!u) { throw new Error(`Work order checklist ${id} not found`); } return u; }
  async deleteWorkOrderChecklist(id: string, orgId?: string): Promise<void> { if (!orgId) { throw new Error("orgId is required for tenant isolation"); } await db.delete(workOrderChecklists).where(and(eq(workOrderChecklists.id, id), eq(workOrderChecklists.orgId, orgId))); }

  async getWorkOrderWorklogs(workOrderId?: string, orgId?: string): Promise<WorkOrderWorklog[]> { if (!orgId) { throw new Error("orgId is required for tenant isolation"); } const c = [eq(workOrderWorklogs.orgId, orgId)]; if (workOrderId) { c.push(eq(workOrderWorklogs.workOrderId, workOrderId)); } return db.select().from(workOrderWorklogs).where(and(...c)).orderBy(sql`${workOrderWorklogs.performedAt} DESC`); }
  async createWorkOrderWorklog(worklog: InsertWorkOrderWorklog): Promise<WorkOrderWorklog> { if (!worklog.orgId) { throw new Error("orgId is required for tenant isolation"); } const [n] = await db.insert(workOrderWorklogs).values({ id: randomUUID(), ...worklog, createdAt: new Date(), updatedAt: new Date() }).returning(); return n; }
  async updateWorkOrderWorklog(id: string, updates: Partial<InsertWorkOrderWorklog>, orgId?: string): Promise<WorkOrderWorklog> { if (!orgId) { throw new Error("orgId is required for tenant isolation"); } const [u] = await db.update(workOrderWorklogs).set({ ...updates, updatedAt: new Date() }).where(and(eq(workOrderWorklogs.id, id), eq(workOrderWorklogs.orgId, orgId))).returning(); if (!u) { throw new Error(`Work order worklog ${id} not found`); } return u; }
  async deleteWorkOrderWorklog(id: string, orgId?: string): Promise<void> { if (!orgId) { throw new Error("orgId is required for tenant isolation"); } await db.delete(workOrderWorklogs).where(and(eq(workOrderWorklogs.id, id), eq(workOrderWorklogs.orgId, orgId))); }
  async calculateWorklogCosts(workOrderId: string, orgId?: string): Promise<{ totalLaborHours: number; totalLaborCost: number }> { if (!orgId) { throw new Error("orgId is required for tenant isolation"); } const logs = await db.select().from(workOrderWorklogs).where(and(eq(workOrderWorklogs.workOrderId, workOrderId), eq(workOrderWorklogs.orgId, orgId))); let totalLaborHours = 0; let totalLaborCost = 0; for (const log of logs) { totalLaborHours += log.hoursWorked || 0; totalLaborCost += log.laborCost || 0; } return { totalLaborHours, totalLaborCost }; }
}
