import {
  Bell,
  ClipboardCheck,
  Cloud,
  FileCheck2,
  FileText,
  Package,
  RadioTower,
  Shield,
  Users,
  Wrench,
} from "lucide-react";
import type {
  FleetScreen,
  FleetVesselCard,
  MobileRole,
  QueueItem,
  TodayScreen,
} from "./mobile-readiness-model-types";
import { sortQueue } from "./mobile-readiness-navigation";

const adminQueue: QueueItem[] = [
  {
    id: "engine-room-fire",
    title: "Engine room fire alarm",
    category: "Alarm",
    reason: "Alarm - 09:36",
    detail: "Deck 2 - Engine Room",
    severity: "critical",
    owner: "Chief Engineer",
    action: "Acknowledge after inspection",
    icon: Bell,
    href: "/attention-inbox",
  },
  {
    id: "port-generator-vibration",
    title: "Port Generator vibration",
    category: "PdM Risk",
    reason: "PdM Risk - 08:48",
    detail: "GE Stamford Generator 2",
    severity: "high",
    owner: "2/E Electrical",
    action: "Inspect within 48h",
    icon: RadioTower,
    href: "/pdm-platform",
  },
  {
    id: "chief-engineer-cert",
    title: "Chief Engineer certificate expired",
    category: "Crew Blocker",
    reason: "Crew Blocker - Since 04 May",
    detail: "Certificate of Competency",
    severity: "high",
    owner: "Crewing",
    action: "Assign relief or renew certificate",
    icon: Users,
    href: "/crew-management",
  },
  {
    id: "fuel-filter-unavailable",
    title: "Fuel filter unavailable",
    category: "Inventory Blocker",
    reason: "Inventory Blocker - Since 06 May",
    detail: "Part No. 100FG-30",
    severity: "medium",
    owner: "Stores",
    action: "Reserve or reorder",
    icon: Package,
    href: "/logistics",
  },
  {
    id: "orb-overdue",
    title: "Oil Record Book overdue",
    category: "Log",
    reason: "Log - Due 08 May",
    detail: "Engine Room - ORB",
    severity: "medium",
    owner: "Chief Engineer",
    action: "Review and sign",
    icon: FileText,
    href: "/logs",
  },
  {
    id: "sync-pending",
    title: "Offline - sync pending",
    category: "Sync",
    reason: "Last synced 2 days ago",
    detail: "15 changes to upload",
    severity: "normal",
    owner: "System Admin",
    action: "Open offline outbox",
    icon: Cloud,
    href: "/offline-outbox",
  },
  {
    id: "ism-task-overdue",
    title: "ISM task overdue",
    category: "Safety",
    reason: "Safety - Due 05 May",
    detail: "Monthly Safety Review",
    severity: "medium",
    owner: "Captain",
    action: "Complete safety review",
    icon: Shield,
    href: "/logs/compliance",
  },
];

const crewQueue: QueueItem[] = [
  {
    id: "clean-bilge",
    title: "Clean bilge holding tank",
    category: "Task",
    reason: "Assigned by Chief Engineer",
    detail: "Due today 12:00",
    severity: "medium",
    owner: "You",
    action: "Open checklist",
    icon: ClipboardCheck,
    href: "/my-tasks",
  },
  {
    id: "engine-log-draft",
    title: "Daily Engine Log (Draft)",
    category: "Log",
    reason: "Your draft in progress",
    detail: "Last edited 08:30",
    severity: "normal",
    owner: "You",
    action: "Review autofill",
    icon: FileText,
    href: "/logs",
  },
  {
    id: "safety-instruction",
    title: "Safety instruction",
    category: "Safety",
    reason: "Enclosed space entry refresher",
    detail: "Read and acknowledge",
    severity: "medium",
    owner: "You",
    action: "Acknowledge",
    icon: Shield,
    href: "/logs/compliance",
  },
  {
    id: "medical-certificate",
    title: "Medical certificate expiring",
    category: "Document",
    reason: "Your medical certificate",
    detail: "Expires 28 May 2025",
    severity: "medium",
    owner: "You",
    action: "Upload renewal",
    icon: FileCheck2,
    href: "/profile",
  },
  {
    id: "offline-draft",
    title: "Offline draft",
    category: "Sync",
    reason: "Engine Log - not synced",
    detail: "Will sync when online",
    severity: "normal",
    owner: "You",
    action: "Open draft",
    icon: Cloud,
    href: "/logs",
  },
];

export function buildTodayScreen(role: MobileRole): TodayScreen {
  if (role === "crew") {
    const items = crewQueue;
    return {
      roleLabel: "Crew",
      vesselName: "MV Atlas",
      queueLabel: "My Queue",
      itemCount: items.length,
      items,
    };
  }
  if (role === "captain") {
    const items: QueueItem[] = [
      {
        id: "vessel-ready",
        title: "Vessel readiness - Good",
        category: "Readiness",
        reason: "All systems operational",
        detail: "Last check 07:15",
        severity: "normal",
        owner: "Captain",
        action: "Review readiness",
        icon: Shield,
        href: "/fleet",
      },
      {
        id: "log-signoff",
        title: "Required log sign-off",
        category: "Log",
        reason: "Oil Record Book",
        detail: "Entries to review: 2",
        severity: "medium",
        owner: "Captain",
        action: "Review and sign",
        icon: FileText,
        href: "/logs",
      },
      {
        id: "active-alert",
        title: "Active alert",
        category: "Alert",
        reason: "High temperature - No. 2 AUX Engine",
        detail: "Raised 09:22",
        severity: "high",
        owner: "Chief Engineer",
        action: "Explain risk",
        icon: Bell,
        href: "/logs/compliance",
      },
      {
        id: "crew-ready",
        title: "Crew readiness",
        category: "Crew",
        reason: "1 certificate expiring within 30 days",
        detail: "4 drills due this week",
        severity: "medium",
        owner: "Crewing",
        action: "Open crew",
        icon: Users,
        href: "/crew-management",
      },
      {
        id: "weather-log",
        title: "Weather & condition log",
        category: "Log",
        reason: "Daily report required",
        detail: "ETA next port: 18 May 06:00",
        severity: "medium",
        owner: "Deck Officer",
        action: "Review autofill",
        icon: Cloud,
        href: "/logs",
      },
    ];
    return {
      roleLabel: "Captain",
      vesselName: "MV Atlas",
      queueLabel: "Command Queue",
      itemCount: items.length,
      items,
    };
  }
  const items = adminQueue;
  return {
    roleLabel: role === "chief_engineer" ? "Chief Engineer" : "Admin",
    vesselName: "MV Atlas",
    queueLabel: "Command Queue",
    itemCount: items.length,
    items,
  };
}

const fleetVessels: FleetVesselCard[] = [
  {
    id: "mv-atlas",
    name: "MV Atlas",
    route: "Singapore -> Rotterdam",
    operationalState: "At sea",
    readiness: 78,
    pdmRiskScore: 82,
    riskTone: "high",
    nextAction: "A/E LO purifier service overdue",
    thumbnailTone: "red",
    assetId: "vessel-atlas",
    kpis: [
      { id: "readiness", label: "Readiness", value: "78%", tone: "good" },
      { id: "alarms", label: "Alarms", value: "2", tone: "critical" },
      { id: "overdue", label: "Overdue", value: "5", tone: "high" },
      { id: "crew", label: "Crew", value: "90%", tone: "good" },
      { id: "logs", label: "Logs", value: "87%", tone: "good" },
      { id: "trust", label: "Trust", value: "96%", tone: "good" },
    ],
  },
  {
    id: "mv-borealis",
    name: "MV Borealis",
    route: "Hamburg, Germany",
    operationalState: "In port",
    readiness: 63,
    pdmRiskScore: 46,
    riskTone: "medium",
    nextAction: "Bow thruster inspection due",
    thumbnailTone: "orange",
    assetId: "vessel-borealis",
    kpis: [
      { id: "readiness", label: "Readiness", value: "63%", tone: "medium" },
      { id: "alarms", label: "Alarms", value: "1", tone: "medium" },
      { id: "overdue", label: "Overdue", value: "3", tone: "high" },
      { id: "crew", label: "Crew", value: "80%", tone: "good" },
      { id: "logs", label: "Logs", value: "72%", tone: "medium" },
      { id: "trust", label: "Trust", value: "92%", tone: "good" },
    ],
  },
  {
    id: "mv-corvus",
    name: "MV Corvus",
    route: "Dubai -> Mumbai",
    operationalState: "At sea",
    readiness: 92,
    pdmRiskScore: 18,
    riskTone: "good",
    nextAction: "No critical actions",
    thumbnailTone: "blue",
    assetId: "vessel-corvus",
    kpis: [
      { id: "readiness", label: "Readiness", value: "92%", tone: "good" },
      { id: "alarms", label: "Alarms", value: "0", tone: "good" },
      { id: "overdue", label: "Overdue", value: "0", tone: "good" },
      { id: "crew", label: "Crew", value: "95%", tone: "good" },
      { id: "logs", label: "Logs", value: "92%", tone: "good" },
      { id: "trust", label: "Trust", value: "98%", tone: "good" },
    ],
  },
];

export function buildFleetScreen(): FleetScreen {
  return {
    summary: [
      { id: "vessels", label: "Vessels", value: "12", tone: "info" },
      { id: "high-risk", label: "High risk", value: "3", tone: "critical" },
      { id: "alarms", label: "Alarms", value: "5", tone: "high" },
      { id: "overdue", label: "Overdue", value: "8", tone: "medium" },
    ],
    vessels: fleetVessels,
    vesselDetail: {
      name: "MV Atlas",
      subtitle: "At sea - Singapore -> Rotterdam",
      readiness: 78,
      topPriorities: sortQueue([
        {
          id: "pump",
          title: "High pressure fuel pump",
          category: "Alarm",
          reason: "Abnormal vibration detected",
          detail: "Machinery zone",
          severity: "critical",
          owner: "Chief Engineer",
          action: "Create work order",
          icon: Bell,
          href: "/work-orders",
        },
        {
          id: "purifier",
          title: "A/E LO purifier service",
          category: "Maintenance",
          reason: "Overdue by 8 days",
          detail: "Auxiliary engine",
          severity: "high",
          owner: "2/E",
          action: "Assign technician",
          icon: Wrench,
          href: "/work-orders",
        },
        {
          id: "chief-engineer",
          title: "Chief Engineer unavailable",
          category: "Crew",
          reason: "Backfill required",
          detail: "Crew blocker",
          severity: "medium",
          owner: "Crewing",
          action: "Open crew readiness",
          icon: Users,
          href: "/crew-management",
        },
      ]),
      tiles: [
        { id: "work-orders", label: "Work orders", value: "18", tone: "high" },
        { id: "inventory", label: "Inventory blocker", value: "2", tone: "critical" },
        { id: "logs", label: "Required logs", value: "7", tone: "medium" },
        { id: "alerts", label: "Open alerts", value: "4", tone: "critical" },
      ],
      diagramModes: [
        "Side elevation",
        "Deck plan",
        "Machinery arrangement",
        "Fire safety",
        "Electrical single-line",
        "Custom",
      ],
      diagramAssetId: "diagram-side-elevation",
      selectedZone: {
        name: "Engine room",
        status: "medium",
        location: "Below main deck",
        related: "3 Alarms, 2 Logs",
        actions: ["Machinery", "Alarm", "Log", "Inspection"],
      },
    },
  };
}
