import {
  Anchor,
  AlertTriangle,
  Bell,
  BookOpen,
  BriefcaseBusiness,
  CalendarCheck,
  ClipboardCheck,
  ClipboardList,
  Cloud,
  Cog,
  FileCheck2,
  FileText,
  Folder,
  Gauge,
  Home,
  LifeBuoy,
  Package,
  RadioTower,
  Settings,
  Shield,
  Ship,
  Users,
  Wrench,
} from "lucide-react";
import type { PdmScreen, WorkScreen } from "./mobile-readiness-model-types";

export function buildPdmScreen(): PdmScreen {
  return {
    summary: [
      { id: "high-risk", label: "High Risk", value: "2", tone: "critical" },
      { id: "watch", label: "Watch", value: "1", tone: "medium" },
      { id: "normal", label: "Normal", value: "1", tone: "good" },
      { id: "offline", label: "Offline", value: "0", tone: "offline" },
    ],
    riskQueue: [
      {
        equipmentId: "port-generator",
        asset: "Port Generator",
        subtitle: "No. 1 Gen Set",
        riskState: "High Risk",
        riskScore: 62,
        signal: "Vibration rising (6 days)",
        action: "Inspect within 48h",
        sourceHealth: "Fresh",
        tone: "critical",
        icon: Gauge,
      },
      {
        equipmentId: "starboard-thruster",
        asset: "Starboard Thruster",
        subtitle: "Tunnel Thruster",
        riskState: "Watch",
        riskScore: 41,
        signal: "Vibration rising (2 days)",
        action: "Inspect within 7 days",
        sourceHealth: "Fresh",
        tone: "medium",
        icon: Cog,
      },
      {
        equipmentId: "main-engine",
        asset: "Main Engine",
        subtitle: "ME Port",
        riskState: "Normal",
        riskScore: 18,
        signal: "All parameters normal",
        action: "Continue watch",
        sourceHealth: "Fresh",
        tone: "good",
        icon: Wrench,
      },
      {
        equipmentId: "hydraulic-power-unit",
        asset: "Hydraulic Power Unit",
        subtitle: "HPU No.1",
        riskState: "Offline",
        riskScore: null,
        signal: "No data (2h 15m)",
        action: "Check sensor heartbeat",
        sourceHealth: "Offline",
        tone: "offline",
        icon: Gauge,
      },
    ],
    assetCase: {
      asset: "Port Generator",
      riskScore: 62,
      trend: "Rising",
      status: "In Service",
      sourceHealth: "Good",
      dataFreshness: "Fresh (2m)",
      evidenceSections: [
        {
          title: "Why at Risk?",
          body: "Vibration overall trending up for 6 days and exceeding warning threshold. Bearing condition degradation detected on DE side.",
        },
        {
          title: "Latest Abnormal Readings",
          body: "Vibration DE 7.8 mm/s, vibration NDE 5.2 mm/s, bearing temp 86.4 C.",
        },
        {
          title: "Recommended Next Action",
          body: "Inspect DE bearing and coupling alignment. Collect oil sample if not done in last 250 hrs.",
        },
        {
          title: "Linked Work Order",
          body: "WO-2025-1187 open, due 19 May 2025.",
        },
        {
          title: "Parts Likely Needed",
          body: "6316 C3 bearing, coupling element, Loctite 243.",
        },
        {
          title: "Responsible",
          body: "2/E Electrical / Chief Engineer.",
        },
        {
          title: "Evidence & Notes",
          body: "Telemetry packet, operator notes, and sensor health attached.",
        },
      ],
    },
    telemetryAdvanced: {
      trust: "Good",
      confidence: 92,
      lastUpdate: "2m ago (09:39)",
      rawReadingsAvailable: true,
      sensorHealthCount: 4,
      chartAssetId: "telemetry-risk-chart",
    },
  };
}

export function buildWorkScreen(): WorkScreen {
  return {
    filters: [
      { id: "all", label: "All", value: "23", tone: "info" },
      { id: "my-work", label: "My Work", value: "7", tone: "info" },
      { id: "overdue", label: "Overdue", value: "4", tone: "high" },
      { id: "watch", label: "Watch", value: "6", tone: "medium" },
    ],
    stageChips: [
      { id: "intake", label: "Intake", value: "3", tone: "normal" },
      { id: "triage", label: "Triage", value: "2", tone: "normal" },
      { id: "assigned", label: "Assigned", value: "5", tone: "normal" },
      { id: "in-progress", label: "In Progress", value: "4", tone: "info" },
      { id: "blocked", label: "Blocked", value: "2", tone: "high" },
    ],
    queue: sortQueue([
      {
        id: "sr-1258",
        title: "M/V Atlantic Trader",
        category: "SR-1258 - In Progress",
        reason: "Main Engine > Fuel System",
        detail: "Fuel leak at port side filter housing",
        severity: "high",
        owner: "J. Ramirez (Tech)",
        action: "Blocked by PdM Alert ALRT-8847",
        icon: Wrench,
        href: "/work-orders/sr-1258",
      },
      {
        id: "so-4481",
        title: "M/V Ocean Pioneer",
        category: "SO-4481 - Awaiting Parts",
        reason: "HVAC > Compressor #2",
        detail: "Compressor not cooling",
        severity: "medium",
        owner: "R. Patel (Tech)",
        action: "Part needed PRT-7732",
        icon: Package,
        href: "/work-orders/so-4481",
      },
      {
        id: "sr-1266",
        title: "M/V Seafarer",
        category: "SR-1266 - Awaiting Crew",
        reason: "Deck > Crane #1",
        detail: "Crane remote intermittent",
        severity: "normal",
        owner: "Deck Crew",
        action: "Crew needed 1 rigger",
        icon: Users,
        href: "/work-orders/sr-1266",
      },
      {
        id: "so-4476",
        title: "M/V Northern Light",
        category: "SO-4476 - Assigned",
        reason: "Generator #2 > Electrical",
        detail: "Frequent overload trips",
        severity: "high",
        owner: "A. Kim (Tech)",
        action: "PdM Alert ALRT-7712",
        icon: AlertTriangle,
        href: "/work-orders/so-4476",
      },
      {
        id: "sr-1271",
        title: "M/V Atlantic Trader",
        category: "SR-1271 - Awaiting Approval",
        reason: "Bilge System > Pump #1",
        detail: "Approval required before dispatch",
        severity: "normal",
        owner: "C. Wilson",
        action: "Approval required",
        icon: ClipboardCheck,
        href: "/work-orders/sr-1271",
      },
    ]),
    execution: {
      orderNumber: "SO-4481",
      vesselName: "M/V Ocean Pioneer",
      assetId: "vessel-borealis",
      title: "HVAC - Compressor #2",
      description: "Compressor not cooling",
      priority: "Medium",
      due: "Tomorrow 09:00",
      syncState: "Syncing...",
      technician: "R. Patel (Tech)",
      checklistProgress: "4 / 6",
      percentComplete: 67,
      checklist: [
        { label: "Isolate and lock out compressor", state: "done" },
        { label: "Verify no pressure and temperature normal", state: "done", telemetry: "Fresh" },
        { label: "Inspect compressor oil level and condition", state: "open" },
        { label: "Check cooling fan and motor operation", state: "done" },
        { label: "Test run and confirm cooling performance", state: "open" },
        { label: "Remove lockout and return to service", state: "open" },
      ],
      requiredPhotos: 3,
      partsUsed: "Filter, Oil - 51860 / P/N FLT-51860",
      labor: "2.50 hrs",
      photoAssetIds: ["work-compressor", "work-motor", "work-gauge"],
      offlineDraftAction: "Save Draft Offline",
      primaryAction: "Complete Work",
      notes: "Found oil level slightly low. Topped up. Fan belt tension adjusted. Running test.",
    },
  };
}
