import type { RoleTemplateConfig } from "./types";

export const ADMIN_ROLE_TEMPLATES: RoleTemplateConfig[] = [
  {
    name: "company_admin",
    displayName: "Company Administrator",
    description: "Full access to all features and settings",
    department: "admin",
    hierarchyLevel: 1,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "vessels", action: "create" },
      { resource: "vessels", action: "edit" },
      { resource: "vessels", action: "delete" },
      { resource: "vessels", action: "export" },
      { resource: "equipment", action: "view" },
      { resource: "equipment", action: "create" },
      { resource: "equipment", action: "edit" },
      { resource: "equipment", action: "delete" },
      { resource: "equipment", action: "manage_config" },
      { resource: "sensors", action: "view" },
      { resource: "sensors", action: "create" },
      { resource: "sensors", action: "edit" },
      { resource: "sensors", action: "delete" },
      { resource: "sensors", action: "manage_config" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "create" },
      { resource: "work_orders", action: "edit" },
      { resource: "work_orders", action: "delete" },
      { resource: "work_orders", action: "assign" },
      { resource: "work_orders", action: "complete" },
      { resource: "work_orders", action: "manage_parts" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "maintenance_schedules", action: "create" },
      { resource: "maintenance_schedules", action: "edit" },
      { resource: "maintenance_schedules", action: "delete" },
      { resource: "maintenance_schedules", action: "approve" },
      { resource: "maintenance_templates", action: "view" },
      { resource: "maintenance_templates", action: "create" },
      { resource: "maintenance_templates", action: "edit" },
      { resource: "maintenance_templates", action: "delete" },
      { resource: "alerts", action: "view" },
      { resource: "alerts", action: "edit" },
      { resource: "alerts", action: "delete" },
      { resource: "alerts", action: "manage_config" },
      { resource: "crew_members", action: "view" },
      { resource: "crew_members", action: "create" },
      { resource: "crew_members", action: "edit" },
      { resource: "crew_members", action: "delete" },
      { resource: "crew_members", action: "export" },
      { resource: "crew_schedules", action: "view" },
      { resource: "crew_schedules", action: "create" },
      { resource: "crew_schedules", action: "edit" },
      { resource: "crew_schedules", action: "delete" },
      { resource: "crew_schedules", action: "assign" },
      { resource: "rest_hours", action: "view" },
      { resource: "rest_hours", action: "create" },
      { resource: "rest_hours", action: "edit" },
      { resource: "rest_hours", action: "delete" },
      { resource: "rest_hours", action: "approve" },
      { resource: "rest_hours", action: "sign_off" },
      { resource: "certifications", action: "view" },
      { resource: "certifications", action: "create" },
      { resource: "certifications", action: "edit" },
      { resource: "certifications", action: "delete" },
      { resource: "safety_alarms", action: "view" },
      { resource: "safety_alarms", action: "trigger" },
      { resource: "safety_alarms", action: "clear" },
      { resource: "safety_alarms", action: "acknowledge" },
      { resource: "safety_alarms", action: "export" },
      { resource: "safety_alarm_types", action: "view" },
      { resource: "safety_alarm_types", action: "manage" },
      { resource: "leave_requests", action: "view" },
      { resource: "leave_requests", action: "create" },
      { resource: "leave_requests", action: "edit" },
      { resource: "leave_requests", action: "delete" },
      { resource: "leave_requests", action: "approve" },
      { resource: "inventory", action: "view" },
      { resource: "inventory", action: "create" },
      { resource: "inventory", action: "edit" },
      { resource: "inventory", action: "delete" },
      { resource: "inventory", action: "export" },
      { resource: "inventory_movements", action: "view" },
      { resource: "inventory_movements", action: "create" },
      { resource: "inventory_movements", action: "edit" },
      { resource: "inventory_movements", action: "delete" },
      { resource: "purchase_requests", action: "view" },
      { resource: "purchase_requests", action: "create" },
      { resource: "purchase_requests", action: "edit" },
      { resource: "purchase_requests", action: "delete" },
      { resource: "purchase_requests", action: "approve" },
      { resource: "suppliers", action: "view" },
      { resource: "suppliers", action: "create" },
      { resource: "suppliers", action: "edit" },
      { resource: "suppliers", action: "delete" },
      { resource: "deck_logbook", action: "view" },
      { resource: "deck_logbook", action: "create" },
      { resource: "deck_logbook", action: "edit" },
      { resource: "deck_logbook", action: "delete" },
      { resource: "deck_logbook", action: "sign_off" },
      { resource: "deck_logbook", action: "export" },
      { resource: "engine_logbook", action: "view" },
      { resource: "engine_logbook", action: "create" },
      { resource: "engine_logbook", action: "edit" },
      { resource: "engine_logbook", action: "delete" },
      { resource: "engine_logbook", action: "sign_off" },
      { resource: "engine_logbook", action: "export" },
      { resource: "compliance_findings", action: "view" },
      { resource: "compliance_findings", action: "create" },
      { resource: "compliance_findings", action: "edit" },
      { resource: "compliance_findings", action: "delete" },
      { resource: "compliance_findings", action: "approve" },
      { resource: "compliance_reports", action: "view" },
      { resource: "compliance_reports", action: "create" },
      { resource: "compliance_reports", action: "export" },
      { resource: "analytics_dashboard", action: "view" },
      { resource: "analytics_dashboard", action: "export" },
      { resource: "predictive_maintenance", action: "view" },
      { resource: "predictive_maintenance", action: "manage_config" },
      { resource: "predictive_maintenance", action: "override" },
      { resource: "condition_monitoring", action: "view" },
      { resource: "condition_monitoring", action: "create" },
      { resource: "condition_monitoring", action: "edit" },
      { resource: "condition_monitoring", action: "delete" },
      { resource: "ai_reports", action: "view" },
      { resource: "ai_reports", action: "create" },
      { resource: "ai_reports", action: "export" },
      { resource: "cost_savings", action: "view" },
      { resource: "cost_savings", action: "export" },
      { resource: "organization_settings", action: "view" },
      { resource: "organization_settings", action: "edit" },
      { resource: "user_management", action: "view" },
      { resource: "user_management", action: "create" },
      { resource: "user_management", action: "edit" },
      { resource: "user_management", action: "delete" },
      { resource: "permission_management", action: "view" },
      { resource: "permission_management", action: "create" },
      { resource: "permission_management", action: "edit" },
      { resource: "permission_management", action: "delete" },
      { resource: "system_settings", action: "view" },
      { resource: "system_settings", action: "edit" },
      { resource: "system_settings", action: "manage_config" },
      { resource: "integrations", action: "view" },
      { resource: "integrations", action: "create" },
      { resource: "integrations", action: "edit" },
      { resource: "integrations", action: "delete" },
      { resource: "integrations", action: "manage_config" },
      { resource: "audit_log", action: "view" },
      { resource: "audit_log", action: "export" },
    ],
  },

  {
    name: "super_admin",
    displayName: "Super Administrator",
    description:
      "Unrestricted system-level administrator for all hubs, roles, access, and safety controls",
    department: "admin",
    hierarchyLevel: 1,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "crew_members", action: "view" },
      { resource: "crew_members", action: "create" },
      { resource: "crew_members", action: "edit" },
      { resource: "crew_members", action: "delete" },
      { resource: "crew_members", action: "export" },
      { resource: "safety_alarms", action: "view" },
      { resource: "safety_alarms", action: "trigger" },
      { resource: "safety_alarms", action: "clear" },
      { resource: "safety_alarms", action: "acknowledge" },
      { resource: "safety_alarms", action: "export" },
      { resource: "safety_alarm_types", action: "view" },
      { resource: "safety_alarm_types", action: "manage" },
      { resource: "organization_settings", action: "view" },
      { resource: "organization_settings", action: "edit" },
      { resource: "user_management", action: "view" },
      { resource: "user_management", action: "create" },
      { resource: "user_management", action: "edit" },
      { resource: "user_management", action: "delete" },
      { resource: "permission_management", action: "view" },
      { resource: "permission_management", action: "create" },
      { resource: "permission_management", action: "edit" },
      { resource: "permission_management", action: "delete" },
      { resource: "system_settings", action: "view" },
      { resource: "system_settings", action: "edit" },
      { resource: "system_settings", action: "manage_config" },
      { resource: "audit_log", action: "view" },
      { resource: "audit_log", action: "export" },
      { resource: "predictive_maintenance", action: "view" },
      { resource: "predictive_maintenance", action: "manage_config" },
      { resource: "predictive_maintenance", action: "override" },
    ],
  },

  {
    name: "admin",
    displayName: "Administrator",
    description: "Administrative role for crew, access, settings, and operational configuration",
    department: "admin",
    hierarchyLevel: 5,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "crew_members", action: "view" },
      { resource: "crew_members", action: "create" },
      { resource: "crew_members", action: "edit" },
      { resource: "crew_members", action: "delete" },
      { resource: "crew_members", action: "export" },
      { resource: "safety_alarms", action: "view" },
      { resource: "safety_alarms", action: "trigger" },
      { resource: "safety_alarms", action: "clear" },
      { resource: "safety_alarms", action: "acknowledge" },
      { resource: "safety_alarms", action: "export" },
      { resource: "safety_alarm_types", action: "view" },
      { resource: "safety_alarm_types", action: "manage" },
      { resource: "organization_settings", action: "view" },
      { resource: "organization_settings", action: "edit" },
      { resource: "user_management", action: "view" },
      { resource: "user_management", action: "create" },
      { resource: "user_management", action: "edit" },
      { resource: "permission_management", action: "view" },
      { resource: "permission_management", action: "edit" },
      { resource: "audit_log", action: "view" },
      { resource: "predictive_maintenance", action: "view" },
      { resource: "predictive_maintenance", action: "manage_config" },
      { resource: "predictive_maintenance", action: "override" },
    ],
  },

  {
    name: "fleet_manager",
    displayName: "Fleet Manager",
    description: "Fleet-level operational manager with broad vessel, crew, and safety visibility",
    department: "admin",
    hierarchyLevel: 8,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "equipment", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "assign" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "maintenance_schedules", action: "approve" },
      { resource: "crew_members", action: "view" },
      { resource: "crew_members", action: "edit" },
      { resource: "crew_schedules", action: "view" },
      { resource: "crew_schedules", action: "assign" },
      { resource: "safety_alarms", action: "view" },
      { resource: "safety_alarms", action: "trigger" },
      { resource: "safety_alarms", action: "clear" },
      { resource: "safety_alarms", action: "acknowledge" },
      { resource: "safety_alarms", action: "export" },
      { resource: "safety_alarm_types", action: "view" },
      { resource: "analytics_dashboard", action: "view" },
      { resource: "audit_log", action: "view" },
    ],
  },
];
