import type { RoleTemplateConfig } from "./types";

export const BRIDGE_ROLE_TEMPLATES: RoleTemplateConfig[] = [
{
    name: "captain",
    displayName: "Captain / Master",
    description: "Vessel master with command authority",
    department: "bridge",
    hierarchyLevel: 10,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "vessels", action: "edit" },
      { resource: "equipment", action: "view" },
      { resource: "equipment", action: "edit" },
      { resource: "sensors", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "create" },
      { resource: "work_orders", action: "edit" },
      { resource: "work_orders", action: "assign" },
      { resource: "work_orders", action: "complete" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "maintenance_schedules", action: "approve" },
      { resource: "alerts", action: "view" },
      { resource: "alerts", action: "edit" },
      { resource: "crew_members", action: "view" },
      { resource: "crew_members", action: "edit" },
      { resource: "crew_schedules", action: "view" },
      { resource: "crew_schedules", action: "create" },
      { resource: "crew_schedules", action: "edit" },
      { resource: "crew_schedules", action: "assign" },
      { resource: "rest_hours", action: "view" },
      { resource: "rest_hours", action: "approve" },
      { resource: "rest_hours", action: "sign_off" },
      { resource: "certifications", action: "view" },
      { resource: "safety_alarms", action: "view" },
      { resource: "safety_alarms", action: "trigger" },
      { resource: "safety_alarms", action: "clear" },
      { resource: "safety_alarms", action: "acknowledge" },
      { resource: "safety_alarms", action: "export" },
      { resource: "safety_alarm_types", action: "view" },
      { resource: "leave_requests", action: "view" },
      { resource: "leave_requests", action: "approve" },
      { resource: "inventory", action: "view" },
      { resource: "purchase_requests", action: "view" },
      { resource: "purchase_requests", action: "approve" },
      { resource: "deck_logbook", action: "view" },
      { resource: "deck_logbook", action: "create" },
      { resource: "deck_logbook", action: "edit" },
      { resource: "deck_logbook", action: "sign_off" },
      { resource: "deck_logbook", action: "export" },
      { resource: "engine_logbook", action: "view" },
      { resource: "engine_logbook", action: "sign_off" },
      { resource: "compliance_findings", action: "view" },
      { resource: "compliance_findings", action: "approve" },
      { resource: "compliance_reports", action: "view" },
      { resource: "compliance_reports", action: "create" },
      { resource: "compliance_reports", action: "export" },
      { resource: "analytics_dashboard", action: "view" },
      { resource: "analytics_dashboard", action: "export" },
      { resource: "predictive_maintenance", action: "view" },
      { resource: "predictive_maintenance", action: "override" },
      { resource: "condition_monitoring", action: "view" },
      { resource: "ai_reports", action: "view" },
      { resource: "ai_reports", action: "create" },
      { resource: "cost_savings", action: "view" },
      { resource: "audit_log", action: "view" },
    ],
  },

{
    name: "vessel_master",
    displayName: "Vessel Master",
    description: "Command authority for vessel operations, crew readiness, and safety alarms",
    department: "bridge",
    hierarchyLevel: 10,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "vessels", action: "edit" },
      { resource: "equipment", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "create" },
      { resource: "work_orders", action: "edit" },
      { resource: "work_orders", action: "assign" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "maintenance_schedules", action: "approve" },
      { resource: "crew_members", action: "view" },
      { resource: "crew_members", action: "edit" },
      { resource: "crew_schedules", action: "view" },
      { resource: "crew_schedules", action: "assign" },
      { resource: "rest_hours", action: "view" },
      { resource: "rest_hours", action: "approve" },
      { resource: "safety_alarms", action: "view" },
      { resource: "safety_alarms", action: "trigger" },
      { resource: "safety_alarms", action: "clear" },
      { resource: "safety_alarms", action: "acknowledge" },
      { resource: "safety_alarm_types", action: "view" },
      { resource: "deck_logbook", action: "view" },
      { resource: "deck_logbook", action: "sign_off" },
      { resource: "engine_logbook", action: "view" },
      { resource: "compliance_reports", action: "view" },
      { resource: "analytics_dashboard", action: "view" },
    ],
  },

{
    name: "chief_officer",
    displayName: "Chief Officer / First Mate",
    description: "Second in command, deck operations",
    department: "bridge",
    hierarchyLevel: 20,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "equipment", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "create" },
      { resource: "work_orders", action: "edit" },
      { resource: "work_orders", action: "assign" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "alerts", action: "view" },
      { resource: "crew_members", action: "view" },
      { resource: "crew_schedules", action: "view" },
      { resource: "crew_schedules", action: "create" },
      { resource: "crew_schedules", action: "edit" },
      { resource: "rest_hours", action: "view" },
      { resource: "rest_hours", action: "create" },
      { resource: "rest_hours", action: "edit" },
      { resource: "certifications", action: "view" },
      { resource: "safety_alarms", action: "view" },
      { resource: "safety_alarms", action: "trigger" },
      { resource: "safety_alarms", action: "clear" },
      { resource: "safety_alarms", action: "acknowledge" },
      { resource: "safety_alarms", action: "export" },
      { resource: "safety_alarm_types", action: "view" },
      { resource: "leave_requests", action: "view" },
      { resource: "leave_requests", action: "create" },
      { resource: "inventory", action: "view" },
      { resource: "deck_logbook", action: "view" },
      { resource: "deck_logbook", action: "create" },
      { resource: "deck_logbook", action: "edit" },
      { resource: "engine_logbook", action: "view" },
      { resource: "compliance_findings", action: "view" },
      { resource: "compliance_findings", action: "create" },
      { resource: "analytics_dashboard", action: "view" },
      { resource: "predictive_maintenance", action: "view" },
      { resource: "condition_monitoring", action: "view" },
    ],
  },
];
