import type { RoleTemplateConfig } from "./types";

export const OPERATIONS_ROLE_TEMPLATES: RoleTemplateConfig[] = [
  {
    name: "chief_engineer",
    displayName: "Chief Engineer",
    description: "Head of engine department with full maintenance authority",
    department: "engine",
    hierarchyLevel: 15,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "equipment", action: "view" },
      { resource: "equipment", action: "create" },
      { resource: "equipment", action: "edit" },
      { resource: "equipment", action: "manage_config" },
      { resource: "sensors", action: "view" },
      { resource: "sensors", action: "create" },
      { resource: "sensors", action: "edit" },
      { resource: "sensors", action: "manage_config" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "create" },
      { resource: "work_orders", action: "edit" },
      { resource: "work_orders", action: "delete" },
      { resource: "work_orders", action: "assign" },
      { resource: "work_orders", action: "complete" },
      { resource: "work_orders", action: "manage_parts" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "maintenance_schedules", action: "create" },
      { resource: "maintenance_schedules", action: "edit" },
      { resource: "maintenance_schedules", action: "approve" },
      { resource: "maintenance_templates", action: "view" },
      { resource: "maintenance_templates", action: "create" },
      { resource: "maintenance_templates", action: "edit" },
      { resource: "alerts", action: "view" },
      { resource: "alerts", action: "edit" },
      { resource: "alerts", action: "manage_config" },
      { resource: "crew_members", action: "view" },
      { resource: "crew_schedules", action: "view" },
      { resource: "crew_schedules", action: "create" },
      { resource: "crew_schedules", action: "edit" },
      { resource: "crew_schedules", action: "assign" },
      { resource: "rest_hours", action: "view" },
      { resource: "rest_hours", action: "create" },
      { resource: "rest_hours", action: "edit" },
      { resource: "rest_hours", action: "approve" },
      { resource: "inventory", action: "view" },
      { resource: "inventory", action: "create" },
      { resource: "inventory", action: "edit" },
      { resource: "inventory_movements", action: "view" },
      { resource: "inventory_movements", action: "create" },
      { resource: "purchase_requests", action: "view" },
      { resource: "purchase_requests", action: "create" },
      { resource: "purchase_requests", action: "approve" },
      { resource: "suppliers", action: "view" },
      { resource: "engine_logbook", action: "view" },
      { resource: "engine_logbook", action: "create" },
      { resource: "engine_logbook", action: "edit" },
      { resource: "engine_logbook", action: "sign_off" },
      { resource: "engine_logbook", action: "export" },
      { resource: "deck_logbook", action: "view" },
      { resource: "compliance_findings", action: "view" },
      { resource: "compliance_findings", action: "create" },
      { resource: "analytics_dashboard", action: "view" },
      { resource: "analytics_dashboard", action: "export" },
      { resource: "predictive_maintenance", action: "view" },
      { resource: "predictive_maintenance", action: "manage_config" },
      { resource: "condition_monitoring", action: "view" },
      { resource: "condition_monitoring", action: "create" },
      { resource: "condition_monitoring", action: "edit" },
      { resource: "ai_reports", action: "view" },
      { resource: "ai_reports", action: "create" },
      { resource: "cost_savings", action: "view" },
    ],
  },

  {
    name: "second_engineer",
    displayName: "Second Engineer",
    description: "Deputy engine department head with maintenance execution authority",
    department: "engine",
    hierarchyLevel: 25,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "equipment", action: "view" },
      { resource: "equipment", action: "edit" },
      { resource: "sensors", action: "view" },
      { resource: "sensors", action: "edit" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "create" },
      { resource: "work_orders", action: "edit" },
      { resource: "work_orders", action: "complete" },
      { resource: "work_orders", action: "manage_parts" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "maintenance_schedules", action: "create" },
      { resource: "maintenance_schedules", action: "edit" },
      { resource: "maintenance_templates", action: "view" },
      { resource: "alerts", action: "view" },
      { resource: "alerts", action: "edit" },
      { resource: "crew_schedules", action: "view" },
      { resource: "rest_hours", action: "view" },
      { resource: "rest_hours", action: "create" },
      { resource: "inventory", action: "view" },
      { resource: "inventory", action: "edit" },
      { resource: "inventory_movements", action: "view" },
      { resource: "inventory_movements", action: "create" },
      { resource: "purchase_requests", action: "view" },
      { resource: "purchase_requests", action: "create" },
      { resource: "engine_logbook", action: "view" },
      { resource: "engine_logbook", action: "create" },
      { resource: "engine_logbook", action: "edit" },
      { resource: "analytics_dashboard", action: "view" },
      { resource: "predictive_maintenance", action: "view" },
      { resource: "condition_monitoring", action: "view" },
      { resource: "condition_monitoring", action: "create" },
    ],
  },

  {
    name: "third_engineer",
    displayName: "Third Engineer",
    description: "Junior engineer with limited maintenance authority",
    department: "engine",
    hierarchyLevel: 35,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "equipment", action: "view" },
      { resource: "sensors", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "create" },
      { resource: "work_orders", action: "edit" },
      { resource: "work_orders", action: "complete" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "alerts", action: "view" },
      { resource: "inventory", action: "view" },
      { resource: "inventory_movements", action: "view" },
      { resource: "engine_logbook", action: "view" },
      { resource: "engine_logbook", action: "create" },
      { resource: "analytics_dashboard", action: "view" },
      { resource: "condition_monitoring", action: "view" },
    ],
  },

  {
    name: "bosun",
    displayName: "Bosun",
    description: "Senior deck rating, supervises deck crew",
    department: "deck",
    hierarchyLevel: 40,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "equipment", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "create" },
      { resource: "work_orders", action: "complete" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "alerts", action: "view" },
      { resource: "crew_schedules", action: "view" },
      { resource: "rest_hours", action: "view" },
      { resource: "rest_hours", action: "create" },
      { resource: "inventory", action: "view" },
      { resource: "deck_logbook", action: "view" },
      { resource: "deck_logbook", action: "create" },
    ],
  },

  {
    name: "able_seaman",
    displayName: "Able Seaman (AB)",
    description: "Qualified deck rating",
    department: "deck",
    hierarchyLevel: 50,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "equipment", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "complete" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "alerts", action: "view" },
      { resource: "rest_hours", action: "view" },
      { resource: "rest_hours", action: "create" },
      { resource: "deck_logbook", action: "view" },
    ],
  },

  {
    name: "oiler",
    displayName: "Oiler / Motorman",
    description: "Engine room rating",
    department: "engine",
    hierarchyLevel: 50,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "equipment", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "complete" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "alerts", action: "view" },
      { resource: "rest_hours", action: "view" },
      { resource: "rest_hours", action: "create" },
      { resource: "engine_logbook", action: "view" },
      { resource: "condition_monitoring", action: "view" },
    ],
  },

  {
    name: "technician",
    displayName: "Technician",
    description:
      "Maintenance technician focused on assigned work, equipment checks, and task closeout",
    department: "engine",
    hierarchyLevel: 55,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "equipment", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "edit" },
      { resource: "work_orders", action: "complete" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "alerts", action: "view" },
      { resource: "inventory", action: "view" },
      { resource: "condition_monitoring", action: "view" },
    ],
  },

  {
    name: "supervisor",
    displayName: "Supervisor",
    description:
      "Department supervisor for crew coordination, assigned work, and readiness follow-up",
    department: "deck",
    hierarchyLevel: 45,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "equipment", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "assign" },
      { resource: "work_orders", action: "complete" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "crew_members", action: "view" },
      { resource: "crew_schedules", action: "view" },
      { resource: "crew_schedules", action: "assign" },
      { resource: "safety_alarms", action: "view" },
      { resource: "safety_alarms", action: "acknowledge" },
      { resource: "alerts", action: "view" },
    ],
  },

  {
    name: "safety_officer",
    displayName: "Safety Officer",
    description: "Safety lead for alarms, acknowledgements, bulletins, and compliance follow-up",
    department: "deck",
    hierarchyLevel: 30,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "crew_members", action: "view" },
      { resource: "safety_alarms", action: "view" },
      { resource: "safety_alarms", action: "trigger" },
      { resource: "safety_alarms", action: "clear" },
      { resource: "safety_alarms", action: "acknowledge" },
      { resource: "safety_alarms", action: "export" },
      { resource: "safety_alarm_types", action: "view" },
      { resource: "compliance_findings", action: "view" },
      { resource: "compliance_findings", action: "create" },
      { resource: "compliance_reports", action: "view" },
      { resource: "audit_log", action: "view" },
    ],
  },

  {
    name: "logistics_user",
    displayName: "Logistics User",
    description:
      "Logistics and procurement user for inventory, purchase requests, and vessel supplies",
    department: "admin",
    hierarchyLevel: 60,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "inventory", action: "view" },
      { resource: "inventory", action: "create" },
      { resource: "inventory", action: "edit" },
      { resource: "inventory_movements", action: "view" },
      { resource: "inventory_movements", action: "create" },
      { resource: "purchase_requests", action: "view" },
      { resource: "purchase_requests", action: "create" },
      { resource: "suppliers", action: "view" },
      { resource: "suppliers", action: "create" },
      { resource: "work_orders", action: "view" },
    ],
  },

  {
    name: "crew_member",
    displayName: "Crew Member",
    description:
      "Standard crew portal user for vessel assignment, watch status, safety, and assigned tasks",
    department: "deck",
    hierarchyLevel: 80,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "work_orders", action: "complete" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "alerts", action: "view" },
      { resource: "rest_hours", action: "view" },
      { resource: "rest_hours", action: "create" },
      { resource: "safety_alarms", action: "view" },
      { resource: "safety_alarms", action: "acknowledge" },
    ],
  },

  {
    name: "viewer",
    displayName: "Viewer",
    description: "Read-only access to non-sensitive data",
    department: "admin",
    hierarchyLevel: 100,
    permissions: [
      { resource: "dashboard", action: "view" },
      { resource: "vessels", action: "view" },
      { resource: "equipment", action: "view" },
      { resource: "work_orders", action: "view" },
      { resource: "maintenance_schedules", action: "view" },
      { resource: "alerts", action: "view" },
      { resource: "crew_members", action: "view" },
      { resource: "inventory", action: "view" },
      { resource: "analytics_dashboard", action: "view" },
    ],
  },
];
