/**
 * Maintenance Templates - Database Storage
 */

import { eq, and, desc, gte, lte, sql } from "drizzle-orm";
import { db } from "../../db-config";
import { getWebSocketServer } from "../../websocket-server";
import { recordAndPublish } from "../../sync-events";
import { maintenanceTemplates, maintenanceChecklistItems, workOrderChecklists, pdmScoreLogs, maintenanceSchedules, type MaintenanceTemplate, type InsertMaintenanceTemplate, type MaintenanceChecklistItem, type InsertMaintenanceChecklistItem, type WorkOrderChecklist, type InsertWorkOrderChecklist, type PdmScoreLog, type InsertPdmScoreLog, type MaintenanceSchedule, type InsertMaintenanceSchedule } from "@shared/schema-runtime";

export class DatabaseMaintenanceTemplatesStorage {
  async getMaintenanceTemplates(orgId?: string, equipmentType?: string, isActive?: boolean): Promise<MaintenanceTemplate[]> { const c = []; if (orgId) {c.push(eq(maintenanceTemplates.orgId, orgId));} if (equipmentType) {c.push(eq(maintenanceTemplates.equipmentType, equipmentType));} if (isActive !== undefined) {c.push(eq(maintenanceTemplates.isActive, isActive));} let q = db.select().from(maintenanceTemplates); if (c.length > 0) {q = q.where(and(...c));} return q.orderBy(maintenanceTemplates.name); }
  async getMaintenanceTemplate(id: string, orgId?: string): Promise<MaintenanceTemplate | undefined> { const c = [eq(maintenanceTemplates.id, id)]; if (orgId) {c.push(eq(maintenanceTemplates.orgId, orgId));} const r = await db.select().from(maintenanceTemplates).where(and(...c)); return r[0]; }
  async createMaintenanceTemplate(template: InsertMaintenanceTemplate): Promise<MaintenanceTemplate> { const [n] = await db.insert(maintenanceTemplates).values(template).returning(); await recordAndPublish("maintenance_template", n.id, "create", n); return n; }
  async updateMaintenanceTemplate(id: string, template: Partial<InsertMaintenanceTemplate>, orgId?: string): Promise<MaintenanceTemplate> { const c = [eq(maintenanceTemplates.id, id)]; if (orgId) {c.push(eq(maintenanceTemplates.orgId, orgId));} const [u] = await db.update(maintenanceTemplates).set({ ...template, updatedAt: new Date() }).where(and(...c)).returning(); if (!u) {throw new Error(`Maintenance template ${id} not found`);} await recordAndPublish("maintenance_template", u.id, "update", u); return u; }
  async deleteMaintenanceTemplate(id: string, orgId?: string): Promise<void> { const c = [eq(maintenanceTemplates.id, id)]; if (orgId) {c.push(eq(maintenanceTemplates.orgId, orgId));} const r = await db.delete(maintenanceTemplates).where(and(...c)).returning(); if (r.length === 0) {throw new Error(`Maintenance template ${id} not found`);} await recordAndPublish("maintenance_template", id, "delete", r[0]); }
  async cloneMaintenanceTemplate(id: string, newName: string, orgId?: string): Promise<MaintenanceTemplate> { return db.transaction(async (tx) => { const c = [eq(maintenanceTemplates.id, id)]; if (orgId) {c.push(eq(maintenanceTemplates.orgId, orgId));} const [o] = await tx.select().from(maintenanceTemplates).where(and(...c)); if (!o) {throw new Error(`Maintenance template ${id} not found`);} const [cloned] = await tx.insert(maintenanceTemplates).values({ ...o, id: undefined, name: newName, createdAt: new Date(), updatedAt: new Date() }).returning(); const oi = await tx.select().from(maintenanceChecklistItems).where(eq(maintenanceChecklistItems.templateId, id)).orderBy(maintenanceChecklistItems.sortOrder); if (oi.length > 0) {await tx.insert(maintenanceChecklistItems).values(oi.map(item => ({ ...item, id: undefined, templateId: cloned.id, createdAt: new Date(), updatedAt: new Date() })));} return cloned; }); }
  async searchMaintenanceTemplates(orgId: string, searchTerm: string): Promise<MaintenanceTemplate[]> { const all = await db.select().from(maintenanceTemplates).where(eq(maintenanceTemplates.orgId, orgId)); const term = searchTerm.toLowerCase(); return all.filter(t => t.name.toLowerCase().includes(term) || (t.description && t.description.toLowerCase().includes(term))); }

  async getChecklistItems(templateId: string, orgId?: string): Promise<MaintenanceChecklistItem[]> { return db.select().from(maintenanceChecklistItems).where(eq(maintenanceChecklistItems.templateId, templateId)).orderBy(maintenanceChecklistItems.sortOrder); }
  async getChecklistItem(id: string, orgId?: string): Promise<MaintenanceChecklistItem | undefined> { const [r] = await db.select().from(maintenanceChecklistItems).where(eq(maintenanceChecklistItems.id, id)); return r; }
  async createChecklistItem(item: InsertMaintenanceChecklistItem): Promise<MaintenanceChecklistItem> { const [n] = await db.insert(maintenanceChecklistItems).values(item).returning(); await recordAndPublish("checklist_item", n.id, "create", n); return n; }
  async updateChecklistItem(id: string, item: Partial<InsertMaintenanceChecklistItem>, orgId?: string): Promise<MaintenanceChecklistItem> { const [u] = await db.update(maintenanceChecklistItems).set({ ...item, updatedAt: new Date() }).where(eq(maintenanceChecklistItems.id, id)).returning(); if (!u) {throw new Error(`Checklist item ${id} not found`);} await recordAndPublish("checklist_item", u.id, "update", u); return u; }
  async deleteChecklistItem(id: string, orgId?: string): Promise<void> { const r = await db.delete(maintenanceChecklistItems).where(eq(maintenanceChecklistItems.id, id)).returning(); if (r.length === 0) {throw new Error(`Checklist item ${id} not found`);} await recordAndPublish("checklist_item", id, "delete", r[0]); }
  async reorderChecklistItems(templateId: string, itemIds: string[]): Promise<MaintenanceChecklistItem[]> { return db.transaction(async (tx) => { for (let i = 0; i < itemIds.length; i++) {await tx.update(maintenanceChecklistItems).set({ sortOrder: i, updatedAt: new Date() }).where(eq(maintenanceChecklistItems.id, itemIds[i]));} return tx.select().from(maintenanceChecklistItems).where(eq(maintenanceChecklistItems.templateId, templateId)).orderBy(maintenanceChecklistItems.sortOrder); }); }
  async bulkCreateChecklistItems(items: InsertMaintenanceChecklistItem[]): Promise<MaintenanceChecklistItem[]> { if (items.length === 0) {return [];} return db.insert(maintenanceChecklistItems).values(items).returning(); }
  async bulkUpdateChecklistItems(updates: { id: string; data: Partial<InsertMaintenanceChecklistItem> }[]): Promise<MaintenanceChecklistItem[]> { const u: MaintenanceChecklistItem[] = []; for (const { id, data } of updates) { const [item] = await db.update(maintenanceChecklistItems).set({ ...data, updatedAt: new Date() }).where(eq(maintenanceChecklistItems.id, id)).returning(); if (item) {u.push(item);} } return u; }

  async getWorkOrderChecklists(workOrderId: string, orgId?: string): Promise<WorkOrderChecklist[]> { return db.select().from(workOrderChecklists).where(eq(workOrderChecklists.workOrderId, workOrderId)).orderBy(workOrderChecklists.sortOrder); }
  async getWorkOrderChecklist(id: string, orgId?: string): Promise<WorkOrderChecklist | undefined> { const [r] = await db.select().from(workOrderChecklists).where(eq(workOrderChecklists.id, id)); return r; }
  async createWorkOrderChecklist(checklist: InsertWorkOrderChecklist): Promise<WorkOrderChecklist> { const [n] = await db.insert(workOrderChecklists).values(checklist).returning(); return n; }
  async updateWorkOrderChecklist(id: string, checklist: Partial<InsertWorkOrderChecklist>, orgId?: string): Promise<WorkOrderChecklist> { const [u] = await db.update(workOrderChecklists).set({ ...checklist, updatedAt: new Date() }).where(eq(workOrderChecklists.id, id)).returning(); if (!u) {throw new Error(`Work order checklist ${id} not found`);} return u; }
  async deleteWorkOrderChecklist(id: string, orgId?: string): Promise<void> { const r = await db.delete(workOrderChecklists).where(eq(workOrderChecklists.id, id)).returning(); if (r.length === 0) {throw new Error(`Work order checklist ${id} not found`);} }
  async completeChecklistItem(id: string, completedBy: string, notes?: string, measurements?: Record<string, any>): Promise<WorkOrderChecklist> { const [u] = await db.update(workOrderChecklists).set({ isCompleted: true, completedBy, completedAt: new Date(), notes, measurements, updatedAt: new Date() }).where(eq(workOrderChecklists.id, id)).returning(); if (!u) {throw new Error(`Work order checklist ${id} not found`);} return u; }
  async uncompleteChecklistItem(id: string): Promise<WorkOrderChecklist> { const [u] = await db.update(workOrderChecklists).set({ isCompleted: false, completedBy: null, completedAt: null, updatedAt: new Date() }).where(eq(workOrderChecklists.id, id)).returning(); if (!u) {throw new Error(`Work order checklist ${id} not found`);} return u; }
  async getChecklistProgress(workOrderId: string): Promise<{ total: number; completed: number; percentage: number }> { const items = await db.select().from(workOrderChecklists).where(eq(workOrderChecklists.workOrderId, workOrderId)); const total = items.length; const completed = items.filter(i => i.isCompleted).length; return { total, completed, percentage: total > 0 ? Math.round((completed / total) * 100) : 0 }; }
  async applyTemplateToWorkOrder(workOrderId: string, templateId: string, orgId?: string): Promise<WorkOrderChecklist[]> { const items = await db.select().from(maintenanceChecklistItems).where(eq(maintenanceChecklistItems.templateId, templateId)).orderBy(maintenanceChecklistItems.sortOrder); if (items.length === 0) {return [];} const woItems = items.map(item => ({ workOrderId, checklistItemId: item.id, description: item.description, category: item.category, isRequired: item.isRequired, sortOrder: item.sortOrder, estimatedMinutes: item.estimatedMinutes, safetyPrecautions: item.safetyPrecautions, tools: item.tools, parts: item.parts, instructions: item.instructions, measurementConfig: item.measurementConfig, isCompleted: false })); return db.insert(workOrderChecklists).values(woItems).returning(); }

  async getPdmScoreLogs(equipmentId: string, startDate?: Date, endDate?: Date): Promise<PdmScoreLog[]> { const c = [eq(pdmScoreLogs.equipmentId, equipmentId)]; if (startDate) {c.push(gte(pdmScoreLogs.timestamp, startDate));} if (endDate) {c.push(lte(pdmScoreLogs.timestamp, endDate));} return db.select().from(pdmScoreLogs).where(and(...c)).orderBy(sql`${pdmScoreLogs.timestamp} DESC`); }
  async createPdmScoreLog(log: InsertPdmScoreLog): Promise<PdmScoreLog> { const [n] = await db.insert(pdmScoreLogs).values(log).returning(); return n; }
  async getLatestPdmScore(equipmentId: string): Promise<PdmScoreLog | undefined> { const [r] = await db.select().from(pdmScoreLogs).where(eq(pdmScoreLogs.equipmentId, equipmentId)).orderBy(sql`${pdmScoreLogs.timestamp} DESC`).limit(1); return r; }
  async getFleetPdmScores(orgId: string): Promise<PdmScoreLog[]> { return db.select().from(pdmScoreLogs).where(eq(pdmScoreLogs.orgId, orgId)).orderBy(sql`${pdmScoreLogs.timestamp} DESC`); }

  async getMaintenanceSchedules(equipmentId?: string, status?: string): Promise<MaintenanceSchedule[]> { const c = []; if (equipmentId) {c.push(eq(maintenanceSchedules.equipmentId, equipmentId));} if (status) {c.push(eq(maintenanceSchedules.status, status));} let q = db.select().from(maintenanceSchedules); if (c.length > 0) {q = q.where(and(...c));} return q.orderBy(maintenanceSchedules.scheduledDate); }
  async createMaintenanceSchedule(schedule: InsertMaintenanceSchedule): Promise<MaintenanceSchedule> { const [n] = await db.insert(maintenanceSchedules).values(schedule).returning(); const ws = getWebSocketServer(); ws?.broadcastMaintenanceScheduleChange("create", n); return n; }
  async updateMaintenanceSchedule(id: string, updates: Partial<InsertMaintenanceSchedule>): Promise<MaintenanceSchedule> { const [u] = await db.update(maintenanceSchedules).set({ ...updates, updatedAt: new Date() }).where(eq(maintenanceSchedules.id, id)).returning(); if (!u) {throw new Error(`Maintenance schedule ${id} not found`);} const ws = getWebSocketServer(); ws?.broadcastMaintenanceScheduleChange("update", u); return u; }
  async deleteMaintenanceSchedule(id: string): Promise<void> { const toDelete = await db.select().from(maintenanceSchedules).where(eq(maintenanceSchedules.id, id)).limit(1); const r = await db.delete(maintenanceSchedules).where(eq(maintenanceSchedules.id, id)); if (r.rowCount === 0) {throw new Error(`Maintenance schedule ${id} not found`);} const ws = getWebSocketServer(); if (toDelete.length > 0) {ws?.broadcastMaintenanceScheduleChange("delete", { id: toDelete[0].id });} }
  async getUpcomingSchedules(days: number = 30): Promise<MaintenanceSchedule[]> { const cutoff = new Date(); cutoff.setDate(cutoff.getDate() + days); return db.select().from(maintenanceSchedules).where(and(gte(maintenanceSchedules.scheduledDate, new Date()), lte(maintenanceSchedules.scheduledDate, cutoff), eq(maintenanceSchedules.status, "scheduled"))).orderBy(maintenanceSchedules.scheduledDate); }
}
