// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-layouts/CardFeed.tsx": () =>
    import("../components/mockups/home-layouts/CardFeed.tsx"),
  "./components/mockups/home-layouts/DashboardGrid.tsx": () =>
    import("../components/mockups/home-layouts/DashboardGrid.tsx"),
  "./components/mockups/home-layouts/SidebarSplit.tsx": () =>
    import("../components/mockups/home-layouts/SidebarSplit.tsx"),
};
