import type { RoleDashboardConfig, TaskSourceKey, WidgetKey } from "./role-dashboard";

interface RoleDashboardDefaultsDeps {
  DASHBOARD_WIDGETS: readonly WidgetKey[];
  TASK_SOURCES: readonly TaskSourceKey[];
}

export function createDefaultRoleDashboardConfigs({
  DASHBOARD_WIDGETS,
  TASK_SOURCES,
}: RoleDashboardDefaultsDeps): Record<string, RoleDashboardConfig> {
  return {
    super_admin: {
      widgets: [...DASHBOARD_WIDGETS],
      taskSources: [...TASK_SOURCES],
      visibilityScope: "fleet",
      quickActions: ["create_work_order", "view_analytics", "manage_roles"],
      filters: {},
      highImpactQuestions: {},
    },
    system_admin: {
      widgets: [...DASHBOARD_WIDGETS],
      taskSources: [...TASK_SOURCES],
      visibilityScope: "fleet",
      quickActions: ["create_work_order", "view_analytics", "manage_roles"],
      filters: {},
      highImpactQuestions: {},
    },
    company_admin: {
      widgets: [...DASHBOARD_WIDGETS],
      taskSources: [...TASK_SOURCES],
      visibilityScope: "fleet",
      quickActions: ["create_work_order", "view_analytics", "manage_roles"],
      filters: {},
      highImpactQuestions: {},
    },
    admin: {
      widgets: [...DASHBOARD_WIDGETS],
      taskSources: [...TASK_SOURCES],
      visibilityScope: "fleet",
      quickActions: ["create_work_order", "view_analytics"],
      filters: {},
      highImpactQuestions: {},
    },
    fleet_manager: {
      widgets: [...DASHBOARD_WIDGETS],
      taskSources: ["work_orders", "maintenance_schedules", "alerts"],
      visibilityScope: "fleet",
      quickActions: ["create_work_order", "view_analytics"],
      filters: {},
      highImpactQuestions: {},
    },
    captain: {
      widgets: [...DASHBOARD_WIDGETS],
      taskSources: ["work_orders", "maintenance_schedules", "alerts", "crew_tasks"],
      visibilityScope: "vessel",
      quickActions: ["create_work_order"],
      filters: {},
      highImpactQuestions: {},
    },
    supervisor: {
      widgets: [
        "current_vessel",
        "shift_status",
        "safety_status",
        "user_tasks",
        "active_alerts",
        "upcoming_maintenance",
      ],
      taskSources: ["work_orders", "maintenance_schedules", "alerts", "crew_tasks"],
      visibilityScope: "department",
      quickActions: ["create_work_order"],
      filters: {},
      highImpactQuestions: {},
    },
    chief_engineer: {
      widgets: [
        "current_vessel",
        "shift_status",
        "safety_status",
        "user_tasks",
        "active_alerts",
        "upcoming_maintenance",
      ],
      taskSources: [
        "work_orders",
        "maintenance_schedules",
        "alerts",
        "purchase_requests",
        "crew_tasks",
      ],
      visibilityScope: "vessel",
      quickActions: ["create_work_order"],
      filters: {},
      highImpactQuestions: {},
    },
    technician: {
      widgets: [
        "current_vessel",
        "shift_status",
        "user_tasks",
        "upcoming_maintenance",
        "active_alerts",
      ],
      taskSources: ["work_orders", "maintenance_schedules", "crew_tasks"],
      visibilityScope: "self",
      quickActions: ["complete_work_order"],
      filters: {},
      highImpactQuestions: {},
    },
    vessel_master: {
      widgets: [...DASHBOARD_WIDGETS],
      taskSources: [
        "work_orders",
        "maintenance_schedules",
        "alerts",
        "service_requests",
        "crew_tasks",
      ],
      visibilityScope: "vessel",
      quickActions: [],
      filters: {},
      highImpactQuestions: {},
    },
    crew_member: {
      widgets: ["current_vessel", "shift_status", "safety_status", "user_tasks", "safety_notices"],
      taskSources: ["work_orders", "crew_tasks"],
      visibilityScope: "self",
      quickActions: [],
      filters: {},
      highImpactQuestions: {},
    },
    logistics_user: {
      widgets: ["current_vessel", "user_tasks", "upcoming_maintenance"],
      taskSources: ["purchase_requests", "service_requests", "reservations"],
      visibilityScope: "department",
      quickActions: [],
      filters: {},
      highImpactQuestions: {},
    },
    procurement_user: {
      widgets: ["current_vessel", "user_tasks"],
      taskSources: ["purchase_requests"],
      visibilityScope: "fleet",
      quickActions: [],
      filters: {},
      highImpactQuestions: {},
    },
    safety_officer: {
      widgets: ["current_vessel", "safety_status", "safety_notices", "active_alerts", "user_tasks"],
      taskSources: ["alerts", "insights"],
      visibilityScope: "fleet",
      quickActions: [],
      filters: {},
      highImpactQuestions: {},
    },
    maintenance_planner: {
      widgets: ["current_vessel", "user_tasks", "upcoming_maintenance", "active_alerts"],
      taskSources: ["work_orders", "maintenance_schedules", "insights"],
      visibilityScope: "fleet",
      quickActions: ["create_work_order"],
      filters: {},
      highImpactQuestions: {},
    },
    viewer: {
      widgets: ["current_vessel", "safety_status", "safety_notices", "active_alerts"],
      taskSources: [],
      visibilityScope: "self",
      quickActions: [],
      filters: {},
      highImpactQuestions: {},
    },
  };
}
