import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Plus, Trash2, Users, ShipWheel } from "lucide-react";
import { useCrewManagementData, type Crew } from "@/features/crew";

interface VesselOption { id: string; name: string; }
interface SkillItem { id: string; name: string; category?: string; maxLevel: number; description?: string; }

export function CrewAdmin() {
  const { crewForm, setCrewForm, crewSkillForm, setCrewSkillForm, editingSkillId, crew, vessels, skillsCatalog, isLoading, skillForm, createCrewMutation, addSkillMutation, createSkillMutation, updateSkillMutation, deleteSkillMutation, capitalizeNames, handleSubmitCrew, handleAddSkill, onSubmitSkill, handleEditSkill, handleCancelEdit, maritimeRanks, availableRanks, skillCategories, commonSkills } = useCrewManagementData();
  
  // Handler to update both rank display name and roleId when rank is selected
  const handleRankChange = (displayName: string) => {
    const selectedRank = availableRanks.find(r => r.displayName === displayName);
    setCrewForm({ 
      ...crewForm, 
      rank: displayName,
      roleId: selectedRank?.id || ""
    });
  };

  if (isLoading) {return <div className="p-6">Loading crew data...</div>;}

  return (
    <div className="space-y-6">
      <Tabs defaultValue="crew" className="w-full">
        <TabsList className="grid w-full grid-cols-3"><TabsTrigger value="crew" data-testid="tab-crew">Crew Members</TabsTrigger><TabsTrigger value="skills" data-testid="tab-skills">Skills Catalog</TabsTrigger><TabsTrigger value="assign" data-testid="tab-assign">Assign Skills</TabsTrigger></TabsList>

        <TabsContent value="crew" className="space-y-6">
          <div className="grid gap-6 lg:grid-cols-2">
            <Card><CardHeader><CardTitle className="flex items-center gap-2"><Plus className="h-5 w-5" />Add Crew Member</CardTitle><CardDescription>Register new crew members with their maritime qualifications</CardDescription></CardHeader><CardContent><form onSubmit={handleSubmitCrew} className="space-y-4"><div className="grid grid-cols-2 gap-4"><div><Label htmlFor="crew-name">Name</Label><Input id="crew-name" data-testid="input-crew-name" placeholder="Full name" value={crewForm.name} onChange={(e) => setCrewForm({ ...crewForm, name: capitalizeNames(e.target.value) })} required /></div><div><Label htmlFor="crew-rank">Rank</Label><Select value={crewForm.rank} onValueChange={handleRankChange}><SelectTrigger data-testid="select-crew-rank"><SelectValue /></SelectTrigger><SelectContent>{maritimeRanks.map((rank) => <SelectItem key={rank} value={rank}>{rank}</SelectItem>)}</SelectContent></Select></div></div><div className="grid grid-cols-3 gap-4"><div><Label htmlFor="vessel-id">Vessel</Label><Select value={crewForm.vesselId || "_unassigned"} onValueChange={(value) => setCrewForm({ ...crewForm, vesselId: value === "_unassigned" ? "" : value })}><SelectTrigger data-testid="select-vessel-id"><SelectValue placeholder="Select vessel" /></SelectTrigger><SelectContent><SelectItem value="_unassigned">Unassigned</SelectItem>{(vessels as VesselOption[]).filter((v) => v.id).map((vessel) => <SelectItem key={vessel.id} value={vessel.id}>{vessel.name}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="max-hours">Max hrs/7d</Label><Input id="max-hours" data-testid="input-max-hours" type="number" min="40" max="84" value={crewForm.maxHours7d} onChange={(e) => setCrewForm({ ...crewForm, maxHours7d: Number(e.target.value) })} /></div><div><Label htmlFor="min-rest">Min rest (h)</Label><Input id="min-rest" data-testid="input-min-rest" type="number" min="6" max="12" value={crewForm.minRestH} onChange={(e) => setCrewForm({ ...crewForm, minRestH: Number(e.target.value) })} /></div></div><Button type="submit" data-testid="button-create-crew" disabled={createCrewMutation.isPending} className="w-full">{createCrewMutation.isPending ? "Creating..." : "Add Crew Member"}</Button></form></CardContent></Card>
            <Card><CardHeader><CardTitle>Add Skills</CardTitle><CardDescription>Assign maritime skills and certifications to crew members</CardDescription></CardHeader><CardContent className="space-y-4"><div><Label htmlFor="skill-crew">Select Crew Member</Label><Select value={crewSkillForm.crewId} onValueChange={(value) => setCrewSkillForm({ ...crewSkillForm, crewId: value })}><SelectTrigger data-testid="select-skill-crew"><SelectValue placeholder="Choose crew member" /></SelectTrigger><SelectContent>{crew.map((member: Crew) => <SelectItem key={member.id} value={member.id}>{member.name} ({member.rank})</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="skill-name">Skill</Label><Select value={crewSkillForm.skill} onValueChange={(value) => setCrewSkillForm({ ...crewSkillForm, skill: value })}><SelectTrigger data-testid="select-skill-name"><SelectValue placeholder="Choose skill" /></SelectTrigger><SelectContent>{commonSkills.map((skill) => <SelectItem key={skill} value={skill}>{skill.replace("_", " ").replace(/\b\w/g, (l) => l.toUpperCase())}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="skill-level">Level (1-5)</Label><Select value={crewSkillForm.level.toString()} onValueChange={(value) => setCrewSkillForm({ ...crewSkillForm, level: Number(value) })}><SelectTrigger data-testid="select-skill-level"><SelectValue /></SelectTrigger><SelectContent>{[1, 2, 3, 4, 5].map((level) => <SelectItem key={level} value={level.toString()}>Level {level} {level === 1 ? "(Basic)" : level === 5 ? "(Expert)" : ""}</SelectItem>)}</SelectContent></Select></div><Button onClick={handleAddSkill} data-testid="button-add-skill" disabled={addSkillMutation.isPending} className="w-full">{addSkillMutation.isPending ? "Adding..." : "Add Skill"}</Button></CardContent></Card>
          </div>
          <Card><CardHeader><CardTitle>Crew Roster</CardTitle><CardDescription>Complete crew manifest with qualifications and assignments</CardDescription></CardHeader><CardContent><div className="grid gap-4">{crew.map((member: Crew) => <div key={member.id} className="border rounded-lg p-4"><div className="flex items-start justify-between"><div className="space-y-2"><div className="flex items-center gap-3"><h3 className="font-semibold text-lg" data-testid={`text-crew-name-${member.id}`}>{member.name}</h3><Badge variant="outline" data-testid={`badge-rank-${member.id}`}>{member.rank}</Badge>{member.vesselId && <Badge variant="secondary" className="flex items-center gap-1"><ShipWheel className="h-3 w-3" />{member.vesselId}</Badge>}</div><div className="flex gap-6 text-sm text-muted-foreground"><span>Max: {member.maxHours7d}h/week</span><span>Rest: {member.minRestH}h minimum</span><span className={member.active ? "text-green-600" : "text-red-600"}>{member.active ? "Active" : "Inactive"}</span></div>{member.skills.length > 0 && <div className="flex flex-wrap gap-1">{member.skills.map((skill) => <Badge key={skill} variant="outline" className="text-xs">{skill.replace("_", " ")}</Badge>)}</div>}</div></div></div>)}{crew.length === 0 && <div className="text-center text-muted-foreground py-8">No crew members registered yet. Add your first crew member above.</div>}</div></CardContent></Card>
        </TabsContent>

        <TabsContent value="skills" className="space-y-6">
          <div className="grid gap-6 lg:grid-cols-2">
            <Card><CardHeader><CardTitle className="flex items-center gap-2"><Plus className="h-5 w-5" />{editingSkillId ? "Edit Skill" : "Add Skill"}</CardTitle><CardDescription>Manage the master catalog of skills that can be assigned to crew members</CardDescription></CardHeader><CardContent><Form {...skillForm}><form onSubmit={skillForm.handleSubmit(onSubmitSkill)} className="space-y-4"><FormField control={skillForm.control} name="name" render={({ field }) => <FormItem><FormLabel>Skill Name</FormLabel><FormControl><Input {...field} data-testid="input-skill-name" placeholder="e.g. Watchkeeping" /></FormControl><FormMessage /></FormItem>} /><div className="grid grid-cols-2 gap-4"><FormField control={skillForm.control} name="category" render={({ field }) => <FormItem><FormLabel>Category</FormLabel><Select value={field.value} onValueChange={field.onChange}><FormControl><SelectTrigger data-testid="select-skill-category"><SelectValue placeholder="Select category" /></SelectTrigger></FormControl><SelectContent>{skillCategories.map((category) => <SelectItem key={category} value={category}>{category}</SelectItem>)}</SelectContent></Select><FormMessage /></FormItem>} /><FormField control={skillForm.control} name="maxLevel" render={({ field }) => <FormItem><FormLabel>Max Level</FormLabel><Select value={field.value?.toString()} onValueChange={(value) => field.onChange(Number.parseInt(value))}><FormControl><SelectTrigger data-testid="select-skill-max-level"><SelectValue /></SelectTrigger></FormControl><SelectContent>{[1, 2, 3, 4, 5].map((level) => <SelectItem key={level} value={level.toString()}>Level {level}</SelectItem>)}</SelectContent></Select><FormMessage /></FormItem>} /></div><FormField control={skillForm.control} name="description" render={({ field }) => <FormItem><FormLabel>Description</FormLabel><FormControl><Input {...field} data-testid="input-skill-description" placeholder="Detailed description of the skill" /></FormControl><FormMessage /></FormItem>} /><div className="flex gap-2"><Button type="submit" data-testid="button-save-skill" disabled={createSkillMutation.isPending || updateSkillMutation.isPending}>{editingSkillId ? "Update Skill" : "Add Skill"}</Button>{editingSkillId && <Button type="button" variant="outline" onClick={handleCancelEdit} data-testid="button-cancel-edit">Cancel</Button>}</div></form></Form></CardContent></Card>
            <Card><CardHeader><CardTitle>Skills Catalog ({skillsCatalog.length})</CardTitle><CardDescription>Available skills in the system</CardDescription></CardHeader><CardContent><div className="space-y-4 max-h-96 overflow-y-auto">{(skillsCatalog as SkillItem[]).map((skill) => <div key={skill.id} className="border rounded p-3"><div className="space-y-2"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><h4 className="font-medium" data-testid={`text-skill-name-${skill.id}`}>{skill.name}</h4>{skill.category && <Badge variant="outline">{skill.category}</Badge>}<Badge variant="secondary">Max Level {skill.maxLevel}</Badge></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => handleEditSkill(skill)} data-testid={`button-edit-skill-${skill.id}`}>Edit</Button><Button size="sm" variant="destructive" onClick={() => deleteSkillMutation.mutate(skill.id)} disabled={deleteSkillMutation.isPending} data-testid={`button-delete-skill-${skill.id}`}><Trash2 className="h-4 w-4" /></Button></div></div>{skill.description && <p className="text-sm text-muted-foreground">{skill.description}</p>}</div></div>)}{skillsCatalog.length === 0 && <div className="text-center text-muted-foreground py-8">No skills in catalog yet. Add your first skill above.</div>}</div></CardContent></Card>
          </div>
        </TabsContent>

        <TabsContent value="assign" className="space-y-6">
          <Card><CardHeader><CardTitle className="flex items-center gap-2"><Plus className="h-5 w-5" />Assign Skills to Crew</CardTitle><CardDescription>Assign skills from the catalog to crew members with proficiency levels</CardDescription></CardHeader><CardContent><div className="grid grid-cols-4 gap-4"><div><Label htmlFor="assign-crew">Crew Member</Label><Select value={crewSkillForm.crewId} onValueChange={(value) => setCrewSkillForm({ ...crewSkillForm, crewId: value })}><SelectTrigger data-testid="select-assign-crew"><SelectValue placeholder="Select crew member" /></SelectTrigger><SelectContent>{crew.map((member) => <SelectItem key={member.id} value={member.id}>{member.name} ({member.rank})</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="assign-skill">Skill</Label><Select value={crewSkillForm.skill} onValueChange={(value) => setCrewSkillForm({ ...crewSkillForm, skill: value })}><SelectTrigger data-testid="select-assign-skill"><SelectValue placeholder="Select skill" /></SelectTrigger><SelectContent>{(skillsCatalog as SkillItem[]).map((skill) => <SelectItem key={skill.id} value={skill.name}>{skill.name} {skill.category && `(${skill.category})`}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="assign-level">Proficiency Level</Label><Select value={crewSkillForm.level.toString()} onValueChange={(value) => setCrewSkillForm({ ...crewSkillForm, level: Number.parseInt(value) })}><SelectTrigger data-testid="select-assign-level"><SelectValue /></SelectTrigger><SelectContent>{[1, 2, 3, 4, 5].map((level) => <SelectItem key={level} value={level.toString()}>Level {level}</SelectItem>)}</SelectContent></Select></div><div className="flex items-end"><Button onClick={handleAddSkill} disabled={!crewSkillForm.crewId || !crewSkillForm.skill || addSkillMutation.isPending} data-testid="button-assign-skill">Assign Skill</Button></div></div></CardContent></Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
