import { createLogger } from "../lib/structured-logger";
import { dbCrewStorage, dbSchedulerStorage } from "../repositories";

const logger = createLogger("Scheduler:SchedulerController");

/**
 * Apply a scheduler run - promotes a draft/completed run to "published" status
 * so its assignments become active. Wraps dbSchedulerStorage.publishSchedulerRun
 * with org-scoped ownership validation.
 */
export async function applySchedule(
  runId: string,
  orgId: string
): Promise<{ runId: string; status: string }> {
  const run = await dbSchedulerStorage.getSchedulerRun(runId);
  if (!run || run.orgId !== orgId) {
    throw new Error(`Scheduler run ${runId} not found for org ${orgId}`);
  }
  const updated = await dbSchedulerStorage.publishSchedulerRun(runId, orgId);
  logger.info(`[Scheduler] Applied/published scheduler run ${runId} for org ${orgId}`);
  return { runId: updated.id, status: updated.status ?? "published" };
}

/**
 * Cancel a scheduler run - marks the run as cancelled and removes any
 * draft assignments that were generated from it. Org-scoped.
 */
export async function cancelScheduleRun(
  runId: string,
  orgId: string
): Promise<{ runId: string; status: string; deletedAssignments: number }> {
  const run = await dbSchedulerStorage.getSchedulerRun(runId);
  if (!run || run.orgId !== orgId) {
    throw new Error(`Scheduler run ${runId} not found for org ${orgId}`);
  }
  const deletedAssignments = await dbCrewStorage.deleteCrewAssignmentsByRunId(orgId, runId);
  const updated = await dbSchedulerStorage.cancelSchedulerRun(runId);
  logger.info(
    `[Scheduler] Cancelled scheduler run ${runId}: removed ${deletedAssignments} draft assignments`
  );
  return { runId: updated.id, status: updated.status ?? "cancelled", deletedAssignments };
}

/**
 * Clear all scheduler run history for an organization
 * Also cleans up associated crew assignments, schedule_assignments, and schedule_unfilled rows
 */
export async function clearSchedulerRunHistory(orgId: string): Promise<{ deleted: number }> {
  const runs = await dbSchedulerStorage.getSchedulerRuns(orgId);
  let totalAssignmentsDeleted = 0;

  // Clean up child tables BEFORE deleting parent runs
  // 1. Delete crew assignments generated by each run
  for (const run of runs) {
    const deleted = await dbCrewStorage.deleteCrewAssignmentsByRunId(orgId, run.id);
    totalAssignmentsDeleted += deleted;
  }

  // 2. Delete schedule_assignments and schedule_unfilled that reference runs
  await dbSchedulerStorage.deleteScheduleAssignmentsByOrg(orgId);
  await dbSchedulerStorage.deleteScheduleUnfilledByOrg(orgId);

  // 3. Finally delete the scheduler runs themselves
  await dbSchedulerStorage.deleteSchedulerRuns(orgId);

  logger.info(
    `[Scheduler] Cleared scheduler run history: deleted ${runs.length} runs and ${totalAssignmentsDeleted} associated crew assignments for org ${orgId}`
  );

  return { deleted: runs.length };
}
