/**
 * Engine Log Auto-Fill - Telemetry Mappings
 * Maps telemetry sensor types to engine log fields
 */

import type { InsertEngineLogHourly, InsertEngineLogGenerator } from "./types.js";

export const DEFAULT_TELEMETRY_MAPPING: Record<string, keyof InsertEngineLogHourly> = {
  me_rpm: "meRpm",
  main_engine_rpm: "meRpm",
  engine_rpm: "meRpm",
  me_load: "meLoad",
  main_engine_load: "meLoad",
  engine_load: "meLoad",
  me_fuel_rack: "meFuelRackPosition",
  fuel_rack_position: "meFuelRackPosition",
  me_exhaust_temp_port: "meExhaustTempPort",
  exhaust_temp_port: "meExhaustTempPort",
  me_exhaust_temp_stbd: "meExhaustTempStbd",
  exhaust_temp_stbd: "meExhaustTempStbd",
  me_scav_air_press: "meScavAirPress",
  scavenge_air_pressure: "meScavAirPress",
  me_scav_air_temp: "meScavAirTemp",
  scavenge_air_temp: "meScavAirTemp",
  me_tc_rpm: "meTurbochargerRpm",
  turbocharger_rpm: "meTurbochargerRpm",
  tc_rpm: "meTurbochargerRpm",
  me_tc_exhaust_temp: "meTurbochargerExhaustTemp",
  turbocharger_exhaust_temp: "meTurbochargerExhaustTemp",
  me_coolant_temp_in: "meCoolantTempIn",
  coolant_inlet_temp: "meCoolantTempIn",
  me_coolant_temp_out: "meCoolantTempOut",
  coolant_outlet_temp: "meCoolantTempOut",
  me_lub_oil_press: "meLubOilPress",
  lub_oil_pressure: "meLubOilPress",
  lube_oil_press: "meLubOilPress",
  me_lub_oil_temp: "meLubOilTemp",
  lub_oil_temp: "meLubOilTemp",
  lube_oil_temp: "meLubOilTemp",
  me_fuel_oil_press: "meFuelOilPress",
  fuel_oil_pressure: "meFuelOilPress",
  me_fuel_oil_temp: "meFuelOilTemp",
  fuel_oil_temp: "meFuelOilTemp",
  me_fuel_oil_visc: "meFuelOilViscosity",
  fuel_oil_viscosity: "meFuelOilViscosity",
  sw_cooling_temp: "seaWaterCoolingTemp",
  sea_water_temp: "seaWaterCoolingTemp",
  fw_cooling_temp: "freshWaterCoolingTemp",
  fresh_water_temp: "freshWaterCoolingTemp",
  air_comp_press: "airCompressorPress",
  air_compressor_pressure: "airCompressorPress",
  starting_air_press: "startingAirPress",
  starting_air_pressure: "startingAirPress",
  control_air_press: "controlAirPress",
  control_air_pressure: "controlAirPress",
  er_temp: "engineRoomTemp",
  engine_room_temp: "engineRoomTemp",
  engine_room_temperature: "engineRoomTemp",
  er_humidity: "engineRoomHumidity",
  engine_room_humidity: "engineRoomHumidity",
  me_running_hours: "meRunningHours",
  main_engine_hours: "meRunningHours",
};

export const GENERATOR_TELEMETRY_MAPPING: Record<string, any> = {
  dg_load_kw: "loadKw",
  generator_load_kw: "loadKw",
  dg_load_percent: "loadPercent",
  generator_load_percent: "loadPercent",
  dg_voltage: "voltage",
  generator_voltage: "voltage",
  dg_frequency: "frequency",
  generator_frequency: "frequency",
  dg_current: "current",
  generator_current: "current",
  dg_power_factor: "powerFactor",
  generator_pf: "powerFactor",
  dg_exhaust_temp: "exhaustTemp",
  generator_exhaust_temp: "exhaustTemp",
  dg_lub_oil_press: "lubOilPress",
  generator_lub_oil_press: "lubOilPress",
  dg_coolant_temp: "coolantTemp",
  generator_coolant_temp: "coolantTemp",
  dg_fuel_rack: "fuelRackPosition",
  generator_fuel_rack: "fuelRackPosition",
  dg_running_hours: "runningHours",
  generator_hours: "runningHours",
};
