import type { OperatorRole } from "../../domain/types.js";
import type { RoleInformationNeedCatalogPort } from "../domain/ports.js";
import type { RoleInformationNeedDefinition } from "../domain/types.js";

const ROLE_NEEDS: RoleInformationNeedDefinition[] = [
  {
    id: "chief-critical-machinery",
    role: "chief_engineer",
    category: "risk",
    title: "Critical machinery risk",
    userQuestion: "Which equipment can fail or affect safe operation today?",
    informationNeeded: ["Predicted status", "RUL", "failure mode", "confidence", "sensor evidence", "operating context"],
    sourceSignals: ["criticalItems", "pdmRisks", "dataQualityWarnings"],
    primaryAction: "Open the highest-risk PdM/equipment item",
    route: "/attention-inbox?queue=needs_review",
    uiPattern: "PdM decision card with evidence, confidence, source freshness, and Create Work Order CTA",
    trustEvidence: ["sensor trend", "model confidence", "data freshness", "source health", "prediction lineage"],
    businessGoal: "uptime",
    basePriority: "urgent",
  },
  {
    id: "chief-blocked-work",
    role: "chief_engineer",
    category: "work",
    title: "Blocked or waiting-on-parts work",
    userQuestion: "Which maintenance items are stuck and why?",
    informationNeeded: ["blocker reason", "parts status", "owner", "ETA", "impact if delayed"],
    sourceSignals: ["blockedItems", "waitingOnParts"],
    primaryAction: "Resolve blocker or assign escalation owner",
    route: "/attention-inbox?queue=blocked",
    uiPattern: "Blocker queue with owner, ETA, parts availability, and escalation action",
    trustEvidence: ["parts availability", "work order status", "owner", "timestamped blocker notes"],
    businessGoal: "conversion",
    basePriority: "important",
  },
  {
    id: "chief-closeout-quality",
    role: "chief_engineer",
    category: "work",
    title: "Closeout quality and PdM feedback",
    userQuestion: "Which completed jobs still need evidence, verification, or model feedback?",
    informationNeeded: ["work performed", "root cause", "parts used", "labour", "downtime", "supervisor verification", "prediction outcome"],
    sourceSignals: ["readyForCloseout"],
    primaryAction: "Close work with evidence and PdM feedback",
    route: "/attention-inbox?queue=ready_to_close",
    uiPattern: "Guided closeout wizard",
    trustEvidence: ["structured closeout", "verification", "photos/notes", "prediction correctness"],
    businessGoal: "retention",
    basePriority: "important",
  },
  {
    id: "second-engine-room-watch",
    role: "second_engineer",
    category: "risk",
    title: "Engine-room watch exceptions",
    userQuestion: "Which readings, defects, or checklists need my attention this watch?",
    informationNeeded: ["assigned jobs", "equipment readings", "exceptions", "checklist state", "handover notes"],
    sourceSignals: ["attentionItems", "handoverNotes", "dataQualityWarnings"],
    primaryAction: "Open the active watch attention queue",
    route: "/attention-inbox",
    uiPattern: "Watch card with readings, exceptions, and next action",
    trustEvidence: ["fresh telemetry", "logbook context", "handover note", "checklist state"],
    businessGoal: "safety",
    basePriority: "important",
  },
  {
    id: "deck-handover",
    role: "deck_officer",
    category: "handover",
    title: "Watch handover readiness",
    userQuestion: "What must be handed over, acknowledged, or clarified before watch change?",
    informationNeeded: ["unresolved notes", "safety observations", "route/weather context", "compliance items", "acknowledgement state"],
    sourceSignals: ["handoverNotes", "attentionItems"],
    primaryAction: "Prepare and share watch handover",
    route: "/attention-inbox?view=handover",
    uiPattern: "Handover lifecycle panel: draft, shared, acknowledged, clarification requested",
    trustEvidence: ["acknowledgement", "timestamp", "author", "unresolved carry-forward list"],
    businessGoal: "trust",
    basePriority: "urgent",
  },
  {
    id: "deck-compliance-log",
    role: "deck_officer",
    category: "compliance",
    title: "Logbook and compliance gaps",
    userQuestion: "What could create a regulatory, safety, or audit issue?",
    informationNeeded: ["missing logs", "certificate/compliance alerts", "rest-hour exceptions", "audit trail"],
    sourceSignals: ["attentionItems", "dataQualityWarnings"],
    primaryAction: "Open compliance/logbook exceptions",
    route: "/logs?tab=compliance",
    uiPattern: "Compliance inbox with audit and correction actions",
    trustEvidence: ["audit log", "correction history", "required fields", "timestamp"],
    businessGoal: "trust",
    basePriority: "important",
  },
  {
    id: "technician-task-clarity",
    role: "technician",
    category: "work",
    title: "Assigned job clarity",
    userQuestion: "What do I need to fix, inspect, photograph, or close out next?",
    informationNeeded: ["asset", "fault description", "steps", "parts", "safety notes", "evidence required", "offline state"],
    sourceSignals: ["attentionItems", "readyForCloseout", "offlinePending"],
    primaryAction: "Open assigned task or scan equipment",
    route: "/equipment-scan",
    uiPattern: "Mobile task card with QR scan, checklist, parts, and evidence capture",
    trustEvidence: ["equipment identity", "checklist", "part list", "offline saved status"],
    businessGoal: "conversion",
    basePriority: "important",
  },
  {
    id: "fleet-risk-ranking",
    role: "fleet_manager",
    category: "business",
    title: "Fleet risk ranking",
    userQuestion: "Which vessel or asset creates the biggest operational and cost risk?",
    informationNeeded: ["vessel ranking", "critical risks", "downtime exposure", "overdue work", "cost impact", "trend"],
    sourceSignals: ["criticalItems", "blockedItems", "pdmRisks"],
    primaryAction: "Review escalations and downtime exposure",
    route: "/analytics/maintenance",
    uiPattern: "Fleet exception dashboard with ranked risk and action owner",
    trustEvidence: ["risk trend", "cost exposure", "maintenance backlog", "owner", "source health"],
    businessGoal: "uptime",
    basePriority: "urgent",
  },
  {
    id: "superintendent-intervention",
    role: "superintendent",
    category: "business",
    title: "Intervention queue",
    userQuestion: "Where should I intervene to protect uptime, compliance, and maintenance quality?",
    informationNeeded: ["blocked work", "critical risk", "repeated defects", "compliance exposure", "closeout quality"],
    sourceSignals: ["criticalItems", "blockedItems", "readyForCloseout", "dataQualityWarnings"],
    primaryAction: "Open escalations queue",
    route: "/attention-inbox?queue=blocked",
    uiPattern: "Exception queue with risk, cause, owner, and escalation action",
    trustEvidence: ["audit trail", "work-order history", "prediction feedback", "closeout evidence"],
    businessGoal: "uptime",
    basePriority: "urgent",
  },
  {
    id: "admin-system-trust",
    role: "system_admin",
    category: "system",
    title: "System trust and data health",
    userQuestion: "Is ARUS healthy enough for operators to trust the data and actions?",
    informationNeeded: ["sync health", "offline conflicts", "sensor health", "API health", "failed integrations", "audit status"],
    sourceSignals: ["conflicts", "offlinePending", "dataQualityWarnings"],
    primaryAction: "Open system health and offline outbox",
    route: "/offline-outbox",
    uiPattern: "System health dashboard with sync, conflicts, source health, and retry actions",
    trustEvidence: ["sync status", "conflict resolution", "sensor health", "audit events", "last successful sync"],
    businessGoal: "trust",
    basePriority: "urgent",
  },
];

const ALL_ROLES: OperatorRole[] = [
  "chief_engineer",
  "second_engineer",
  "deck_officer",
  "technician",
  "fleet_manager",
  "superintendent",
  "system_admin",
];

export class StaticRoleInformationCatalogAdapter implements RoleInformationNeedCatalogPort {
  listRoles(): OperatorRole[] {
    return ALL_ROLES;
  }

  listForRole(role: OperatorRole): RoleInformationNeedDefinition[] {
    return ROLE_NEEDS.filter((need) => need.role === role);
  }
}
